import assert from 'node:assert/strict';
import { boundedRecordQuery, uniqueMemberMatch, uniqueTruckMatch } from '../desktop-ui/lib/people-fleet-contract';
import { resolveScheduleDeepLink, scheduleMatchesQuery, type ScheduleAppointment } from '../desktop-ui/lib/schedule-contract';
const member={id:'synthetic person',name:'Synthetic Person'};
assert.equal(uniqueMemberMatch([member],'Person, Synthetic'),member);
assert.equal(uniqueMemberMatch([member],'Synthetic'),null,'partial names cannot auto-open a person');
assert.equal(uniqueMemberMatch([member,{...member,id:'other'}],'Synthetic Person'),null,'ambiguous names do not auto-open');
assert.equal(boundedRecordQuery(new URLSearchParams({member:'x'.repeat(201)}),'member'),'');
const truck={id:'Truck# 12',label:'Truck# 12'};
assert.equal(uniqueTruckMatch([truck],'12'),truck);assert.equal(uniqueTruckMatch([truck],'Truck 12'),truck);
assert.equal(uniqueTruckMatch([truck],'2'),null);assert.equal(uniqueTruckMatch([truck],'unrelated 12'),null);
assert.equal(uniqueTruckMatch([truck,{id:'Truck 12',label:'Truck 12'}],'12'),null);
const source:ScheduleAppointment={recordId:'2026-09-04:appointment:101',appointmentId:'101',version:'synthetic',callAhead:'not_called',jkNumber:'JK-SYNTHETIC',appointmentType:'Estimate',status:'Open',appointmentUrl:'',appointmentTime:'',appointmentStartMinutes:null,appointmentEndMinutes:null,hasScheduledTime:false,customerName:'Synthetic Customer',customerEmail:'',phone:'5551230000',address:'Test, New Orleans',territory:'New Orleans',truck:'Truck 12',driver:'',navigator:'',paymentType:'',paymentAmount:0,tipAmount:0,junkItems:[],appointmentNotes:[],cancellationReason:'',location:null};
const second={...source,recordId:'2026-09-04:appointment:102',appointmentId:'102',appointmentType:'Job'};
assert.equal(resolveScheduleDeepLink([source,second],'JK-SYNTHETIC','').recordId,null,'same JK is a filter, not appointment identity');
assert.equal(resolveScheduleDeepLink([source,second],'Synthetic Customer','').recordId,null,'ambiguous customer names remain choices');
assert.equal(resolveScheduleDeepLink([source],'Synthetic','').recordId,null,'fuzzy query never auto-opens');
assert.equal(resolveScheduleDeepLink([source],'JK-SYNTHETIC','').recordId,source.recordId);
assert.equal(resolveScheduleDeepLink([source,second],'','102').recordId,second.recordId);
assert.equal(resolveScheduleDeepLink([source,second],'','2026-09-04:appointment:101').recordId,source.recordId);
assert.equal(resolveScheduleDeepLink([source],'JK-SYNTHETIC','invalid').recordId,null,'invalid explicit identity cannot fall back to another record');
assert.equal(resolveScheduleDeepLink([source],'','2026-09-05:appointment:101').recordId,null,'full identity preserves source operating date');
assert.equal(resolveScheduleDeepLink([source],'x'.repeat(201),'').query,'');
assert.equal(scheduleMatchesQuery(source,'555123'),true);assert.equal(scheduleMatchesQuery(source,'Unknown customer'),false);
console.log('Bounded member/truck and exact appointment deep-link tests passed; ambiguous/fuzzy matches remain selectable filters.');
