import { useMemo, useRef, useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowUpRight, ChevronLeft, ChevronRight, Phone, Search, Star } from 'lucide-react';
import { Button } from './components/ui/button';
import { commercialDate, commercialMoney, type Lead, type MarketingData, type Review } from './lib/commercial-contract';
import { browseLeads, defaultLeadFilters, leadPhoneHref, type LeadFilters } from './lib/lead-browser';
import { browseReviews, defaultReviewFilters, recordedReviewCrew, type ReviewFilters } from './lib/review-browser';
import './campaign-workspace.css';

export const campaignLeadStatus = (lead: Lead) => lead.appointmentId ? (lead.completed ? 'Completed job' : 'Booking matched') : ({ needs_follow_up: 'Needs follow-up', lost: lead.reason === 'customer_declined' ? 'Customer declined' : 'No booking matched', booked: 'Booking reported', recovered: 'Recovery reported', unqualified: 'Not qualified' }[lead.status] || 'Outcome not recorded');
export const campaignSourceUrl = (url: string) => /^https?:\/\//i.test(url) ? url : undefined;
export const campaignOutcomes = [['needs_follow_up', 'Needs follow-up'], ['lost', 'No booking matched'], ['booked', 'Booked · operator reported'], ['recovered', 'Recovered · operator reported'], ['unqualified', 'Not qualified']] as const;
export const campaignReasons = ['', 'availability', 'pricing', 'missed_call', 'no_follow_up', 'competitor', 'out_of_area', 'service_not_offered', 'customer_declined', 'other'];
function SourceLink({ url, children }: { url: string; children: ReactNode }) {
  return campaignSourceUrl(url) ? <a className="campaign-source-link" href={url} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={14}/></a> : null;
}
function Pages({ page, pageCount, onPage, disabled }: { page: number; pageCount: number; onPage: (page: number) => void; disabled?: boolean }) {
  return <nav className="campaign-pages" aria-label="Queue pages"><Button size="sm" variant="ghost" aria-label="Previous page" disabled={disabled || page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft size={16}/></Button><span>Page {page} of {pageCount}</span><Button size="sm" variant="ghost" aria-label="Next page" disabled={disabled || page >= pageCount} onClick={() => onPage(page + 1)}><ChevronRight size={16}/></Button></nav>;
}
function Empty({ children }: { children: ReactNode }) { return <div className="campaign-empty">{children}</div>; }

export function CampaignLeads({ leads, draft, locked, onDraft, onReview }: { leads: Lead[]; draft: Lead | null; locked: boolean; onDraft: (lead: Lead | null) => void; onReview: () => void }) {
  const [filters, setFilters] = useState<LeadFilters>(defaultLeadFilters);
  const [page, setPage] = useState(1), [selectedId, setSelectedId] = useState(''), [mobileDetail, setMobileDetail] = useState(false);
  const heading = useRef<HTMLHeadingElement>(null);
  const result = useMemo(() => browseLeads(leads, filters, page, 8), [leads, filters, page]);
  const selected = draft || result.rows.find(lead => lead.id === selectedId) || result.rows[0];
  const recorded = leads.find(lead => lead.id === selected?.id) || selected;
  const territories = useMemo(() => [...new Set(leads.map(lead => lead.territory))].sort(), [leads]);
  const edit = (values: Partial<Lead>) => { if (selected) onDraft({ ...selected, ...values }); };
  const filter = (next: Partial<LeadFilters>) => { setFilters(current => ({ ...current, ...next })); setPage(1); setMobileDetail(false); };
  const queueLocked = locked || Boolean(draft);
  const selectLead = (lead: Lead) => { setSelectedId(lead.id); setMobileDetail(true); requestAnimationFrame(() => { heading.current?.focus({ preventScroll: true }); if (window.matchMedia('(max-width: 760px)').matches) heading.current?.closest('.campaign-detail')?.scrollIntoView({ block: 'start' }); }); };
  return <div className={`campaign-split ${mobileDetail ? 'campaign-detail-open' : ''}`}>
    <section className="campaign-panel campaign-queue" aria-label="Lead queue">
      <header><span className="campaign-eyebrow">Follow up</span><h2>Your next conversations</h2><p>Start with the people still looking for help.</p></header>
      <fieldset disabled={queueLocked} className="campaign-filters">
        <label className="campaign-search"><Search size={16}/><input aria-label="Search leads" type="search" placeholder="Search name, phone or notes…" value={filters.query} onChange={event => filter({ query: event.target.value })}/></label>
        <div className="campaign-filter-pair"><select aria-label="Lead territory" value={filters.territory} onChange={event => filter({ territory: event.target.value })}><option value="">All territories</option>{territories.map(territory => <option key={territory}>{territory}</option>)}</select><select aria-label="Lead order" value={filters.order} onChange={event => filter({ order: event.target.value as LeadFilters['order'] })}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="value">Highest quote</option></select></div>
        <div className="campaign-queue-tabs" aria-label="Lead quick filters"><button aria-pressed={filters.queue === 'recover' && filters.contact === ''} onClick={() => filter({ queue: 'recover', contact: '' })}>To follow up <span>{leads.filter(lead => ['lost', 'needs_follow_up'].includes(lead.status)).length}</span></button><button aria-pressed={filters.queue === 'recover' && filters.contact === 'uncontacted'} onClick={() => filter({ queue: 'recover', contact: 'uncontacted' })}>No contact</button><button aria-pressed={filters.queue === 'all'} onClick={() => filter({ queue: 'all', contact: '' })}>All</button></div>
        <details className="campaign-more-filters"><summary>More filters</summary><div className="campaign-filter-pair"><select aria-label="Lead outcome filter" value={filters.queue} onChange={event => filter({ queue: event.target.value as LeadFilters['queue'] })}><option value="recover">To follow up</option><option value="followup">Needs follow-up</option><option value="lost">No booking matched / closed</option><option value="booked">Booking / recovery reported</option><option value="all">All outcomes</option></select><select aria-label="Lead contact filter" value={filters.contact} onChange={event => filter({ contact: event.target.value as LeadFilters['contact'] })}><option value="">Any contact status</option><option value="uncontacted">No contact recorded</option><option value="contacted">Contact recorded</option></select></div></details>
      </fieldset>
      <p className="campaign-count" aria-live="polite">{result.start}–{result.end} of {result.total} matching leads</p>
      <div className="campaign-queue-list">{result.rows.map(lead => <button className="campaign-queue-row" key={lead.id} aria-pressed={selected?.id === lead.id} disabled={queueLocked} onClick={() => selectLead(lead)}><span className="campaign-row-heading"><strong>{lead.customer}</strong><ChevronRight size={15}/></span><span>{lead.territory} · {commercialDate(lead.calledAt)}</span><span className="campaign-row-preview">{lead.intent}</span><small>{lead.contacted ? 'Contact recorded' : 'No contact recorded'} · {campaignLeadStatus(lead)}</small></button>)}</div>
      {!result.total && <Empty><strong>No leads match.</strong><p>Try another search or show all leads.</p><Button variant="outline" onClick={() => { setFilters({ ...defaultLeadFilters, queue: 'all' }); setPage(1); }}>Show all leads</Button></Empty>}
      <Pages page={result.page} pageCount={result.pageCount} disabled={queueLocked} onPage={next => { setPage(next); setSelectedId(''); }}/>
    </section>
    <section className="campaign-panel campaign-detail" aria-label="Lead conversation">
      <Button className="campaign-back" variant="ghost" disabled={queueLocked} onClick={() => setMobileDetail(false)}><ArrowLeft size={16}/>Back to leads</Button>
      {selected && recorded ? <>
        <header><span className="campaign-eyebrow campaign-accent">{campaignLeadStatus(recorded)} · {recorded.contacted ? 'Contact recorded' : 'No contact recorded'}</span><h2 ref={heading} tabIndex={-1}>{recorded.customer}</h2><p>{recorded.territory} · {recorded.source || 'SearchKings'} · {commercialDate(recorded.calledAt)}</p></header>
        <div className="campaign-next-action"><h3>{recorded.appointmentId ? 'Keep the conversation connected' : recorded.contacted ? 'Pick up the conversation' : 'Start with a callback'}</h3><p>{recorded.appointmentId ? 'Review the matched appointment and record any follow-up with the customer.' : 'Read the call summary, then reach out and record what happens next.'}</p><div className="campaign-actions">{leadPhoneHref(recorded.phone) ? <a className="campaign-primary-link" href={leadPhoneHref(recorded.phone)}><Phone size={15}/>Call customer</a> : <span>Phone unavailable</span>}<SourceLink url={recorded.sourceUrl}>Open call in SearchKings</SourceLink></div>{recorded.phone && <small>{recorded.phone}</small>}</div>
        <section className="campaign-context"><h3>What we know</h3><dl><dt>Call summary</dt><dd>{recorded.intent}</dd><dt>Booking</dt><dd>{recorded.appointmentId ? <a href={`/schedule?job=${encodeURIComponent(recorded.jk || recorded.appointmentId)}`} target="_blank" rel="noreferrer">{recorded.jk || recorded.appointmentId} · {recorded.completed ? 'Completed in JunkWare' : 'Matched in JunkWare'}</a> : 'No verified match in JunkWare.'}</dd><dt>Quoted value</dt><dd>{recorded.quotedValue == null ? 'Not recorded' : commercialMoney(recorded.quotedValue)}</dd><dt>Reason</dt><dd>{recorded.reason ? recorded.reason.replaceAll('_', ' ') : 'Not recorded'}</dd>{recorded.note && <><dt>Latest note</dt><dd className="campaign-preserve-text">{recorded.note}</dd></>}</dl></section>
        <form className="campaign-outcome" onSubmit={event => { event.preventDefault(); if (draft) onReview(); }}><h3>After the conversation</h3><fieldset disabled={locked}><label>Outcome<select value={selected.status} disabled={Boolean(selected.appointmentId)} onChange={event => edit({ status: event.target.value })}>{campaignOutcomes.map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label><label>Reason<select value={selected.reason} onChange={event => edit({ reason: event.target.value })}>{campaignReasons.map(reason => <option key={reason} value={reason}>{reason ? reason.replaceAll('_', ' ') : 'No reason recorded'}</option>)}</select></label><label className="campaign-checkbox"><input type="checkbox" checked={selected.contacted} onChange={event => edit({ contacted: event.target.checked })}/>Franchise contacted</label><label>Note or next step<textarea required maxLength={2000} placeholder="What happened, and what should happen next?" value={selected.note} onChange={event => edit({ note: event.target.value })}/></label></fieldset><div className="campaign-actions"><Button className="campaign-primary" type="submit" disabled={locked || !draft}>Review & save outcome</Button>{draft && <Button type="button" variant="ghost" disabled={locked} onClick={() => onDraft(null)}>Discard changes</Button>}</div><small>{selected.appointmentId ? 'The matched JunkWare booking is preserved. Contact details and notes remain editable.' : 'Reported outcomes do not create a JunkWare appointment.'}</small></form>
      </> : <Empty><h2>No conversation selected</h2><p>Choose a lead from the queue to see the next step.</p></Empty>}
    </section>
  </div>;
}

export function CampaignReviews({ reviews, canAssign, locked, selections, onSelect, onReview }: { reviews: Review[]; canAssign: boolean; locked: boolean; selections: Record<string, string>; onSelect: (id: string, appointment: string) => void; onReview: (review: Review) => void }) {
  const [filters, setFilters] = useState<ReviewFilters>(defaultReviewFilters);
  const [page, setPage] = useState(1), [selectedId, setSelectedId] = useState(''), [mobileDetail, setMobileDetail] = useState(false);
  const heading = useRef<HTMLHeadingElement>(null);
  const result = useMemo(() => browseReviews(reviews, filters, page), [reviews, filters, page]);
  const review = result.rows.find(row => row.id === selectedId) || result.rows[0];
  const locations = useMemo(() => [...new Set(reviews.map(row => row.location))].sort(), [reviews]);
  const filter = (next: Partial<ReviewFilters>) => { setFilters(current => ({ ...current, ...next })); setPage(1); setMobileDetail(false); };
  const queueLocked = locked || Object.keys(selections).length > 0;
  const appointment = review ? selections[review.id] ?? review.attribution?.appointmentId ?? '' : '';
  const crew = review ? recordedReviewCrew(review) : [];
  const candidate = review?.candidates.find(item => item.appointmentId === appointment);
  return <div className={`campaign-split ${mobileDetail ? 'campaign-detail-open' : ''}`}>
    <section className="campaign-panel campaign-queue" aria-label="Review queue"><header><span className="campaign-eyebrow">Google reviews via Podium</span><h2>Give great service its credit</h2><p>Read feedback. Respond. Connect the right job.</p></header>
      <fieldset className="campaign-filters" disabled={queueLocked}><label className="campaign-search"><Search size={16}/><input aria-label="Search reviews" type="search" placeholder="Search reviewer, feedback or crew…" value={filters.query} onChange={event => filter({ query: event.target.value })}/></label><div className="campaign-queue-tabs">{([{ queue: 'all', name: 'All', count: reviews.length }, { queue: 'response', name: 'Need response', count: reviews.filter(row => row.needsResponse === true).length }, { queue: 'unassigned', name: 'Need job match', count: reviews.filter(row => row.attribution?.status !== 'matched').length }] as const).map(item => <button key={item.queue} aria-pressed={filters.queue === item.queue} onClick={() => filter({ queue: item.queue })}>{item.name} <span>{item.count}</span></button>)}</div><div className="campaign-filter-pair"><select aria-label="Review location" value={filters.location} onChange={event => filter({ location: event.target.value })}><option value="">All locations</option>{locations.map(location => <option key={location}>{location}</option>)}</select><select aria-label="Review rating" value={filters.queue === 'low' ? 'low' : filters.rating} onChange={event => filter(event.target.value === 'low' ? { queue: 'low', rating: '' } : { queue: filters.queue === 'low' ? 'all' : filters.queue, rating: event.target.value })}><option value="">All ratings</option><option value="low">Low ratings · 1–3 stars</option>{[1, 2, 3, 4, 5].map(rating => <option key={rating} value={rating}>{rating} stars</option>)}</select></div><select aria-label="Review order" value={filters.order} onChange={event => filter({ order: event.target.value as ReviewFilters['order'] })}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></fieldset>
      <p className="campaign-count" aria-live="polite">{result.start}–{result.end} of {result.total} matching reviews</p><div className="campaign-queue-list">{result.rows.map(row => <button key={row.id} className="campaign-queue-row" aria-pressed={row.id === review?.id} disabled={queueLocked} onClick={() => { setSelectedId(row.id); setMobileDetail(true); requestAnimationFrame(() => { heading.current?.focus({ preventScroll: true }); if (window.matchMedia('(max-width: 760px)').matches) heading.current?.closest('.campaign-detail')?.scrollIntoView({ block: 'start' }); }); }}><span className="campaign-row-heading"><strong>{row.customer}</strong><span className="campaign-stars"><Star size={13} fill="currentColor"/>{row.stars}/5</span></span><span>{row.location} · {commercialDate(row.createdAt)}</span><span className="campaign-row-preview">{row.excerpt || 'Rating only'}</span><small>{row.needsResponse === true ? 'Needs response · ' : ''}{row.attribution?.status === 'matched' ? 'Job matched' : 'Needs job match'}</small></button>)}</div>{!result.total && <Empty><strong>No reviews match.</strong><p>Try another filter.</p><Button variant="outline" onClick={() => { setFilters(defaultReviewFilters); setPage(1); }}>Show all reviews</Button></Empty>}<Pages page={result.page} pageCount={result.pageCount} disabled={queueLocked} onPage={next => { setPage(next); setSelectedId(''); }}/><p className="campaign-count">Latest 100 per location. Response status comes from Podium.</p>
    </section>
    <section className="campaign-panel campaign-detail" aria-label="Review detail"><Button className="campaign-back" variant="ghost" disabled={queueLocked} onClick={() => setMobileDetail(false)}><ArrowLeft size={16}/>Back to reviews</Button>{review ? <><header><span className="campaign-eyebrow campaign-accent">{review.needsResponse === true ? 'Needs response' : 'Customer feedback'}</span><h2 tabIndex={-1} ref={heading}>{review.customer}</h2><p>{review.location} · {commercialDate(review.createdAt)}</p></header><div className="campaign-review-quote"><span className="campaign-stars"><Star size={18} fill="currentColor"/>{review.stars} out of 5</span><blockquote>{review.excerpt || 'This customer left a rating without written feedback.'}</blockquote><SourceLink url={review.sourceUrl}>Open original review / respond</SourceLink><small>Responses are managed in Podium or Google.</small></div><section className="campaign-context"><h3>The job behind the review</h3>{review.attribution?.status === 'matched' ? <dl><dt>Matched job</dt><dd><a href={`/schedule?job=${encodeURIComponent(review.attribution.jkNumber || review.attribution.appointmentId || '')}`} target="_blank" rel="noreferrer">{review.attribution.jkNumber || review.attribution.appointmentId || 'Completed appointment'}</a></dd><dt>Recorded crew</dt><dd>{crew.length ? crew.join(' · ') : 'Crew not recorded'}</dd></dl> : <p>No completed appointment has been confirmed for this review.</p>}</section><section className="campaign-match"><h3>{review.attribution?.status === 'matched' ? 'Change the job match' : 'Find the right job'}</h3><p>Review the completed appointment before giving the crew credit.</p><label>Completed appointment ID<input disabled={locked || !canAssign} list={`campaign-candidates-${review.id}`} value={appointment} placeholder="Choose a suggestion or enter the ID" onChange={event => onSelect(review.id, event.target.value)}/></label><datalist id={`campaign-candidates-${review.id}`}>{review.candidates.map(item => <option key={item.appointmentId} value={item.appointmentId}>{item.label}</option>)}</datalist>{candidate && <p>{candidate.label}</p>}{appointment && <a className="campaign-source-link" href={`/schedule?job=${encodeURIComponent(candidate?.jkNumber || (appointment === review.attribution?.appointmentId ? review.attribution?.jkNumber : '') || appointment)}`} target="_blank" rel="noreferrer">Review appointment<ArrowUpRight size={14}/></a>}<small>{review.candidates.length} name-match suggestions · A suggestion is not a confirmed match.</small><Button className="campaign-primary" disabled={locked || !canAssign || !appointment} onClick={() => onReview(review)}>Review job match</Button>{!canAssign && <p>Manager access is required to change a job match.</p>}</section></> : <Empty><h2>No review selected</h2><p>Choose a review from the queue.</p></Empty>}</section>
  </div>;
}

export function CampaignResults({ data }: { data: MarketingData }) {
  const { totals, sources } = data;
  return <div className="campaign-results"><section className="campaign-results-hero"><div><span className="campaign-eyebrow">Attributed completed revenue · {data.range}</span><strong>{commercialMoney(totals.revenue)}</strong><p>{totals.completed} completed jobs · Verified in JunkWare</p></div><div><h2>Is demand turning into work?</h2><p>{totals.bookings} matched bookings from {totals.qualified} qualified calls.</p><small>{data.jobChange}</small></div></section><section className="campaign-panel"><h2>Where demand goes</h2><div className="campaign-funnel">{[[totals.calls, 'Tracked calls'], [totals.qualified, 'Qualified calls'], [totals.bookings, 'Matched bookings'], [totals.completed, 'Completed jobs']].map(([value, name], index) => <article key={name}><span className="campaign-stage">0{index + 1}</span><strong>{value}</strong><span>{name}</span></article>)}</div><p className="campaign-footnote">SearchKings tracks calls. JunkWare confirms completed jobs. Booking matches use the existing seven-day phone-match rule.</p></section><section className="campaign-panel"><h2>Which territories are producing?</h2><div className="campaign-table-scroll" role="region" aria-label="Territory results" tabIndex={0}><table><thead><tr><th>Territory</th><th>Completed jobs</th><th>Completed revenue</th><th>Paid media cost</th><th>Revenue / ad spend</th></tr></thead><tbody>{sources.map(source => <tr key={source.source}><th scope="row">{source.source}</th><td>{source.completed ?? 'Unavailable'}</td><td>{commercialMoney(source.revenue)}</td><td>{commercialMoney(source.cost)}</td><td>{source.cost > 0 ? `${(source.revenue / source.cost).toFixed(2)}×` : 'No recorded spend'}</td></tr>)}</tbody></table></div>{!sources.length && <Empty>No territory results available for this period.</Empty>}<p className="campaign-footnote">Ad spend return is attributed completed revenue ÷ recorded media cost. It is not profit.</p></section></div>;
}
