import { useState } from 'react';
import { CircleAlert, Package, Plus, Search, Tag, Wallet } from 'lucide-react';
import { CapitalEmpty, CapitalPageHeader, CapitalStat } from './capital-ui';
import { commercialMoney as money, commercialDate, type FinanceData, type ResaleRecord } from './lib/commercial-contract';
export function CapitalResale({ data, onAdd, onReview }: { data: FinanceData; onAdd: () => void; onReview: (item: ResaleRecord) => void }) {
  const [query,setQuery]=useState('');
  const [filter,setFilter]=useState<'all' | ResaleRecord['status']>('all');
  const open=data.resale.filter(item=>item.status!=='sold'), sold=data.resale.filter(item=>item.status==='sold');
  const rows=data.resale.filter(item=>(filter==='all'||item.status===filter)&&[item.itemNumber,item.itemName,item.source,item.marketplace].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
  const labels={to_list:'To list',listed:'Listed',sold:'Sold'};
  return <div className="capital-page capital-resale">
    <CapitalPageHeader eyebrow="RECOVERED VALUE" title="Resale inventory" description="Track every item from pickup to listing and recorded sale." action={<button className="capital-button capital-button-primary" onClick={onAdd}><Plus size={15}/>Add item</button>}/>
    <section className="capital-stat-grid" aria-label="Resale summary"><CapitalStat primary icon={Package} label="On hand" value={open.length} detail="Recorded inventory · not yet sold"/><CapitalStat icon={Tag} label="Asking value" value={money(open.reduce((sum,item)=>sum+item.askingPrice,0))} detail="Entered prices for on-hand items"/><CapitalStat icon={Wallet} label="Recorded sales" value={money(sold.reduce((sum,item)=>sum+item.soldPrice,0))} detail={`${sold.length} sold records · not QBO verified`}/><CapitalStat warning={data.resale.some(item=>item.status==='to_list')} icon={CircleAlert} label="Ready to list" value={data.resale.filter(item=>item.status==='to_list').length} detail="Items awaiting a listing decision"/></section>
    <section className="capital-panel" aria-label="Resale inventory register"><header><div><span className="capital-eyebrow">INVENTORY REGISTER</span><h3>Items & disposition</h3></div><span className="capital-date">{rows.length} of {data.resale.length} items</span></header>
      <div className="capital-toolbar"><div className="capital-filter-group" role="group" aria-label="Filter resale inventory">{(['all','to_list','listed','sold'] as const).map(key=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{key==='all'?'All items':labels[key]}</button>)}</div><label className="capital-search"><Search size={15}/><input aria-label="Search resale inventory" placeholder="Search item or source job" value={query} onChange={event=>setQuery(event.target.value)}/></label></div>
      {rows.length ? <div className="capital-inventory-grid">{rows.map(item=><article className="capital-inventory-card" key={item.itemId}><div className="capital-inventory-image">{item.photos?.length ? <button onClick={()=>onReview(item)} aria-label={`View ${item.photos.length} photos of ${item.itemName}`}><img src={`/api/resale-items/photos/${item.photos[0].photoId}`} alt={item.itemName} loading="lazy"/><span>{item.photos.length} photos</span></button> : <Package size={32}/>}<span className={`capital-status ${item.status==='to_list'?'warning':''}`}>{labels[item.status]}</span></div><div className="capital-inventory-body"><small>{item.itemNumber || 'Inventory record'} · {commercialDate(item.acquiredDate)}</small><h3>{item.itemName}</h3><dl><div><dt>Source</dt><dd>{item.source || 'Source missing'}</dd></div><div><dt>Listing</dt><dd>{item.marketplace || 'Not specified'}</dd></div><div><dt>{item.status==='sold'?'Sold for':'Asking price'}</dt><dd>{money(item.status==='sold'?item.soldPrice:item.askingPrice)}</dd></div></dl>{item.notes && <p>{item.notes}</p>}<button className="capital-button" onClick={()=>onReview(item)}>{item.status==='listed'?'Record sale':'Review item'}</button></div></article>)}</div> : <CapitalEmpty icon={Package} title={data.resale.length?'No matching inventory':'Start building recovered value'} description={data.resale.length?'Try another search or filter.':'Add an item here, or send OpsBot photos with three lines: Resale, item name, price.'} action={data.resale.length ? <button className="capital-button" onClick={()=>{setQuery('');setFilter('all');}}>Clear filters</button> : <button className="capital-button capital-button-primary" onClick={onAdd}><Plus size={14}/>Add first item</button>}/>}
      <footer>To record a sale through OpsBot, use the item number and add “sold” on a fourth line. Recorded sales are separate from verified accounting payments.</footer>
    </section>
    <section className="finance-recovery-ledger"><div className="section-title"><div><span className="section-kicker">INVENTORY EVIDENCE</span><h2>Value & source coverage</h2><p>All recorded inventory · last observed {commercialDate(data.resaleUpdatedAt || '')}</p></div></div><div className="finance-recovery-ledger-summary"><article><span>Recorded cost</span><strong>{money(data.resale.reduce((sum,item)=>sum+item.cost,0))}</strong></article><article><span>Recorded sales</span><strong>{money(sold.reduce((sum,item)=>sum+item.soldPrice,0))}</strong></article><article><span>Open asking value</span><strong>{money(open.reduce((sum,item)=>sum+item.askingPrice,0))}</strong></article><article><span>Source entered</span><strong>{data.resale.filter(item=>item.source).length} / {data.resale.length}</strong></article></div><footer>OpsCenter inventory evidence · asking value is not realized income or a verified deposit.</footer></section>
  </div>;
}
