import { truckDisplayText } from '../lib/junkware-trucks';
import { ConvoyRepairs } from './convoy-repairs';
import { Truck } from 'lucide-react';
import { Button } from './components/ui/button';
import { DrivingScoreDetails } from './driving-scores';
import { sameTruck, truckCondition, truckLoadLabel, recordedValue } from './lib/convoy-presentation';
import type { DesktopFleetSnapshot, DesktopFleetTruck, FleetIssueRow, FleetMaintenanceRow, FleetView } from './lib/people-fleet-contract';
import './convoy.css';

export type FleetRecord = { kind: 'truck' | 'load' | 'history' | 'issue' | 'checklist' | 'maintenance'; truck: DesktopFleetTruck; issue?: FleetIssueRow; record?: FleetMaintenanceRow; initialStatus?: 'scheduled' | 'completed' };
type Props = { snapshot: DesktopFleetSnapshot; trucks: DesktopFleetTruck[]; view: FleetView; truckId: string; onTruck: (id: string) => void; open: (record: FleetRecord) => void };
const money = (n: number | null) => n === null ? 'Not recorded' : n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const number = (n: number | null) => n === null ? 'Not recorded' : n.toLocaleString('en-US', { maximumFractionDigits: 1 });
const dateLabel = (date: string) => date ? new Date(`${date.slice(0,10)}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'Date not recorded';
function Status({ truck }: { truck: DesktopFleetTruck }) { return <span className={`convoy-status ${truck.readiness === 'Out of service' ? 'stop' : truck.readiness === 'Ready' ? 'ready' : 'attention'}`}>{truckCondition(truck)}</span>; }

export function ConvoyHistory({ snapshot, truck, open }: { snapshot: DesktopFleetSnapshot; truck: DesktopFleetTruck; open: Props['open'] }) {
  const records = [
    ...snapshot.issues.filter(row => sameTruck(row.truck, truck.id)).map(issue => ({ id: `issue:${issue.issueId}`, date: issue.updatedAt, title: issue.title, note: `Repair · ${issue.status.replaceAll('_', ' ')} · ${money(issue.cost)}`, action: () => open({kind:'issue',truck,issue}), label: 'View repair' })),
    ...snapshot.maintenance.filter(row => sameTruck(row.truck, truck.id)).map(record => ({ id: `service:${record.recordId}`, date: record.serviceDate, title: record.serviceType, note: `${record.status === 'scheduled' ? 'Scheduled service' : 'Completed service'} · ${money(record.cost)}`, action: () => open({kind:'maintenance',truck,record}), label: 'View service record' })),
  ].sort((a,b) => b.date.localeCompare(a.date));
  return <section className="convoy-history"><h3>Truck history</h3><p>Service dates and latest repair updates. Scheduled work remains separate from completed work.</p>{records.length ? records.map(row => <article className="convoy-row" key={row.id}><div><small>{dateLabel(row.date)}</small><strong>{row.title}</strong><p>{row.note}</p></div><Button variant="outline" size="sm" onClick={row.action}>{row.label}</Button></article>) : <p className="convoy-empty">No repair or service records have been recorded for this truck.</p>}</section>;
}

export function ConvoyViews({snapshot,trucks,view,truckId,onTruck,open}:Props) {
  const visible = trucks.filter(truck => !truckId || truck.id === truckId);
  const repairs = snapshot.issues.filter(row => row.status !== 'resolved');
  const scopedRepairs = snapshot.issues.filter(row => !truckId || sameTruck(row.truck, truckId));
  return <>
    <div className="convoy-toolbar"><label>Truck<select value={truckId} onChange={event=>onTruck(event.target.value)}><option value="">All trucks</option>{trucks.map(truck=><option key={truck.id} value={truck.id}>{truck.label}</option>)}{truckId&&!trucks.some(truck=>truck.id===truckId)&&<option value={truckId}>{truckId} · unavailable on this day</option>}</select></label><span>{truckId ? 'This truck stays selected across Convoy tabs.' : `${trucks.length} trucks in the fleet`}</span><a href={`/fleet-inspections?date=${encodeURIComponent(snapshot.date)}`}>Truck phone inspections</a></div>
    {truckId&&!visible.length&&<p className="convoy-empty">This truck is not available in this day’s records. Choose another truck or All trucks.</p>}
    {view==='overview'&&<>
      <div className="convoy-summary" aria-label="Fleet condition"><span><strong>{trucks.filter(t=>t.readiness==='Ready').length}</strong> inspected, no active repairs</span><span><strong>{trucks.filter(t=>t.readiness==='Out of service').length}</strong> out of service</span><span><strong>{trucks.filter(t=>t.checklist==='Missing').length}</strong> missing inspections</span></div>
      <div className="convoy-trucks">{visible.map(truck=>{const issues=repairs.filter(row=>sameTruck(row.truck,truck.id));const unknownLoad=truck.loadNeedsVerification||/provisional|verify/i.test(truck.loadLabel||'');return <article className="convoy-truck" key={truck.id}>
        <header><h2><Truck size={18}/>{truck.label}</h2><Status truck={truck}/></header>
        <p className="convoy-condition">{issues.length ? [...new Set(issues.map(row=>row.title))].join(' · ') : truck.readiness==='Unavailable' ? 'Repair records unavailable' : truck.checklist==='Missing' ? 'No completed inspection recorded' : truck.checklist==='Problem reported' ? 'Inspection reported a problem' : 'No active repairs'}</p>
        <dl><div><dt>Load</dt><dd>{truckLoadLabel(truck)}</dd>{!unknownLoad&&truck.loadPercent!==null&&<span className="convoy-load-meter" aria-label={truckDisplayText(`${truck.loadPercent}% full`)}><i style={{width:`${Math.min(Math.max(truck.loadPercent,0),100)}%`}}/></span>}</div><div><dt>Truck activity</dt><dd>{truck.operatingStatus}</dd><small>{truck.gpsAt ? `Reported ${new Date(truck.gpsAt).toLocaleTimeString('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'})}` : 'No GPS observation'}</small></div><div><dt>Inspection</dt><dd>{truck.checklist}</dd></div><div><dt>Driver</dt><dd>{recordedValue(truck.driver,'Not assigned')}</dd></div></dl>
        <div className="convoy-actions"><Button variant="outline" size="sm" onClick={()=>open({kind:'truck',truck})}>View truck</Button><Button variant="ghost" size="sm" onClick={()=>open({kind:'load',truck})}>Record current load</Button></div>
      </article>;})}</div>
    </>}
    {view==='maintenance'&&<ConvoyRepairs snapshot={snapshot} trucks={trucks} truckId={truckId} onTruck={onTruck} open={open}/>}
    {view==='service'&&<section className="convoy-panel"><header><h2>Service schedule</h2><p>Schedule upcoming work or record service already completed.</p></header>{visible.map(truck=>{const records=snapshot.maintenance.filter(row=>sameTruck(row.truck,truck.id));const completed=records.filter(r=>r.status==='completed').sort((a,b)=>b.serviceDate.localeCompare(a.serviceDate));const latest=[...new Map(completed.map(r=>r.serviceType).map(type=>[type,completed.find(r=>r.serviceType===type)!])).values()];const scheduled=records.filter(r=>r.status==='scheduled').sort((a,b)=>a.serviceDate.localeCompare(b.serviceDate));return <section className="convoy-service-truck" key={truck.id}><header className="convoy-heading"><div><h3>{truck.label}</h3><p>Odometer: {recordedValue(truck.odometer)} · Source service target: {recordedValue(truck.nextService,'Not available')}</p></div><div className="convoy-actions"><Button variant="outline" size="sm" onClick={()=>open({kind:'maintenance',truck,initialStatus:'scheduled'})}>Schedule service</Button><Button variant="outline" size="sm" onClick={()=>open({kind:'maintenance',truck,initialStatus:'completed'})}>Record completed service</Button></div></header>
        {!records.length&&<p className="convoy-empty">No service history recorded. Add the last completed service and its next date or mileage target.</p>}
        {latest.map(record=><p className="convoy-service-target" key={record.recordId}><strong>{record.serviceType}</strong> · Next date: {record.nextServiceDate?dateLabel(record.nextServiceDate):'Not recorded'}{record.nextServiceDate&&record.nextServiceDate<=snapshot.date?' · date target reached':''} · Next mileage: {number(record.nextServiceOdometer)}</p>)}
        {scheduled.map(record=><article className="convoy-row" key={record.recordId}><div><strong>{record.serviceType} · {dateLabel(record.serviceDate)}</strong><p>Scheduled{record.serviceDate<snapshot.date?' · scheduled date has passed':''}{record.vendor?` · ${record.vendor}`:''}</p></div><Button variant="outline" size="sm" onClick={()=>open({kind:'maintenance',truck,record})}>Update scheduled service</Button></article>)}
        {completed.length>0&&<details><summary>Completed service · {completed.length} records</summary>{completed.map(record=><article className="convoy-row" key={record.recordId}><div><strong>{record.serviceType} · {dateLabel(record.serviceDate)}</strong><p>Next date: {record.nextServiceDate?dateLabel(record.nextServiceDate):'Not recorded'} · Next mileage: {number(record.nextServiceOdometer)}</p></div><Button variant="outline" size="sm" onClick={()=>open({kind:'maintenance',truck,record})}>View service record</Button></article>)}</details>}
      </section>;})}</section>}
    {view==='scores'&&<section className="convoy-panel convoy-driving"><header><h2>Driving</h2><p>{dateLabel(snapshot.date)} · Scores and the driving records behind them.</p></header>{visible.map(truck=>{const rows=(snapshot.drivingScores||[]).filter(row=>sameTruck(row.truck,truck.id));const row=rows[0];return <details key={truck.id}><summary><strong>{truck.label}</strong><span>{row?.display||'No driving score available'}</span><span>{row?.drivers.length?row.drivers.join(', '):'Driver not confirmed'}</span><span>View driving details</span></summary>{row?<DrivingScoreDetails rows={rows}/>:<p className="convoy-empty">No scoring record is available for this truck and day. GPS activity alone does not establish a driving score.</p>}</details>;})}</section>}
    {view==='reports'&&<section className="convoy-panel"><header><h2>History & Costs</h2><p>{snapshot.date.slice(0,7)} · {snapshot.reportCoverageDays} observed days in the production and driving report. Missing costs stay “Not recorded.”</p></header>
      {visible.map(truck=>{const row=snapshot.reportRows.find(r=>sameTruck(r.truck,truck.id));const issues=scopedRepairs.filter(r=>sameTruck(r.truck,truck.id)&&r.updatedAt.startsWith(snapshot.date.slice(0,7)));const services=snapshot.maintenance.filter(r=>sameTruck(r.truck,truck.id)&&r.status==='completed'&&r.serviceDate.startsWith(snapshot.date.slice(0,7)));return <article className="convoy-report" key={truck.id}><header className="convoy-heading"><h3>{truck.label}</h3><Button variant="outline" size="sm" onClick={()=>open({kind:'history',truck})}>View truck history</Button></header><dl><div><dt>Jobs / revenue</dt><dd>{row?`${number(row.jobsCompleted)} jobs · ${money(row.revenue)}`:'Not available'}</dd></div><div><dt>Driving / idle</dt><dd>{row?`${number(row.miles)} mi · ${number(row.idleTimeMinutes)} min idle`:'Not available'}</dd></div><div><dt>Repair costs · records updated this month</dt><dd>{issues.length&&issues.every(r=>r.cost!==null)?money(issues.reduce((sum,r)=>sum+(r.cost??0),0)):'Not recorded'}</dd></div><div><dt>Downtime · records updated this month</dt><dd>{issues.length&&issues.every(r=>r.downtimeHours!==null)?`${number(issues.reduce((sum,r)=>sum+(r.downtimeHours??0),0))} hours`:'Not recorded'}</dd></div><div><dt>Completed service costs this month</dt><dd>{services.length&&services.every(r=>r.cost!==null)?money(services.reduce((sum,r)=>sum+(r.cost??0),0)):'Not recorded'}</dd></div><div><dt>Average truck driving score</dt><dd>{row?number(row.averageDriverScore):'Not available'}</dd></div></dl></article>;})}
      {!truckId&&snapshot.reportRows.filter(row=>!trucks.some(t=>sameTruck(t.id,row.truck))).map(row=><article className="convoy-row" key={row.truck}><div><strong>{truckDisplayText(row.truck)}</strong><p>{number(row.jobsCompleted)} jobs · {money(row.revenue)} · Report-only record; no physical truck details.</p></div></article>)}
      {visible.length===1&&<ConvoyHistory snapshot={snapshot} truck={visible[0]} open={open}/>}
    </section>}
  </>;
}
