import {useEffect,useRef,useState} from 'react';
import {Button} from './components/ui/button';
import type {AppointmentCreationReceipt} from './appointment-creation';
import type {PrebookingCheck} from '../lib/prebooking-duplicates';

type Estimate = {id:string;jk:string;customer:string;phone:string;address:string;territory:string};
export default function EstimateBooking({estimate,saved,onBusyChange,canWrite=true}: {estimate:Estimate;saved:()=>void;onBusyChange?:(busy:boolean)=>void;canWrite?:boolean}) {
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago'}).format(new Date());
  const key=`estimate-booking:${estimate.id}`;
  const [open,setOpen]=useState(false),[date,setDate]=useState(today),[time,setTime]=useState('09:00'),[duration,setDuration]=useState(1),[notes,setNotes]=useState(''),[reason,setReason]=useState(''),[separate,setSeparate]=useState(false);
  const [check,setCheck]=useState<PrebookingCheck|null>(null),[receipt,setReceipt]=useState<AppointmentCreationReceipt|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [requestId,setRequestId]=useState(()=>typeof window==='undefined'?'':localStorage.getItem(key)||'');
  const pending=useRef(false);
  const payload=()=>{const names=estimate.customer.trim().split(/\s+/);return {requestId,sourceEstimateAppointmentId:estimate.id,date,startTime:time,durationHours:duration,firstName:names.shift(),lastName:names.join(' '),phone:estimate.phone,serviceAddress:estimate.address,serviceZip:estimate.address.match(/\b\d{5}(?:-\d{4})?\b(?=\D*$)/)?.[0]||'',franchise:estimate.territory,notes,duplicateOverrideReason:reason};};
  useEffect(()=>{onBusyChange?.(busy);return()=>onBusyChange?.(false);},[busy,onBusyChange]);
  async function recover(id=requestId) {
    const response=await fetch(`/api/desktop/schedule/creation?requestId=${encodeURIComponent(id)}`,{cache:'no-store',credentials:'same-origin'});const body=await response.json();if(!response.ok)throw new Error(body.error||'Saved result unavailable.');setReceipt(body.receipt);
    if(body.receipt.status==='verified') {localStorage.removeItem(key);saved();}
    return body.receipt as AppointmentCreationReceipt;
  }
  useEffect(()=>{if(!requestId||receipt?.status!=='pending')return;const timer=window.setInterval(()=>{void recover().catch(()=>{});},3000);return()=>clearInterval(timer);},[requestId,receipt?.status]);
  async function review() {if(pending.current)return;pending.current=true;setBusy(true);setError('');try {const id=crypto.randomUUID();const response=await fetch('/api/desktop/schedule/creation/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload(),requestId:id})});const body=await response.json();if(!response.ok)throw new Error(body.error);setRequestId(id);setCheck(body.check);}catch(e){setError(e instanceof Error?e.message:'Review unavailable.');}finally{pending.current=false;setBusy(false);}}
  async function book() {if(pending.current||receipt||!check)return;pending.current=true;setBusy(true);setError('');localStorage.setItem(key,requestId);try {const response=await fetch('/api/desktop/schedule/creation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload(),duplicateReview:{fingerprint:check.fingerprint,createSeparate:separate}})});const body=await response.json();if(!response.ok&&!body.receipt)throw new Error(body.error);setReceipt(body.receipt);if(body.receipt.status==='verified'){localStorage.removeItem(key);saved();}}catch{setReceipt({requestId,status:'uncertain',error:'The booking result is unconfirmed. Check the saved result before another booking.'});}finally{pending.current=false;setBusy(false);}}
  const blocked=!canWrite||busy||Boolean(receipt);
  return <section className="appointment-create-section" aria-label="Book job from estimate"><header><strong>Book Job from Estimate</strong></header><p>Creates a new job linked to {estimate.jk}. The original estimate and quote stay intact.</p>{!open?<Button variant="brand" disabled={!canWrite} onClick={()=>{setOpen(true);if(localStorage.getItem(key)){setReceipt({requestId,status:'uncertain',error:'Checking the previous booking result.'});}if(localStorage.getItem(key))void recover().catch(e=>setError(e.message));}}>Book Job</Button>:<><fieldset disabled={blocked}><label>Job date<input aria-label="Job date" type="date" min={today} value={date} onChange={e=>{setDate(e.target.value);setCheck(null);}}/></label><label>Start time<select aria-label="Job start time" value={time} onChange={e=>{setTime(e.target.value);setCheck(null);}}>{Array.from({length:10},(_,i)=>`${String(i+8).padStart(2,'0')}:00`).map(t=><option key={t}>{t}</option>)}</select></label><label>Duration<select aria-label="Job duration" value={duration} onChange={e=>{setDuration(Number(e.target.value));setCheck(null);}}>{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n} value={n}>{n} hour{n>1?'s':''}</option>)}</select></label><label>Additional job notes<textarea value={notes} onChange={e=>{setNotes(e.target.value);setCheck(null);}} maxLength={2000}/></label></fieldset>{check&&<div><p>Review: {estimate.customer} · {date} · {time} · {duration} hour(s)</p>{check.matches.length>0&&<><p>Existing appointments: {check.matches.map(m=>`${m.jkNumber} · ${m.appointmentTime}`).join('; ')}</p><label><input type="checkbox" checked={separate} onChange={e=>setSeparate(e.target.checked)}/> Create a separate job</label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label></>}</div>}{!receipt&&(check?<Button variant="brand" disabled={busy||check.matches.length>0&&(!separate||reason.trim().length<10)} onClick={()=>void book()}>Book Job in JunkWare</Button>:<Button disabled={busy||!canWrite} onClick={()=>void review()}>Review Job Booking</Button>)}{receipt&&<p role="status">{receipt.status==='verified'?`Booked and verified: ${receipt.result?.jkNumber}`:receipt.status==='pending'?'Booking in progress…':receipt.error}</p>}{receipt?.result&&<a href={`/desktop?workspace=Schedule&scheduleView=board&date=${receipt.result.date}&appointment=${receipt.result.appointmentId}`}>Open booked job</a>}{receipt?.status==='failed'&&<Button onClick={()=>{localStorage.removeItem(key);setReceipt(null);setCheck(null);setError('');}}>Correct Booking</Button>}{receipt&&receipt.status!=='verified'&&<Button disabled={busy} onClick={()=>void recover().catch(e=>setError(e.message))}>Check Saved Result</Button>}</>}{error&&<p role="alert">{error}</p>}</section>;
}
