import type { FinanceData } from './lib/commercial-contract';
import { commercialMoney as money } from './lib/commercial-contract';
import type { TrendValues } from '../lib/finance-trend-comparison';
import './finance-trends.css';
const metrics: Array<{key:keyof TrendValues;label:string}> = [{key:'revenue',label:'Revenue'},{key:'jobs',label:'Jobs'},{key:'averageJob',label:'Average Job'},{key:'costs',label:'Total Costs'},{key:'profit',label:'Operating Profit'},{key:'margin',label:'Margin'}];
const format = (key:keyof TrendValues,v:number|null|undefined) => v == null ? 'Unavailable' : key === 'jobs' ? v.toLocaleString('en-US') : key === 'margin' ? `${v.toFixed(1)}%` : money(v);
const change = (key:keyof TrendValues,current:number|null|undefined,prior:number|null|undefined) => current == null || prior == null ? 'Unavailable' : key === 'margin' ? `${current-prior >= 0 ? '+' : ''}${(current-prior).toFixed(1)} pp` : prior === 0 ? current === 0 ? '0.0%' : 'No prior baseline' : `${current-prior >= 0 ? '+' : ''}${((current-prior)/Math.abs(prior)*100).toFixed(1)}%`;
export default function FinanceTrends({data}:{data:FinanceData}) {
  const selected = data.trendComparisons?.[data.date.slice(0,7)];
  const month = data.trends.find(m=>m.monthKey===data.date.slice(0,7));
  const headline:TrendValues = {revenue:month?.grossRevenue??null,jobs:month?.completedJobs??null,averageJob:month?.completedJobs?month.grossRevenue/month.completedJobs:null,costs:month?.totalOperatingExpenses??null,profit:month?.estimatedOperatingProfit??null,margin:month?.grossRevenue&&month.estimatedOperatingProfit!=null?month.estimatedOperatingProfit/month.grossRevenue*100:null};
  return <section className="finance-trends-shell"><div className="section-title"><div><span className="section-kicker">Month-to-month · Year-over-year</span><h2>Finance Trends</h2><p>{selected ? `${selected.currentStart}–${selected.currentEnd} vs ${selected.priorStart}–${selected.priorEnd}.` : 'Comparison unavailable.'} {selected ? `YOY ${selected.yearCurrentStart}–${selected.yearCurrentEnd} vs ${selected.yearPriorStart}–${selected.yearPriorEnd}.` : ''} Operating profit is estimated.</p></div></div>
    <div className="finance-trend-cards">{metrics.map(({key,label})=><article key={key}><span>{label}</span><strong>{format(key,headline[key])}</strong><b title={selected?`Compared daily totals: ${format(key,selected.current[key])} vs ${format(key,selected.prior[key])}`:undefined}>MTM {change(key,selected?.current[key],selected?.prior[key])}</b><small title={selected?`Current ${format(key,selected.yearCurrent[key])}; last year ${format(key,selected.yearPrior[key])}`:undefined}>YOY {change(key,selected?.yearCurrent[key],selected?.yearPrior[key])}</small></article>)}</div>
    <div className="finance-trend-scroll"><div className="finance-trend-head"><span>Month</span>{metrics.map(m=><span key={m.key}>{m.label}</span>)}</div><div className="finance-trend-table">{data.trends.map(month=>{
      const comparison=data.trendComparisons?.[month.monthKey];
      const monthValues:TrendValues={revenue:month.grossRevenue,jobs:month.completedJobs,averageJob:month.completedJobs?month.grossRevenue/month.completedJobs:null,costs:month.totalOperatingExpenses,profit:month.estimatedOperatingProfit,margin:month.estimatedOperatingProfit!=null&&month.grossRevenue?month.estimatedOperatingProfit/month.grossRevenue*100:null};
      return <article key={month.monthKey} className={month.monthKey===data.date.slice(0,7)?'current':''}><div><strong>{month.monthDisplay}</strong><small>{month.complete?'Complete':`Through ${month.dataThroughDate}`}</small>{comparison && <small title={`${comparison.currentStart}–${comparison.currentEnd} vs ${comparison.priorStart}–${comparison.priorEnd}`}>MTM vs {comparison.priorStart}–{comparison.priorEnd}</small>}{comparison && <small title={`${comparison.yearCurrentStart}–${comparison.yearCurrentEnd} vs ${comparison.yearPriorStart}–${comparison.yearPriorEnd}`}>YOY vs {comparison.yearPriorStart}–{comparison.yearPriorEnd}</small>}</div>{metrics.map(({key})=><div className="finance-trend-value" key={key}><strong>{format(key,monthValues[key])}</strong><small title={comparison?`Current ${format(key,comparison.current[key])}; prior ${format(key,comparison.prior[key])}`:undefined}>MTM {change(key,comparison?.current[key],comparison?.prior[key])}</small><small title={comparison?`Current ${format(key,comparison.yearCurrent[key])}; last year ${format(key,comparison.yearPrior[key])}`:undefined}>YOY <b>{change(key,comparison?.yearCurrent[key],comparison?.yearPrior[key])}</b></small></div>)}</article>;
    })}</div></div>{!data.trends.length && <div className="marketing-empty">No published monthly history available.</div>}</section>;
}
