import { truckDisplayText } from '../lib/junkware-trucks';
import TruckAgents from './truck-agents';
import { fleetSnapshotUrl } from './lib/fleet-snapshot';
import { ConvoyViews, ConvoyHistory, type FleetRecord } from './convoy-views';
import { convoyWarnings, truckLoadLabel, recordedValue } from './lib/convoy-presentation';
import { workspaceReady } from './navigation-performance';
import { useWorkspaceSnapshot } from './use-workspace-snapshot';
import { fetchWorkspace } from './lib/workspace-cache';
import { useWorkspaceRefresh, WorkspaceFreshness } from './workspace-freshness';
import { useCallback, useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';
import { Button } from './components/ui/button';
import { Input } from './components/ui/input';
import { Textarea } from './components/ui/textarea';
import { displayedGpsFreshness, boundedRecordQuery, uniqueTruckMatch } from './lib/people-fleet-contract';
import type { DesktopWorkspaceProps, FleetView, DesktopFleetSnapshot, DesktopFleetTruck, FleetIssueRow, FleetMaintenanceRow } from './lib/people-fleet-contract';
const nullVersion='74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b';
type Drawer=FleetRecord;
/** Parent renders the approved Fleet header and tabs. report may select an ISO month/date. */
export default function LiveFleet({date,view,report,onBusyChange}:DesktopWorkspaceProps<FleetView>){
  const deepLinkApplied=useRef('');
  const selectedDate=view==='reports'&&report&&/^\d{4}-\d{2}/.test(report)?`${report.slice(0,7)}-01`:date;
  const snapshotKey=fleetSnapshotUrl(selectedDate,view);
  const [snapshot,setSnapshot]=useWorkspaceSnapshot<DesktopFleetSnapshot>(snapshotKey);const [error,setError]=useState('');const [pending,setPending]=useState(false);const [active,setActive]=useState<Drawer|null>(null);const [serviceTruck,setServiceTruck]=useState('');const [draft,setDraft]=useState<Record<string,string>>({});const [answers,setAnswers]=useState<Record<string,{status:string;notes:string}>>({});const busy=useRef(false);const generation=useRef(0);const opener=useRef<HTMLElement|null>(null);const drawer=useRef<HTMLElement|null>(null);
  const loadSnapshot=useCallback(async(signal:AbortSignal)=>{const run=++generation.current;const body=await fetchWorkspace<DesktopFleetSnapshot>(snapshotKey,signal);if(run===generation.current&&!signal.aborted){setSnapshot(body);setActive(previous=>{if(!previous)return null;const truck=body.trucks.find((row:DesktopFleetTruck)=>row.id===previous.truck.id);if(previous.issue&&!body.issues.some(row=>row.issueId===previous.issue?.issueId))return null;return truck?{...previous,truck,issue:previous.issue?body.issues.find((row:FleetIssueRow)=>row.issueId===previous.issue?.issueId):undefined,record:previous.record?body.maintenance.find((row:FleetMaintenanceRow)=>row.recordId===previous.record?.recordId):undefined}:null;});}},[snapshotKey,setSnapshot]);
  const invalidate=useCallback(()=>{generation.current+=1;},[]);
  useEffect(()=>{setActive(null);setError('');},[selectedDate,view]);
  useEffect(()=>invalidate,[snapshotKey,invalidate]);
  useEffect(() => { if (snapshot) workspaceReady('Fleet'); }, [snapshot]);
  const freshness=useWorkspaceRefresh(loadSnapshot,snapshotKey,Boolean(active)||pending,30_000,snapshotKey);
  const refresh=freshness.refresh;
  useEffect(()=>{onBusyChange?.(Boolean(active)||pending);return()=>onBusyChange?.(false);},[Boolean(active),pending,onBusyChange]);
  const dialogKey=active?`${active.truck.id}:${active.kind}`:'';
  useEffect(()=>{if(!dialogKey)return;drawer.current?.focus();const handle=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy.current){setActive(null);opener.current?.focus();}if(event.key==='Tab'){const list=drawer.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]');if(!list?.length)return;const first=list[0],last=list[list.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle);},[dialogKey]);
  const open=useCallback((next:Drawer)=>{opener.current=document.activeElement as HTMLElement;setActive(next);setServiceTruck(next.truck.id);setError('');const source=next.issue||next.record;setDraft(source?Object.fromEntries(Object.entries(source).filter(([,value])=>value!==null&&typeof value!=='object').map(([key,value])=>[key,String(value)])):{cadence:'daily',inspector:next.truck.checklists.daily.inspector,serviceDate:date,status:next.kind==='issue'?'open':next.initialStatus||'completed',serviceType:'Oil change',severity:'monitor',percent:next.truck.loadNeedsVerification?'':next.truck.loadPercent?.toString()||'',location:'dump'});setAnswers(Object.fromEntries(next.truck.answers.map(answer=>[answer.itemId,{status:answer.status,notes:answer.notes}])));},[date]);
  useEffect(()=>{if(!snapshot||snapshot.date!==selectedDate||busy.current)return;const params=new URLSearchParams(window.location.search);const truck=boundedRecordQuery(params,'truck',40);const key=`${selectedDate}:${truck}`;if(!truck||deepLinkApplied.current===key)return;deepLinkApplied.current=key;const match=uniqueTruckMatch(snapshot.trucks,truck);if(match){setServiceTruck(match.id);open({kind:'truck',truck:match});}else setError('The linked truck is not uniquely available in this date’s source records.');},[snapshot,selectedDate,open]);
  const [lastRequest,setLastRequest]=useState('');
  const [confirmDelete,setConfirmDelete]=useState(false);
  useEffect(()=>setConfirmDelete(false),[active?.issue?.issueId]);
  async function checkSavedResult() {
    if(!lastRequest||busy.current)return; busy.current=true;setPending(true);
    try {
      const response=await fetch(`/api/desktop/fleet?receipt=${encodeURIComponent(lastRequest)}`,{cache:'no-store',credentials:'same-origin',signal:AbortSignal.timeout(30_000)});
      const body=await response.json();
      if(!response.ok||!body.receipt)throw new Error('No saved result could be confirmed. Review the record before trying again.');
      if(body.receipt.status==='verified'){await refresh();setError('Saved result verified and current record retrieved.');}
      else setError(`Saved result: ${body.receipt.status}. Review the recorded state before another change.`);
    }catch(failure){setError(failure instanceof Error?failure.message:'Saved result unavailable.');}
    finally{busy.current=false;setPending(false);}
  }
  async function save(action:string,expectedVersion:string,values:Record<string,unknown>){if(!active||busy.current)return;busy.current=true;setPending(true);onBusyChange?.(true);setError('');const requestId=crypto.randomUUID();setLastRequest(requestId);try{const response=await fetch('/api/desktop/fleet',{method:'POST',signal:AbortSignal.timeout(30_000),credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,truck:active.truck.id,action,expectedVersion,values,requestId})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Save failed.');await refresh();setError(body.receipt.status==='verified'?(action==='issue_delete'?'Repair deleted and removal verified.':'Saved and read back from OpsCenter.'):'Verification pending. Review the saved state before another change.');}catch(failure){setError(`${failure instanceof Error?failure.message:'Result could not be confirmed.'} Check Saved Result before trying again.`);}finally{busy.current=false;setPending(false);onBusyChange?.(false);}}
  if(!snapshot)return <section className="fleet-workspace"><WorkspaceFreshness state={freshness}/><div className="job-record-empty-row" role="status">{error||freshness.error||'Loading authoritative Fleet records…'}</div></section>;
  const trucks=snapshot.trucks.map(row=>{const gpsFreshness=displayedGpsFreshness(row.gpsAt,selectedDate,freshness.now,row);return {...row,gpsFreshness,operatingStatus:['GPS Stale','Offline','GPS unavailable'].includes(gpsFreshness)?gpsFreshness:row.operatingStatus};});
  const activeChecklist=active?.truck.checklists[(draft.cadence||'daily') as 'daily'|'weekly'|'monthly'];
  const field=(key:string,label:string,type='text')=><label key={key}><span>{label}</span><Input type={type} value={draft[key]||''} onChange={event=>setDraft({...draft,[key]:event.target.value})}/></label>;
  return <section className={`fleet-workspace live-fleet convoy-workspace fleet-view-${view}`}>
    <WorkspaceFreshness state={freshness} sourceAt={snapshot.sourceUpdatedAt} budgetMinutes={3}/>
    {error&&<p className="drawer-action-feedback" role="status">{error}</p>}
    {lastRequest&&<Button variant="outline" size="sm" disabled={pending} onClick={()=>void checkSavedResult()}>Check Saved Result</Button>}
    {!snapshot.sourceAvailable&&<p className="convoy-source-alert">GPS source unavailable. Stored inspection and repair records remain visible.</p>}
    {snapshot.warnings.filter(warning=>warning.startsWith('Repair source')).map(warning=><p className="convoy-source-alert" key={warning}>{warning}</p>)}
    {view==='overview'&&<TruckAgents date={selectedDate} truck={serviceTruck||undefined}/>}
    <ConvoyViews snapshot={snapshot} trucks={trucks} view={view} truckId={serviceTruck} onTruck={setServiceTruck} open={open}/>
    {convoyWarnings(snapshot.warnings,view,serviceTruck).length>0&&<details className="convoy-source-details"><summary>Source details · {convoyWarnings(snapshot.warnings,view,serviceTruck).length} notes</summary>{convoyWarnings(snapshot.warnings,view,serviceTruck).map(warning=><p key={warning}>{truckDisplayText(warning)}</p>)}</details>}
    {!trucks.length&&<div className="job-record-empty-row">No source fleet records are available.</div>}
    {active&&<div><button className="record-drawer-backdrop" aria-label="Close record" disabled={pending} onClick={()=>{setActive(null);opener.current?.focus();}}/><aside className="record-drawer truck-record-drawer" role="dialog" aria-modal="true" aria-label={`${active.truck.label} ${active.kind}`} ref={drawer} tabIndex={-1}><header className="record-drawer-header"><div><span>Convoy · {date}</span><h2>{truckDisplayText(active.issue?.title||active.truck.label)}</h2></div><Button variant="ghost" size="icon" aria-label="Close Fleet record" disabled={pending} onClick={()=>{setActive(null);opener.current?.focus();}}><X/></Button></header><div className="record-drawer-body"><section className="fleet-drawer-overview">{[['Readiness',active.truck.readiness],['Assignment',active.truck.assignment],['GPS coordinates',recordedValue(active.truck.location,'Unavailable')],['GPS observation',active.truck.gpsAt||'Unavailable'],['Vehicle',recordedValue(active.truck.vehicle)],['Inspection',active.truck.checklist]].map(([label,value])=><div key={label}><span>{truckDisplayText(label)}</span><strong>{truckDisplayText(value)}</strong></div>)}</section>
      {active.truck.inspectionHref&&<a href={active.truck.inspectionHref}>View submitted Five Point Inspection</a>}
      {active.kind==='truck'&&<>
        <TruckAgents date={selectedDate} truck={active.truck.id}/>
        <div className="truck-record-actions">
          <Button variant="outline" size="sm" onClick={()=>open({...active,kind:'load'})}>Record current load</Button>
          <Button variant="outline" size="sm" onClick={()=>open({...active,kind:'checklist'})}>View checklist</Button>
          <Button variant="outline" size="sm" onClick={()=>open({...active,kind:'maintenance',initialStatus:'scheduled'})}>Schedule service</Button>
          <Button variant="outline" size="sm" onClick={()=>open({...active,kind:'maintenance',initialStatus:'completed'})}>Record completed service</Button>
          <Button variant="outline" size="sm" onClick={()=>open({...active,kind:'issue'})}>Add repair</Button>
        </div>
        <section className="convoy-drawer-load"><h3>Load · {truckDisplayText(truckLoadLabel(active.truck))}</h3><details><summary>Load evidence</summary><p>{truckDisplayText(active.truck.loadNote)}</p></details></section>
        <ConvoyHistory snapshot={snapshot} truck={active.truck} open={open}/>
      </>}
      {active.kind==='history'&&<ConvoyHistory snapshot={snapshot} truck={active.truck} open={open}/>}
      {active.kind==='load'&&<section className="fleet-drawer-controls"><div className="drawer-control-heading"><span>Current load</span><strong>{truckDisplayText(truckLoadLabel(active.truck))}</strong><small>Record the load you can observe now, with a contents note.</small></div>
        <div className="fleet-load-form">{field('percent','Load percent','number')}{field('contents','Contents / observation note')}</div>
        <Button disabled={pending||!snapshot.canWrite||draft.percent===''||!Number.isFinite(Number(draft.percent))||Number(draft.percent)<0||Number(draft.percent)>200||!draft.contents?.trim()} onClick={()=>void save('load_snapshot',active.truck.loadVersion,{loadFraction:Number(draft.percent)/100,contents:draft.contents})}>Save current load observation</Button>
        <details className="convoy-extra-fields"><summary>Starting load or verified unload</summary><p>Starting load sets the day’s baseline. Use a verified yard reset only after an actual unload.</p>
          <label><span>Verified unload location</span><select value={draft.location||'dump'} onChange={event=>setDraft({...draft,location:event.target.value})}><option value="dump">Dump</option><option value="metal_yard">Metal yard</option></select></label>
          <div className="fleet-load-actions"><Button variant="outline" disabled={pending||!snapshot.canWrite} onClick={()=>void save('load_reset',active.truck.loadVersion,{location:draft.location||'dump'})}>Record verified yard reset</Button><Button variant="outline" disabled={pending||!snapshot.canWrite||draft.percent===''||Number(draft.percent)<0||Number(draft.percent)>100} onClick={()=>void save('load_start',active.truck.loadVersion,{loadFraction:Number(draft.percent)/100})}>Save starting load</Button></div>
        </details><details className="convoy-extra-fields"><summary>Load evidence</summary><p>{truckDisplayText(active.truck.loadNote)}</p></details>
      </section>}
      {active.kind==='issue'&&<section className="fleet-drawer-controls"><div className="drawer-control-heading"><span>Repair controls</span><strong>{active.issue?'Update repair':'Add repair'}</strong><small>A resolution note is required before a repair can be closed.</small></div><div className="fleet-form-grid">{field('title','Issue title')}<label><span>Severity</span><select value={draft.severity||'monitor'} onChange={event=>setDraft({...draft,severity:event.target.value})}>{['monitor','repair_soon','out_of_service'].map(value=><option value={value} key={value}>{value.replaceAll('_',' ')}</option>)}</select></label><label><span>Status</span><select value={draft.status||'open'} onChange={event=>setDraft({...draft,status:event.target.value})}>{['open','in_progress','resolved'].map(value=><option value={value} key={value}>{value.replaceAll('_',' ')}</option>)}</select></label>{field('cost','Repair cost','number')}{field('downtimeHours','Downtime hours','number')}<label className="wide"><span>Description</span><Textarea value={draft.description||''} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><label className="wide"><span>Resolution</span><Textarea value={draft.resolution||''} onChange={event=>setDraft({...draft,resolution:event.target.value})}/></label></div><details className="convoy-extra-fields"><summary>Additional repair details</summary><div className="fleet-form-grid">{field('owner','Shop / contact')}{field('dueDate','Planned date','date')}</div></details><Button disabled={pending||!snapshot.canWrite||!draft.title?.trim()||draft.status==='resolved'&&!draft.resolution?.trim()} onClick={()=>void save('issue',active.issue?.version||nullVersion,{...draft,issueId:active.issue?.issueId})}>Save repair</Button>{active.issue&&<div className="convoy-delete-repair">{confirmDelete?<div role="group" aria-label="Confirm repair deletion"><p>Delete “{active.issue.title}” for {truckDisplayText(active.truck.label)}? This removes it from repairs, history and repair totals. Original inspection reports stay unchanged.</p><div className="convoy-actions"><Button variant="outline" disabled={pending} onClick={()=>setConfirmDelete(false)}>Keep repair</Button><Button variant="destructive" disabled={pending||!snapshot.canWrite} onClick={()=>void save('issue_delete',active.issue!.version,{issueId:active.issue!.issueId})}>{pending?'Deleting…':'Confirm delete repair'}</Button></div></div>:<Button variant="destructive" disabled={pending||!snapshot.canWrite} onClick={()=>setConfirmDelete(true)}>Delete repair</Button>}</div>}</section>}
      {active.kind==='maintenance'&&<section className="fleet-drawer-controls"><div className="drawer-control-heading"><span>Maintenance record</span><strong>{draft.status==='scheduled'?'Schedule service':'Record completed service'}</strong></div><div className="fleet-form-grid">{field('serviceType','Service type')}{field('serviceDate','Service date','date')}<label><span>Status</span><select value={draft.status||'scheduled'} onChange={event=>setDraft({...draft,status:event.target.value})}><option value="scheduled">Scheduled</option><option value="completed">Completed</option></select></label>{field('description','Description')}{field('odometer','Odometer','number')}{field('cost','Cost','number')}{field('vendor','Vendor')}{field('nextServiceDate','Next service date','date')}{field('nextServiceOdometer','Next service odometer','number')}{field('notes','Notes')}</div><Button disabled={pending||!snapshot.canWrite||!draft.serviceType?.trim()||!draft.serviceDate} onClick={()=>void save('maintenance',active.record?.version||nullVersion,{...draft,recordId:active.record?.recordId})}>Save maintenance record</Button></section>}
      {active.kind==='checklist'&&<section className="fleet-drawer-controls"><div className="drawer-control-heading"><span>Truck inspection</span><strong>Review every required item</strong><small>Attention findings become repair work items.</small></div><div className="fleet-form-grid"><label><span>Frequency</span><select value={draft.cadence||'daily'} onChange={event=>{const cadence=event.target.value as 'daily'|'weekly'|'monthly';setDraft({...draft,cadence,inspector:active.truck.checklists[cadence].inspector});setAnswers(Object.fromEntries(active.truck.checklists[cadence].answers.map(answer=>[answer.itemId,{status:answer.status,notes:answer.notes}])));}}>{['daily','weekly','monthly'].map(value=><option key={value}>{value}</option>)}</select></label>{field('inspector','Inspector')}{field('odometer','Odometer','number')}{(activeChecklist?.definitions||[]).map(item=><label className="wide" key={item.itemId}><span>{item.label}</span><small>{item.guidance}</small><select value={answers[item.itemId]?.status||''} onChange={event=>setAnswers({...answers,[item.itemId]:{status:event.target.value,notes:answers[item.itemId]?.notes||''}})}><option value="">Choose inspection result</option><option value="pass">Pass</option><option value="attention">Needs attention</option><option value="na">Not applicable</option></select><Input aria-label={`${item.label} notes`} placeholder="Observation or defect notes" value={answers[item.itemId]?.notes||''} onChange={event=>setAnswers({...answers,[item.itemId]:{status:answers[item.itemId]?.status||'',notes:event.target.value}})}/></label>)}</div><Button disabled={pending||!snapshot.canWrite||!draft.inspector?.trim()||!(activeChecklist?.definitions||[]).every(item=>answers[item.itemId]?.status)} onClick={()=>void save('checklist',activeChecklist?.version||'',{cadence:draft.cadence||'daily',inspector:draft.inspector,odometer:draft.odometer,answers:(activeChecklist?.definitions||[]).map(item=>({itemId:item.itemId,...answers[item.itemId]}))})}>Save completed inspection</Button></section>}
      {error&&<p className="drawer-action-feedback" role="status">{error}</p>}{lastRequest&&<Button variant="outline" size="sm" disabled={pending} onClick={()=>void checkSavedResult()}>Check Saved Result</Button>}</div></aside></div>}
  </section>;
}
