import { truckDisplayText } from '../lib/junkware-trucks';
import { CapitalPayments } from './capital-payments';
import { CapitalResale } from './capital-resale';
import { CapitalPageHeader, CapitalStat } from './capital-ui';
import './capital-workspace.css';
import { CapitalOverview } from './capital-overview';
import { FuelReconciliation } from './fuel-reconciliation';
import type { FuelReconciliation as FuelReconciliationData } from './lib/fuel-reconciliation-contract';
import { combineFinanceEvidence, financeReading, presentDailyFinance, type DailyFinanceEvidence } from '../lib/daily-finance-freshness';
import { DumpExpenses } from './dump-expenses';
import type { DumpExpenseSummary } from './lib/dump-expense-contract';
import { RecyclingReceiptReview } from './recycling-receipt-review';
import { RecyclingMonthly } from './recycling-monthly';
import './resale-photos.css';
import { paymentVerification, verifiedPayments } from './lib/payment-verification';
import { MerchantPaymentEvidence, merchantLink } from './merchant-evidence';
import { workspaceReady } from './navigation-performance';
import { useWorkspaceSnapshot } from './use-workspace-snapshot';
import { fetchWorkspace } from './lib/workspace-cache';
import { FinancialStatements } from "./financial-statements";
import FinanceTrends from './finance-trends';
import { useWorkspaceRefresh, WorkspaceFreshness } from './workspace-freshness';
import { useCallback, useEffect, useState } from 'react';
import { ShieldCheck, X, ReceiptText, Users, Truck, Fuel } from 'lucide-react';
import { Button } from './components/ui/button';
import { Badge } from './components/ui/badge';
import { commercialMoney as money, commercialDate, type FinanceData, type FinanceView, type ResaleRecord, type RecyclingRecord, type CommercialOperation, type CommercialReceipt } from './lib/commercial-contract';
/** Navigation is owned by the prototype root. report receives action status messages. */
export type LiveFinanceProps = { date: string; view?: string; report?: (message: string) => void; onBusyChange?: (busy: boolean) => void; onViewChange?: (view: FinanceView) => void };
type FinanceWithWex = FinanceData & { fuelReconciliation?: FuelReconciliationData; dailyFreshness?: DailyFinanceEvidence; dailyBreakdown?: { revenue: number | null; labor: number | null; dumps: number | null; fuel: number | null; totalCosts: number | null; net: number | null; fuelSource: 'published' | 'wex' | 'unavailable'; wexIncludedSeparately: boolean }; dumpExpenses?: DumpExpenseSummary; wexFuel: { available: boolean; status: 'available' | 'missing' | 'invalid'; importedAt: string | null; sourceFileModifiedAt: string | null; coverageFrom: string | null; coverageThrough: string | null; transactionCount: number; selectedDate: { count: number; gallons: number; netCost: number }; month: { count: number; gallons: number; netCost: number }; transactions: Array<{ transactionId: string; transactionDate: string; transactionTime: string; postedDate: string; truck: string; driver: string; driverPromptId: string; cardLastFive: string; units: number | null; unitOfMeasure: string; gallons: number | null; unitCost: number | null; totalFuelCost: number | null; totalNonFuelCost: number | null; netCost: number; product: string; productDescription: string; merchant: string; city: string; state: string; postalCode: string; odometer: number | null; ticketNumber: string; status: 'posted' }> } };
const emptyVersion = '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945';
const emptyWex: FinanceWithWex['wexFuel'] = { available: false, status: 'missing', importedAt: null, sourceFileModifiedAt: null, coverageFrom: null, coverageThrough: null, transactionCount: 0, selectedDate: { count: 0, gallons: 0, netCost: 0 }, month: { count: 0, gallons: 0, netCost: 0 }, transactions: [] };
export function LiveFinance({ date, view, report, onViewChange, onBusyChange }: LiveFinanceProps) {
  const [receiptReviewOpen, setReceiptReviewOpen] = useState(false);
  const snapshotKey = `/api/desktop/finance?date=${date}`;
  const [data, setData] = useWorkspaceSnapshot<FinanceWithWex>(snapshotKey);
  const [error, setError] = useState(''), [revision, setRevision] = useState(0), [localView, setLocalView] = useState<FinanceView>('overview');
  const financeView = (view && ['overview', 'payments', 'resale', 'recycling', 'trends', 'accounting', 'expenses'].includes(view) ? view : localView) as FinanceView;
  const setFinanceView = (next: FinanceView) => { setLocalView(next); onViewChange?.(next); };
  const [feedback, setFeedback] = useState(''), [busy, setBusy] = useState(false), [resale, setResale] = useState<ResaleRecord | null>(null), [recycling, setRecycling] = useState<RecyclingRecord | null>(null), [payment, setPayment] = useState<FinanceData['reconciliation']['paymentsByJob'][number] | null>(null);
  useEffect(() => { setError(''); setResale(null); setRecycling(null); setPayment(null); }, [date]);
  const loadSnapshot = useCallback(async (signal: AbortSignal) => {
    const payload = await fetchWorkspace<FinanceWithWex>(snapshotKey, signal);
    if (!signal.aborted) setData(payload);
  }, [snapshotKey, setData]);
  useEffect(() => { if (data) workspaceReady('Finance'); }, [data]);
  const freshness = useWorkspaceRefresh(loadSnapshot,`${date}:${revision}`,busy || receiptReviewOpen || Boolean(resale || recycling || payment),30_000,snapshotKey);

  useEffect(() => { const escape = (event: KeyboardEvent) => { if (event.key === 'Escape' && !busy) { setResale(null); setRecycling(null); setPayment(null); } }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape); }, [busy]);
  useEffect(() => { if (!(resale || recycling || payment)) return; const prior = document.activeElement as HTMLElement | null; document.querySelector<HTMLElement>('[aria-labelledby="finance-record-title"] button')?.focus(); return () => { if (prior?.isConnected) prior.focus({ preventScroll: true }); }; }, [resale?.itemId, recycling?.id, payment?.jkNumber]);
  useEffect(() => { if (feedback) report?.(feedback); }, [feedback, report]);
  useEffect(() => { onBusyChange?.(busy || receiptReviewOpen || Boolean(resale || recycling || payment)); return () => onBusyChange?.(false); }, [busy, receiptReviewOpen, Boolean(resale || recycling || payment), onBusyChange]);
  const [lastRequest, setLastRequest] = useState('');
  async function checkReceipt() {
    if (!lastRequest || busy) return; setBusy(true); onBusyChange?.(true);
    try { const response = await fetch(`/api/desktop/finance?date=${date}&receipt=${lastRequest}`, { cache: 'no-store', signal: AbortSignal.timeout(30_000) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setFeedback(result.receipt.message); if (result.receipt.status === 'verified') {setResale(null);setRecycling(null);setPayment(null);setRevision(value => value + 1);} }
    catch (error) { setFeedback(error instanceof Error ? error.message : 'Saved receipt unavailable.'); } finally { setBusy(false); onBusyChange?.(false); }
  }
  async function mutate(operation: Omit<CommercialOperation, 'date' | 'requestId'>) {
    setBusy(true); onBusyChange?.(true); const requestId = crypto.randomUUID(); setLastRequest(requestId);
    try { const response = await fetch('/api/desktop/finance', { method: 'POST', signal: AbortSignal.timeout(30_000), headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...operation, date, requestId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); const receipt: CommercialReceipt = result.receipt; setFeedback(receipt.message); if (receipt.status === 'verified') { setResale(null); setRecycling(null); setRevision(value => value + 1); } return receipt.status === 'verified'; }
    catch (error) { setFeedback(`${error instanceof Error ? error.message : 'Result unavailable.'} Check saved receipt ${requestId} before retrying.`); return false; } finally { setBusy(false); onBusyChange?.(false); }
  }
  if (!data) return <section className="finance-workspace"><WorkspaceFreshness state={freshness}/><div className="marketing-empty" role="status">{error || freshness.error || 'Loading Finance sources…'}</div></section>;
  const recon = data.reconciliation;
  const verification = verifiedPayments(recon);
  const wex = data.wexFuel || emptyWex;
  const dailyBreakdown = data.dailyBreakdown || { revenue: data.daily.revenue, labor: null, dumps: null, fuel: wex.available && wex.selectedDate.count ? wex.selectedDate.netCost : null, totalCosts: data.daily.costs, net: data.daily.profit, fuelSource: wex.available && wex.selectedDate.count ? 'wex' as const : 'unavailable' as const, wexIncludedSeparately: false };
  const dailyDisplay = presentDailyFinance(dailyBreakdown, data.dailyFreshness, date, freshness.now);
  const expenseReading = financeReading(dailyBreakdown.dumps == null || dailyBreakdown.fuel == null ? null : dailyBreakdown.dumps + dailyBreakdown.fuel,
    data.dailyFreshness ? combineFinanceEvidence(data.dailyFreshness.dumps, data.dailyFreshness.fuel) : undefined, date, freshness.now);
  const displayAmount = (reading: typeof dailyDisplay.revenue) => reading.state === 'current' ? money(reading.value) : reading.state === 'stale' ? 'Stale' : 'Unavailable';
  const close = () => { if (!busy) { setResale(null); setRecycling(null); setPayment(null); } };
  const jobLink = (jk: string) => jk ? <a className="finance-job-link" href={`/schedule?date=${date}&job=${encodeURIComponent(jk)}`}>{jk}</a> : <span>Unspecified</span>;
  const newResale = () => setResale({ itemId: crypto.randomUUID(), version: emptyVersion, itemName: '', acquiredDate: date, source: '', cost: NaN, askingPrice: NaN, soldPrice: NaN, status: 'to_list', marketplace: '', notes: '', createdAt: '', updatedAt: '' });
  const newRecycling = (runDate: string) => setRecycling({ id: crypto.randomUUID(), version: data.recyclingVersion, date: runDate, paymentDate: '', material: 'Scrap metal', sourceJob: '', yard: '', quantity: '', expectedValue: null, realizedValue: null, ticket: '', paymentReference: '', status: 'Awaiting yard', owner: '', note: '', updatedAt: '' });
  const dailySummary = (<section className="metric-strip finance-capital-metrics" aria-label="Selected day financial breakdown">
      <button type="button" className="kpi-card" onClick={() => setFinanceView('payments')}><span>Revenue</span><strong>{displayAmount(dailyDisplay.revenue)}</strong><small>{dailyDisplay.revenue.detail}</small></button>
      <button type="button" className="kpi-card" onClick={() => setFinanceView('trends')}><span>Labor</span><strong>{displayAmount(dailyDisplay.labor)}</strong><small>{dailyDisplay.labor.detail}</small></button>
      <button type="button" className="kpi-card" onClick={() => setFinanceView('expenses')}><span>Dump + Fuel</span><strong>{displayAmount(expenseReading)}</strong><small>{expenseReading.state === 'current' ? `Dumps ${money(dailyDisplay.dumps.value)} · Fuel ${money(dailyDisplay.fuel.value)} · ${expenseReading.detail}` : expenseReading.detail}</small></button>
      <button type="button" className={`kpi-card ${dailyDisplay.net.state !== 'current' ? 'warning' : dailyDisplay.net.value! < 0 ? 'critical' : 'healthy'}`} onClick={() => setFinanceView('trends')}><span>Net</span><strong>{displayAmount(dailyDisplay.net)}</strong><small>{dailyDisplay.net.detail}</small></button>
    </section>);
  return <section className={`finance-workspace capital-workspace finance-view-${financeView}`}>
    <WorkspaceFreshness state={freshness} sourceAt={data.generatedAt} sourceLabel="Metrics published" statusLabel="Source age shown on each financial card"/>
    {financeView === 'overview' && <p className="finance-payment-note" role="status"><ShieldCheck size={14} />{data.available ? `Published daily metrics · ${date}` : `Daily metrics unavailable for ${date}`} · Payment verification {verification.status} · {commercialDate(recon.generatedAt || '')}</p>}
    {feedback && <p className="finance-feedback" role="status">{feedback}</p>}{lastRequest && <Button disabled={busy} variant="outline" size="sm" onClick={() => { void checkReceipt(); }}>Check Saved Result</Button>}
    {financeView === 'overview' && <CapitalOverview data={data} date={date} dailySummary={dailySummary} onViewChange={setFinanceView} />}
    {financeView === 'accounting' && <FinancialStatements data={data.statements} date={date} onRefresh={() => setRevision(value => value + 1)} />}
    {financeView === 'expenses' && <div className="capital-page capital-expenses">
      <CapitalPageHeader eyebrow={`OPERATING EXPENSES · ${commercialDate(date)}`} title="Know the cost of the day" description="Published operating costs, disposal visits and fuel purchases with their source evidence." />
      <section className="capital-stat-grid" aria-label="Selected day operating expenses">
        <CapitalStat primary icon={ReceiptText} label="Published costs" value={displayAmount(dailyDisplay.totalCosts)} detail={dailyDisplay.totalCosts.detail}/>
        <CapitalStat icon={Users} label="Labor" value={displayAmount(dailyDisplay.labor)} detail={dailyDisplay.labor.detail}/>
        <CapitalStat icon={Truck} label="Published disposal" value={displayAmount(dailyDisplay.dumps)} detail={dailyDisplay.dumps.detail}/>
        <CapitalStat icon={Fuel} label="Published fuel" value={displayAmount(dailyDisplay.fuel)} detail={dailyDisplay.fuel.detail}/>
      </section>
      <nav className="capital-section-links" aria-label="Expense sections"><a href="#capital-disposal">Disposal records</a><a href="#fuel-reconciliation">Fuel matching</a><a href="#capital-fuel-purchases">Fuel card purchases</a></nav>
      <div className="capital-expense-grid">
      <DumpExpenses data={data.dumpExpenses} />
      <FuelReconciliation data={data.fuelReconciliation} />
      </div>
      <section className="finance-wex-shell" id="capital-fuel-purchases"><div className="section-title"><div><span className="section-kicker">WEX Fleet Fuel · posted transactions only</span><h2>Fuel Card Purchases</h2><p>{wex.available ? `Portal export imported ${commercialDate(wex.importedAt || '')} · source coverage through ${commercialDate(wex.coverageThrough || '')}` : wex.status === 'invalid' ? 'The saved WEX snapshot needs recovery.' : 'No WEX portal export has been imported.'}</p></div><Badge variant="outline">{wex.available ? `${wex.transactionCount} posted` : 'Sign-in / export required'}</Badge></div>
        <div className="finance-wex-summary"><article><span>Selected day</span><strong>{wex.available ? money(wex.selectedDate.netCost) : 'Unavailable'}</strong><small>{wex.selectedDate.count} posted purchases · {wex.selectedDate.gallons.toFixed(2)} gal</small></article><article><span>Month to source date</span><strong>{wex.available ? money(wex.month.netCost) : 'Unavailable'}</strong><small>{wex.month.count} posted purchases · {wex.month.gallons.toFixed(2)} gal</small></article><article><span>Source coverage</span><strong>{wex.coverageThrough ? commercialDate(wex.coverageThrough) : 'Unavailable'}</strong><small>WEXOnline CSV · portal session retained in Chrome</small></article></div>
        {!!wex.transactions.length && <><div className="finance-wex-head"><span>Time</span><span>Truck / driver</span><span>Fuel</span><span>Merchant</span><span>Odometer</span><span>Net cost</span></div><div className="finance-wex-list">{wex.transactions.map(transaction => <article key={transaction.transactionId}><span>{transaction.transactionTime}</span><div><strong>{truckDisplayText(transaction.truck)}</strong><small>{transaction.driver}</small></div><div><strong>{transaction.gallons == null ? `${transaction.units ?? '—'} ${transaction.unitOfMeasure}` : `${transaction.gallons.toFixed(2)} gal`}</strong><small>{transaction.productDescription || transaction.product}</small></div><div><strong>{transaction.merchant}</strong><small>{[transaction.city, transaction.state].filter(Boolean).join(', ')}</small></div><span>{transaction.odometer?.toLocaleString() || '—'}</span><strong>{money(transaction.netCost)}</strong></article>)}</div></>}
        <footer className="finance-payment-note"><ShieldCheck size={14}/><span>{dailyBreakdown.wexIncludedSeparately ? 'Selected-day WEX net cost fills the missing published fuel expense once.' : 'Published daily fuel is used when present; WEX detail is shown without adding the same fuel expense again.'} Transaction IDs prevent duplicate WEX imports, and pending authorizations are excluded.</span></footer>
      </section>
    </div>}
    {financeView === 'payments' && <CapitalPayments key={date} data={data} date={date} onReview={setPayment} />}
    {financeView === 'resale' && <CapitalResale data={data} onAdd={newResale} onReview={setResale} />}
    {financeView === 'recycling' && <RecyclingMonthly key={date.slice(0, 7)} records={data.recycling} date={date} onAdd={newRecycling} onReview={setRecycling} receiptInbox={<RecyclingReceiptReview records={data.recycling} drafts={data.recyclingReceipts || []} busy={busy} onBusyChange={setReceiptReviewOpen} onSave={mutate} />} />}
    {financeView === 'trends' && <FinanceTrends data={data} />}
    {financeView !== 'overview' && financeView !== 'expenses' && <details className="capital-day-context"><summary>Selected day · {commercialDate(date)} · operational snapshot</summary>{dailySummary}</details>}
    {(resale || recycling || payment) && <><button className="record-drawer-backdrop" aria-label="Close finance record" disabled={busy} onClick={close} /><aside className="record-drawer" role="dialog" aria-modal="true" aria-labelledby="finance-record-title" onKeyDown={event => { if (event.key !== 'Tab') return; const controls = [...event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), textarea:not(:disabled), select:not(:disabled), a[href]')]; const first = controls[0], last = controls.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }}><header className="record-drawer-header"><div><span className="section-kicker">Finance · {resale ? 'Resale custody' : recycling ? 'Recycling evidence' : 'Payment sources'}</span><h2 id="finance-record-title">{resale?.itemName || recycling?.material || payment?.jkNumber || 'New Record'}</h2></div><button disabled={busy} onClick={close} aria-label="Close"><X /></button></header>
      {payment && <><div className="record-drawer-body"><p>{payment.customer} · {paymentVerification(payment, verification.qboUsable)}</p><dl className="record-facts"><div><dt>Job total</dt><dd>{money(payment.revenueAmount)}</dd></div><div><dt>Recorded payment</dt><dd>{money(payment.paidAmount)}</dd></div><div><dt>Recorded tip</dt><dd>{money(payment.tipAmount)}</dd></div><div><dt>Payment method</dt><dd>{payment.paymentMethod}</dd></div>{payment.tender === 'check' && <div><dt>Check number</dt><dd>{payment.checkNumber || 'Unavailable'}</dd></div>}<div><dt>QBO transaction</dt><dd>{payment.qboTransactionId || (payment.tender === 'cash' || payment.tender === 'check' ? 'Not a card payment' : 'Unavailable')}</dd></div><div><dt>QBO status</dt><dd>{payment.qboStatus || (payment.tender === 'cash' || payment.tender === 'check' ? 'Recorded in JunkWare; deposit not verified' : 'Unavailable')}</dd></div>{payment.tender !== 'cash' && payment.tender !== 'check' && <><div><dt>Merchant Center processing</dt><dd><MerchantPaymentEvidence evidence={payment.processor} /></dd></div>{payment.processor?.transaction && <><div><dt>Merchant transaction</dt><dd><a href={merchantLink(payment.processor.transaction.transactionId)}>{payment.processor.transaction.transactionId}</a></dd></div><div><dt>Merchant amount</dt><dd>{money(payment.processor.transaction.amount)}</dd></div><div><dt>Merchant fee</dt><dd>{money(payment.processor.transaction.fee)}</dd></div><div><dt>Merchant observed</dt><dd>{new Date(payment.processor.transaction.observedAt).toLocaleString()}</dd></div></>}</>}</dl><p>A matched Merchant Center approval verifies a payment. QBO posting is tracked separately.</p><p>Matching is owned by the reconciliation collector. No adjustment is posted from this drawer. Correct the source record, then refresh after collection.</p></div><footer className="record-drawer-actions">{jobLink(payment.jkNumber)}<a href="https://qbo.intuit.com/">Open QuickBooks</a><Button variant="outline" onClick={() => { setPayment(null); setRevision(value => value + 1); }}>Refresh Source Snapshot</Button></footer></>}
      {resale && <form onSubmit={event => { event.preventDefault(); void mutate({ action: 'resale.save', recordId: resale.itemId, expectedVersion: resale.version, values: { ...resale } }); }}><div className="record-drawer-body appointment-create-grid"><p>{resale.itemNumber || "Item number assigned when saved"}</p>{Boolean(resale.photos?.length) && <div className="resale-photo-gallery">{resale.photos?.map((photo, index) => <a key={photo.photoId} href={`/api/resale-items/photos/${photo.photoId}`} target="_blank" rel="noreferrer" aria-label={`Open photo ${index + 1} of ${resale.itemName}`}><img src={`/api/resale-items/photos/${photo.photoId}`} alt={`${resale.itemName}, photo ${index + 1}`} loading="lazy" /></a>)}</div>}<label>Item name<input required maxLength={500} value={resale.itemName} onChange={event => setResale({ ...resale, itemName: event.target.value })} /></label><label>Source job / custody reference<input required maxLength={500} value={resale.source} onChange={event => setResale({ ...resale, source: event.target.value })} /></label><label>Acquired date<input required type="date" value={resale.acquiredDate} onChange={event => setResale({ ...resale, acquiredDate: event.target.value })} /></label>{(['cost', 'askingPrice', 'soldPrice'] as const).map(field => <label key={field}>{field === 'cost' ? 'Recorded cost' : field === 'askingPrice' ? 'Asking price' : 'Sale amount (enter 0 if unsold)'}<input required type="number" min="0" step="0.01" value={Number.isFinite(resale[field]) ? resale[field] : ''} onChange={event => setResale({ ...resale, [field]: event.target.value === '' ? NaN : Number(event.target.value) })} /></label>)}<label>Disposition<select value={resale.status} onChange={event => setResale({ ...resale, status: event.target.value as ResaleRecord['status'] })}><option value="to_list">To list</option><option value="listed">Listed</option><option value="sold">Sold (receipt recorded)</option></select></label><label>Listing location / marketplace<input required={resale.status === 'listed'} maxLength={500} value={resale.marketplace} onChange={event => setResale({ ...resale, marketplace: event.target.value })} /></label><label>Custody and sale evidence<textarea required={resale.status === 'sold'} maxLength={2000} value={resale.notes} onChange={event => setResale({ ...resale, notes: event.target.value })} /></label><p>Saving records OpsCenter inventory evidence; it does not post to accounting.</p></div><footer className="record-drawer-actions"><Button type="submit" disabled={busy}>{busy ? 'Verifying…' : 'Save Inventory Record'}</Button></footer></form>}
      {recycling && <form onSubmit={event => { event.preventDefault(); void mutate({ action: 'recycling.save', recordId: recycling.id, expectedVersion: recycling.version, values: { ...recycling, runDate: recycling.date } }); }}><div className="record-drawer-body appointment-create-grid"><label>Run / ticket date<input required type="date" value={recycling.date} onChange={event => setRecycling({ ...recycling, date: event.target.value })} /></label><label>Payment received date<input type="date" required={recycling.status === 'Paid'} value={recycling.paymentDate || ''} onChange={event => setRecycling({ ...recycling, paymentDate: event.target.value })} /></label>{(['material', 'sourceJob', 'yard', 'quantity', 'owner', 'ticket', 'paymentReference'] as const).map(field => <label key={field}>{{ material: 'Material', sourceJob: 'Source job / custody reference', yard: 'Yard', quantity: 'Quantity and unit', owner: 'Owner', ticket: 'Yard ticket reference', paymentReference: 'Payment receipt reference' }[field]}<input required={['material', 'sourceJob', 'quantity', 'owner'].includes(field) || recycling.status !== 'Awaiting yard' && ['yard', 'ticket'].includes(field) || recycling.status === 'Paid' && field === 'paymentReference'} maxLength={500} value={recycling[field]} onChange={event => setRecycling({ ...recycling, [field]: event.target.value })} /></label>)}{(['expectedValue', 'realizedValue'] as const).map(field => <label key={field}>{field === 'expectedValue' ? 'Expected payout (optional)' : 'Income received'}<input type="number" min="0" step="0.01" required={field === 'realizedValue' && recycling.status === 'Paid'} value={recycling[field] ?? ''} onChange={event => setRecycling({ ...recycling, [field]: event.target.value === '' ? null : Number(event.target.value) })} /></label>)}<label>Status<select value={recycling.status} onChange={event => setRecycling({ ...recycling, status: event.target.value as RecyclingRecord['status'] })}><option>Awaiting yard</option><option>Submitted</option><option value="Paid">Paid (operator-recorded)</option></select></label><label>Evidence notes<textarea maxLength={2000} value={recycling.note} onChange={event => setRecycling({ ...recycling, note: event.target.value })} /></label><p>This saves user-entered ticket and payment evidence. It does not verify receipt with the yard or match a QBO payment.</p></div><footer className="record-drawer-actions"><Button type="submit" disabled={busy}>{busy ? 'Verifying…' : 'Save Recycling Record'}</Button></footer></form>}
    </aside></>}
  </section>;
}
