'use client';
import { useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { operatingPatterns, upcomingDemand, planningBacktest } from '../lib/operating-planning';
import type { OperatingTrendsData } from '../lib/operating-trends';
import { currentOperatingDay } from './lib/operating-day';

const number = (value: number | null) => value == null ? '—' : value.toLocaleString('en-US', { maximumFractionDigits: 1 });
const money = (value: number | null) => value == null ? '—' : value.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const tooltipStyle = { background: 'var(--card)', color: 'var(--foreground)', border: '1px solid var(--border)', borderRadius: 8 };
export function OperatingPlanning({ data, showRevenue = true }: { data: OperatingTrendsData; showRevenue?: boolean }) {
  const [days, setDays] = useState(90);
  const patterns = useMemo(() => operatingPatterns(data, days), [data, days]);
  const upcoming = useMemo(() => upcomingDemand(data, currentOperatingDay()), [data]);
  const backtest = useMemo(() => planningBacktest(data.daily, 'completedJobs'), [data]);
  const strongest = (rows: typeof patterns.weekdays) => [...rows].filter(row => row.samples >= 3).sort((a, b) => (b.jobs ?? 0) - (a.jobs ?? 0)).slice(0, 3);
  const busyWeekdays = strongest(patterns.weekdays), busyMonthDays = strongest(patterns.monthDays);
  const available = upcoming.filter(row => row.jobs != null);
  const peak = [...available].sort((a, b) => b.jobs! - a.jobs!)[0];
  const quiet = [...available].sort((a, b) => a.jobs! - b.jobs!)[0];
  return <section className="operating-planning" aria-label="Demand planning">
    <div className="finance-performance-chart-heading"><div><h3>Busy days & demand planning</h3><p>Completed jobs per operating day · zero-job days excluded.</p></div><label>Pattern history<select aria-label="Pattern history" value={days} onChange={event => setDays(Number(event.target.value))}>{[90, 180, 365].map(value => <option key={value} value={value}>{value} days</option>)}</select></label></div>
    <p>{patterns.start}–{data.historyThrough}. {busyWeekdays.length ? `Busiest weekdays: ${busyWeekdays.map(row => `${row.label} (${number(row.jobs)} jobs/day)`).join(', ')}.` : 'Not enough repeated weekdays to rank.'} {busyMonthDays.length ? `Busiest dates: ${busyMonthDays.map(row => `${row.label} (${number(row.jobs)})`).join(', ')}.` : 'Not enough repeated month dates to rank.'} Rankings require at least 3 operating-day observations.</p>
    <div className="operating-chart-grid">{[{ title: 'Jobs by weekday', rows: patterns.weekdays, dense: false }, { title: 'Jobs by day of month', rows: patterns.monthDays, dense: true }].map(group => <article className="operating-chart" key={group.title}><h4>{group.title}</h4><div className="operating-chart-plot"><ResponsiveContainer width="100%" height="100%"><BarChart data={group.rows} accessibilityLayer margin={{ top: 16, right: 12, bottom: 0, left: 0 }}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="label" ticks={group.dense ? ['1', '5', '10', '15', '20', '25', '31'] : undefined} tickLine={false} axisLine={false} /><YAxis width={42} domain={[0, 'auto']} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltipStyle} labelFormatter={label => group.dense ? `Day ${label} of month` : String(label)} formatter={(value, _name, item) => [`${number(typeof value === 'number' ? value : null)} jobs · ${item.payload.samples} operating days`, 'Average']} /><Bar dataKey="jobs" name="Jobs per operating day" fill="var(--operating-actual)" isAnimationActive={false} /></BarChart></ResponsiveContainer></div><p>{group.dense ? 'Month dates have fewer observations and a different weekday mix; this is descriptive, not a separate forecast driver.' : 'Recent Sunday openings can produce a smaller sample than other weekdays.'}</p><details><summary>See pattern data</summary><div className="operating-data-table"><table><thead><tr><th>{group.dense ? 'Month date' : 'Weekday'}</th><th>Jobs/day</th><th>Operating days</th>{showRevenue && <><th>Revenue/day</th><th>Revenue days</th></>}</tr></thead><tbody>{group.rows.map(row => <tr key={row.label}><td>{row.label}</td><td>{number(row.jobs)}</td><td>{row.samples}{row.samples < 3 ? ' · small sample' : ''}</td>{showRevenue && <><td>{money(row.revenue)}</td><td>{row.revenueSamples}</td></>}</tr>)}</tbody></table></div></details></article>)}</div>
    <article className="operating-chart operating-upcoming"><h4>Next 14 days · expected jobs</h4>{upcoming.length ? <><p>Assumes you remain open every day, including Sundays. These are planning estimates, not booked jobs; holidays, weather and staffing changes are not modeled.</p>{peak && quiet && <p>Expected high: {peak.label} · {number(peak.jobs)} jobs. Expected low: {quiet.label} · {number(quiet.jobs)} jobs.</p>}<div className="operating-chart-plot"><ResponsiveContainer width="100%" height="100%"><BarChart data={upcoming} accessibilityLayer margin={{ top: 12, right: 16, left: 0, bottom: 0 }}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="label" minTickGap={22} tickLine={false} axisLine={false} /><YAxis width={42} domain={[0, 'auto']} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={value => [`${number(typeof value === 'number' ? value : null)} jobs`, 'Expected']} /><Bar dataKey="jobs" fill="var(--operating-forecast)" fillOpacity={0.4} stroke="var(--operating-forecast)" strokeDasharray="3 2" isAnimationActive={false} /></BarChart></ResponsiveContainer></div><p>Low-confidence planning baseline · backtest error {backtest.wape == null ? 'unavailable' : `${number(backtest.wape * 100)}% WAPE`} ({backtest.samples} tests). Calibrated prediction intervals are not yet available.</p><details><summary>See predictions & method</summary><p>Recency-weighted average of up to 8 matching operating weekdays within 84 days. At least 2 matching days; otherwise 7–28 recent operating days are used as a low-confidence fallback. No observed future data enters training. Backtest error uses prior-only predictions for up to 56 observed operating days.</p><div className="operating-data-table"><table><thead><tr><th>Date</th><th>Expected jobs</th>{showRevenue && <th>Expected revenue</th>}<th>Training days</th><th>Method</th></tr></thead><tbody>{upcoming.map(row => <tr key={row.date}><td>{row.date}</td><td>{number(row.jobs)}</td>{showRevenue && <td>{money(row.revenue)}</td>}<td>{row.samples}{row.samples < 4 ? ' · small sample' : ''}</td><td>{row.method ?? 'Insufficient history'}</td></tr>)}</tbody></table></div></details></> : <p>Forward predictions require today’s selection and a current dataset.</p>}</article>
  </section>;
}
