import {useRef,useState} from 'react';
import type {DayRoster,RosterEntry} from '../lib/schedule-crew-roster';
import {truckDisplayLabel} from '../lib/junkware-trucks';
import './schedule-crew-roster.css';
export function ScheduleCrewRoster({date,busy}:{date:string;busy:boolean}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [roster,setRoster]=useState<DayRoster|null>(null),[rows,setRows]=useState<RosterEntry[]>([]),[trucks,setTrucks]=useState<string[]>([]),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[canWrite,setCanWrite]=useState(false);
 const open=async()=>{dialog.current?.showModal();setRoster(null);setRows([]);setMessage('');setWorking(true);
  try{const response=await fetch(`/api/desktop/schedule/roster?date=${date}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setRoster(body.roster);setTrucks(body.trucks);setCanWrite(body.canWrite);const names=[...new Set<string>([...body.names,...body.roster.entries.map((row:RosterEntry)=>row.name)])];setRows(names.map(name=>body.roster.entries.find((row:RosterEntry)=>row.name===name)||{name,status:'pending',truck:'',startTime:''}));}catch(error){setMessage(error instanceof Error?error.message:'Roster could not load.');}finally{setWorking(false);}
 };
 const update=(index:number,patch:Partial<RosterEntry>)=>{setRows(prior=>prior.map((row,i)=>i===index?{...row,...patch}:row));setMessage('');};
 const save=async()=>{if(!roster||working)return;setWorking(true);setMessage('');try{const response=await fetch('/api/desktop/schedule/roster',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,expectedVersion:roster.version,entries:rows})});const body=await response.json();if(!response.ok)throw new Error(body.error);setRoster(body.roster);setRows(body.roster.entries);setMessage('Roster saved.');}catch(error){setMessage(error instanceof Error?error.message:'Save could not be verified. Close and reopen the roster to check.');}finally{setWorking(false);}};
 return <><button type="button" disabled={busy} onClick={()=>void open()}>Crew roster</button><dialog ref={dialog} className="schedule-crew-roster" aria-labelledby="crew-roster-title" onCancel={event=>{if(working)event.preventDefault();}}>
 <div className="crew-roster-heading"><div><h2 id="crew-roster-title">Crew roster</h2><p>{date} · Central time</p></div><button type="button" disabled={working} onClick={()=>dialog.current?.close()} aria-label="Close crew roster">Close</button></div>
 {working&&!roster?<p role="status">Loading roster…</p>:roster&&<><p>{rows.filter(row=>row.status==='scheduled').length} coming in · {rows.filter(row=>row.status==='scheduled'&&!row.truck).length} unassigned</p><div className="crew-roster-rows">{rows.map((row,index)=><div key={row.name} className="crew-roster-row"><strong>{row.name}</strong><label>Status<select aria-label={`${row.name} status`} disabled={working||!canWrite} value={row.status} onChange={event=>update(index,{status:event.target.value as RosterEntry['status'],...(event.target.value!=='scheduled'?{truck:'',startTime:''}:{})})}><option value="pending">Pending</option><option value="scheduled">Scheduled</option><option value="off">Off</option></select></label><label>Truck<select aria-label={`${row.name} truck`} disabled={working||!canWrite||row.status!=='scheduled'} value={row.truck} onChange={event=>update(index,{truck:event.target.value})}><option value="">Unassigned</option>{trucks.map(truck=><option key={truck} value={truck}>{truckDisplayLabel(truck)}</option>)}</select></label><label>Start time<input aria-label={`${row.name} start time`} type="time" disabled={working||!canWrite||row.status!=='scheduled'} value={row.startTime} onChange={event=>update(index,{startTime:event.target.value})}/></label></div>)}</div>{!rows.length&&<p>No crew members are configured.</p>}<button type="button" disabled={working||!canWrite||!rows.length} onClick={()=>void save()}>{working?'Saving…':'Save roster'}</button>{roster.savedAt&&<small>Saved {new Date(roster.savedAt).toLocaleString('en-US',{timeZone:'America/Chicago'})}</small>}</>}
 {message&&<p role="status">{message}</p>}</dialog></>;
}
