import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import { Button } from './components/ui/button';
import { appointmentCategory, appointmentStatus, scheduleFollowupFlags, type ScheduleAppointment } from './lib/schedule-contract';
type CalendarDay = { date: string; available: boolean; observedAt: string | null; count: number | null; routes: number | null; territories: Record<string, number> };
type HistoryRow = { id: string; at: string; appointmentId: string; action: string; actor: string; status: string; detail: string };
export function ScheduleCalendar({ date, openDate }: { date: string; openDate: (date: string) => void }) {
  const [month, setMonth] = useState(date.slice(0, 7));
  const [days, setDays] = useState<CalendarDay[]>([]);
  const [selected, setSelected] = useState(date);
  const [error, setError] = useState('');
  useEffect(() => { setMonth(date.slice(0, 7)); setSelected(date); }, [date]);
  useEffect(() => { const abort = new AbortController(); setDays([]); setError(''); void fetch(`/api/desktop/schedule/calendar?month=${month}`, { cache: 'no-store', credentials: 'same-origin', signal: abort.signal }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setDays(body.days); }).catch(error => { if (!abort.signal.aborted) setError(error.message || 'Calendar unavailable.'); }); return () => abort.abort(); }, [month]);
  const change = (offset: number) => { const next = new Date(`${month}-15T12:00:00Z`); next.setUTCMonth(next.getUTCMonth() + offset); setMonth(next.toISOString().slice(0, 7)); };
  const first = new Date(`${month}-01T12:00:00Z`).getUTCDay();
  const picked = days.find(day => day.date === selected);
  return <section className="schedule-calendar-shell"><div className="section-title"><div><span className="section-kicker">{days.filter(day => day.available).length} source days · {days.reduce((sum, day) => sum + (day.count || 0), 0)} appointments</span><h2>{new Date(`${month}-15T12:00:00Z`).toLocaleDateString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' })}</h2></div><div><Button variant="outline" size="sm" aria-label="Previous month" onClick={() => change(-1)}><ArrowLeft /></Button><Button variant="outline" size="sm" aria-label="Next month" onClick={() => change(1)}><ArrowRight /></Button></div></div>{error && <p role="alert">{error}</p>}<div className="schedule-calendar-grid">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => <span className="calendar-weekday" key={day}>{day}</span>)}{Array.from({ length: first }, (_, index) => <span key={index} className="calendar-empty" />)}{days.map(day => <button className={`calendar-day${day.date === selected ? ' selected' : ''}`} key={day.date} aria-pressed={day.date === selected} onClick={() => setSelected(day.date)}><strong><b>{Number(day.date.slice(-2))}</b></strong><span>{day.available ? `${day.count} scheduled` : 'Source unavailable'}</span><small>{Object.entries(day.territories).map(([code, count]) => <i className={`territory-${code.toLowerCase()}`} key={code}><b>{code}</b>{count}</i>)}</small></button>)}</div>{picked && <section className="calendar-selection-panel"><div className="calendar-selection-heading"><span>Selected Day</span><strong>{selected}</strong><small>{picked.available ? 'Source appointment snapshot' : 'No verified snapshot is available'}</small></div><div className="calendar-selection-metrics"><div><span>Scheduled</span><strong>{picked.count ?? '—'}</strong></div><div><span>Assigned routes</span><strong>{picked.routes ?? '—'}</strong></div><div><span>Capacity</span><strong>—</strong><small>Requires route and load review</small></div></div><Button onClick={() => openDate(selected)}>Open Board <ArrowRight /></Button></section>}</section>;
}
export function ScheduleHistory({ date, jobs, open }: { date: string; jobs: ScheduleAppointment[]; open: (id: string) => void }) {
  const [data, setData] = useState<{ rows: HistoryRow[]; coverage: string } | null>(null);
  const [error, setError] = useState('');
  const [filter, setFilter] = useState('all');
  useEffect(() => { const abort = new AbortController(); setData(null); setError(''); void fetch(`/api/desktop/schedule/history?date=${date}`, { credentials: 'same-origin', cache: 'no-store', signal: abort.signal }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch(error => { if (!abort.signal.aborted) setError(error.message); }); return () => abort.abort(); }, [date]);
  const rows = data?.rows.filter(row => filter === 'all' || filter === 'plan' && ['move', 'assignment'].includes(row.action) || filter === 'cancel' && row.action === 'cancel' || filter === 'verified' && row.status === 'verified') || [];
  return <div className="schedule-history-grid"><section className="schedule-history-shell"><div className="section-title"><div><span className="section-kicker">{date}</span><h2>Activity History</h2></div></div><p>{data?.coverage || error || 'Loading saved activity…'}</p><div className="history-overview" role="tablist" aria-label="History filters">{[['all', 'All Activity'], ['plan', 'Plan Changes'], ['cancel', 'Cancellations'], ['verified', 'Verified Results']].map(([key, label]) => <button key={key} role="tab" aria-selected={key === filter} className={key === filter ? 'active' : ''} onClick={() => setFilter(key)}><span>{label}</span></button>)}</div><div className="history-list">{rows.map(row => { const job = jobs.find(job => job.appointmentId === row.appointmentId); return <article className={`history-row ${row.action}`} key={row.id}><div className="history-kind"><strong>{row.action.replaceAll('_', ' ')}</strong><time>{new Date(row.at).toLocaleTimeString('en-US', { timeZone: 'America/Chicago' })}</time></div><div className="history-change"><strong>{job?.jkNumber || `Appointment ${row.appointmentId}`}</strong><span>{row.detail}</span><small>{row.status}</small></div><div className="history-origin"><span><b>Changed by</b>{row.actor}</span></div>{job && <Button variant="outline" size="sm" onClick={() => open(job.recordId)}>Open</Button>}</article>; })}{data && !rows.length && <div className="history-empty"><strong>No saved events in this view</strong><span>Source-system history may contain additional changes.</span></div>}</div></section></div>;
}
export function ScheduleFollowup({ jobs, open }: { jobs: ScheduleAppointment[]; open: (id: string) => void }) {
  const [filter, setFilter] = useState<'all' | 'estimates' | 'closed' | 'unclosed' | 'photos'>('all');
  const rows = jobs.map(job => ({ job, flags: scheduleFollowupFlags(job, jobs) })).filter(({ flags }) => flags.estimates || flags.closed || flags.unclosed || flags.photos);
  const visible = rows.filter(({ flags }) => filter === 'all' || flags[filter]);
  const counts = { all: rows.length, estimates: rows.filter(({ flags }) => flags.estimates).length, closed: rows.filter(({ flags }) => flags.closed).length, unclosed: rows.filter(({ flags }) => flags.unclosed).length, photos: rows.filter(({ flags }) => flags.photos).length };
  const unknownPhotoAudits = jobs.filter(job => !/cancel/i.test(job.status) && /complete|closed|paid/i.test(job.status) && !job.photoAuditAvailable).length;
  return <section className="schedule-followup-shell"><div className="section-title"><div><span className="section-kicker">{rows.length} source records requiring review</span><h2>Follow-Up Queue</h2></div></div>
    <div className="followup-overview" aria-label="Follow-up summary">{([['all', 'Needs review', 'Available source observations'], ['estimates', 'Open estimates', 'Pricing and contact'], ['unclosed', 'Unclosed jobs', 'Closeout required'], ['photos', 'Missing photos', 'Verified empty photo audit']] as const).map(([key, label, detail]) => <button className={filter === key ? 'active' : ''} key={key} onClick={() => setFilter(key)}><span>{label}</span><strong>{counts[key]}</strong><small>{detail}</small></button>)}</div>
    <div className="followup-filters">{([['all', 'All'], ['estimates', 'Open estimates'], ['closed', 'Closed estimates'], ['unclosed', 'Unclosed jobs'], ['photos', 'Missing photos']] as const).map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{label} <span>{counts[key]}</span></button>)}</div>
    {unknownPhotoAudits > 0 && <p>{unknownPhotoAudits} closed appointment(s) have unavailable photo audits. They are not counted as confirmed missing photos.</p>}
    <div className="followup-list">{visible.map(({ job, flags }) => <article className="followup-row warning" key={job.recordId}><div className="followup-record-type"><i /><strong>{flags.photos ? 'Missing photos' : flags.closed ? 'Closed estimate' : flags.estimates ? 'Open estimate' : 'Unclosed job'}</strong><small>{appointmentStatus(job)}</small></div><div className="followup-record-main"><strong><button className="jk-record-link" onClick={() => open(job.recordId)}>{job.jkNumber || `Appointment ${job.appointmentId}`}</button> · {job.customerName}</strong><span>{job.appointmentNotes.join(' · ') || 'Review the source record and record any follow-up as a note.'}</span>{appointmentCategory(job) === 'Estimate' && <small>{flags.linkedBooking ? <>Source-linked booking: <button className="jk-record-link" onClick={() => open(flags.linkedBooking!.recordId)}>{flags.linkedBooking.jkNumber || flags.linkedBooking.appointmentId}</button> · Appointment {flags.linkedBooking.appointmentId}</> : 'No source-linked booking is present in this day’s snapshot; other dates may contain a booking.'}</small>}{flags.photos && <small>JunkWare photo audit is available and contains no photos.</small>}</div><div className="followup-record-meta"><span><b>Area</b>{job.territory || 'Unavailable'}</span><span><b>Krewe</b>{[job.driver, job.navigator].filter(Boolean).join(' · ') || 'Unassigned'}</span></div><div className="followup-record-actions"><Button variant="outline" size="sm" onClick={() => open(job.recordId)}>Open and Review</Button></div></article>)}{!visible.length && <div className="followup-empty"><strong>No matching records in this snapshot</strong><span>This view covers the selected date only.</span></div>}</div><p>Closed estimates remain separate from completed jobs. Booking links use the source estimate appointment ID; sharing a JK number does not establish a booking relationship.</p></section>;
}
