import { knowledgeSnapshot } from './knowledge-store';
import { knowledgeStatus, outcomeLabel, type KnowledgeEntry, type KnowledgeSnapshot } from '../desktop-ui/lib/knowledge-contract';
import type { MaintenanceSnapshot } from '../desktop-ui/lib/maintenance-contract';
import type { KnowledgeTroubleshooting, KnowledgeTroubleshootingCase } from '../desktop-ui/lib/knowledge-troubleshooting-contract';

type Profile = { terms: RegExp; topics: string[]; assessment: string; checks: string[]; verification: string };
const profiles: Record<string, Profile> = {
  availability: { terms: /startup|outage|host error|public.*(?:524|cloudflare)|relay|continuity/i, topics: ['release-and-recovery'], assessment: 'The observer could not confirm local login availability. This does not identify the failing process or establish public-route health.', checks: ['Compare local login, service ownership and the public route as separate signals.', 'Check the existing bounded process-recovery receipt before considering another action.'], verification: 'Require current local login and public-route results, then reproduce the affected authenticated interaction.' },
  'health-probe': { terms: /health|readiness|outage|liveness/i, topics: ['source-freshness'], assessment: 'Application health evidence was unavailable. Source health remains unproven.', checks: ['Read the health response and its timestamp; compare it with local login availability.', 'Inspect the recorded failure without treating missing data as a healthy response.'], verification: 'Require fresh successful health observations and the relevant source-specific checks.' },
  'readiness-probe': { terms: /readiness|health|queue/i, topics: ['source-freshness'], assessment: 'The readiness probe did not establish usable dependency evidence.', checks: ['Compare readiness with application health.', 'Identify which dependency lacks evidence before choosing a remedy.'], verification: 'Require current readiness evidence for the affected dependency, not just an HTTP 200 login.' },
  metrics: { terms: /metric|labor|revenue|financial.*fresh|data.*(?:stale|collection)|freshness/i, topics: ['source-freshness','payroll'], assessment: 'The observer reports unavailable or stale daily metrics. The specific metric source must be identified before selecting a past fix.', checks: ['Check the requested operating date and per-metric source timestamps.', 'For Labor, check only the rates used by the current payroll; for revenue, check its own source independently.'], verification: 'Recheck the named metric amount, ratio and source timestamp in the authenticated UI; preserve last-known values with their age.' },
  schedule: { terms: /schedule.*(?:stale|refresh|synchron|latency)|junkware.*(?:stale|refresh|synchron)|collector.*(?:stale|fresh)|reschedule/i, topics: ['source-freshness','receipt-recovery'], assessment: 'Schedule evidence is stale. This is not evidence that appointments were deleted or that a pending move failed.', checks: ['Check the source date, market snapshots and schedule detector evidence.', 'If a move is uncertain, read its terminal JunkWare receipt before reviewing a new action.'], verification: 'Require fresh schedule evidence plus matching board/detail read-back for the affected appointment.' },
  gps: { terms: /gps|linxup|tracker|truck.*(?:movement|location)/i, topics: ['gps-and-visits'], assessment: 'Location evidence is stale. Distinguish a receiver/collector problem from individual silent trackers.', checks: ['Compare V3 push age, processed snapshot age and each affected truck timestamp.', 'Inspect processing-lock ownership and newer away reports before interpreting parked presence.'], verification: 'Observe a newer real report in the affected truck view without a manual refresh; retain honest stale labels for silent trackers.' },
  storage: { terms: /disk|storage|retention|write.*permission/i, topics: ['release-and-recovery'], assessment: 'Operator storage is not confirmed writable. A historical disk incident is a lead, not proof that disk space is the current cause.', checks: ['Inspect available disk space and the affected directory permissions without changing records.', 'Use the documented retention report to identify eligible generated files; preserve unique source and runtime records.'], verification: 'Require a successful storage-readiness observation and the exact affected save/read-back path.' },
  database: { terms: /database|slow.*page|page.*load|postgres/i, topics: ['release-and-recovery'], assessment: 'The database health check failed. Connection configuration, process state and stale locks require separate evidence.', checks: ['Inspect database readiness and configured connection ownership.', 'If a PID file is suspected, compare its process identity and startup time; do not remove a lock based on an old incident.'], verification: 'Require fresh database readiness and successful reads through the affected authenticated workspace.' },
  'crew-sync': { terms: /crew portal|portal.*(?:publication|sync)|pay.*privacy/i, topics: ['payroll'], assessment: 'Crew Portal publication is failed, stale or unverified. This does not establish that the employee data itself is wrong.', checks: ['Compare the latest publication receipt with the portal source timestamp.', 'Read back the affected employee mapping and private pay view on the separate portal surface.'], verification: 'Require a current successful publication receipt and the correct employee-specific portal view.' },
  'photo-queue': { terms: /photo|whatsapp/i, topics: ['photos-and-intake'], assessment: 'The photo queue could not be read. Queue availability and held-photo review are separate conditions.', checks: ['Inspect queue-directory availability and the dedicated worker receipt.', 'Preserve original files and uncertain-upload receipts.'], verification: 'Require readable queues and a terminal receipt for the affected batch.' },
  'photo-review': { terms: /photo.*(?:review|held|recover|missing)|missing.*photo|whatsapp.*photo/i, topics: ['photos-and-intake'], assessment: 'Photos are awaiting review or have failed records. This is a review workload, not proof of an application outage.', checks: ['Match the original photo, exact appointment and sender/truck evidence.', 'Check existing upload and delivery receipts before any authorized retry or reassignment.'], verification: 'Confirm each reviewed item against the original and visible job gallery; unresolved records stay in review.' },
  'photo-processing': { terms: /photo.*(?:latency|processing|batch|recover)|whatsapp.*photo/i, topics: ['photos-and-intake'], assessment: 'An incoming or processing photo batch exceeded the observer threshold. Historical review backlog is not the same delay.', checks: ['Inspect the oldest active batch and worker progress.', 'Check for an existing terminal upload receipt before considering a replay.'], verification: 'Require a terminal receipt and correct gallery read-back, without duplicating another batch.' },
  browser: { terms: /browser|safari|interaction|page.*load|readability|schedule|runtime error/i, topics: ['ui-acceptance'], assessment: 'The browser reported a failed interaction. Server health alone cannot establish that interaction recovery.', checks: ['Reproduce the named interaction in an authenticated session on the current release.', 'Compare that exact failure with the prior incident evidence; a matching keyword does not establish the same cause.'], verification: 'Record a successful affected interaction against the latest failure generation; absence of new reports does not count as recovery.' },
};
profiles['gps-fallback'] = { ...profiles.gps, assessment: 'Fallback delivery is active. Its functioning data must be preserved while V3 delivery is checked.', checks: ['Compare V3 receiver timestamps with the currently functioning fallback.', 'Check the delivery/processing boundary before assuming a truck tracker is silent.'] };
const fallback: Profile = { terms: /(?!) /, topics: [], assessment: 'This observed condition has no mapped troubleshooting guide yet.', checks: ['Inspect the owning source and its timestamp.', 'Capture a dated diagnosis only after the affected condition is established.'], verification: 'Require the owning source result and the exact affected interaction before closure.' };

function matchHistory(entries: KnowledgeEntry[], profile: Profile, now: number) {
  // Titles/summaries must match a defined symptom family. Topic-only overlap cannot diagnose an incident.
  return entries.filter(entry => entry.status !== 'archived' && profile.terms.test(`${entry.title} ${entry.summary}`))
    .map(entry => ({ entry, score: Number(profile.terms.test(entry.title)) * 4 + (entry.learning?.topics.filter(topic => profile.topics.includes(topic)).length || 0) * 2 + Number(entry.kind === 'pattern') + Number(entry.learning?.outcome === 'fixed') }))
    .sort((a,b) => b.score - a.score || (b.entry.learning?.recordedAt || b.entry.updatedAt).localeCompare(a.entry.learning?.recordedAt || a.entry.updatedAt) || a.entry.id.localeCompare(b.entry.id))
    .slice(0, 4).map(({entry}) => ({ id: entry.id, title: entry.title, summary: entry.summary, reason: 'Recorded symptom family matches this observer signal; cause still needs verification.', recordedAt: entry.learning?.recordedAt || entry.updatedAt, outcome: entry.learning ? outcomeLabel[entry.learning.outcome] : 'Documented guidance', reviewStatus: knowledgeStatus(entry, now) }));
}
export function diagnoseFromKnowledge(snapshot: MaintenanceSnapshot, knowledge: KnowledgeSnapshot, now = Date.now()): KnowledgeTroubleshooting {
  const age = now - Date.parse(snapshot.checkedAt || '');
  const current = snapshot.available && snapshot.fresh && age >= 0 && age < 180000;
  const cases: KnowledgeTroubleshootingCase[] = snapshot.available ? snapshot.incidents.map(incident => {
    const profile = profiles[incident.key] || (incident.key.startsWith('client-') ? profiles.browser : fallback);
    const browserVerified = !incident.key.startsWith('client-') || Boolean(incident.clientFailureAt && incident.recoveryVerifiedAt && incident.recoveryVerifiedAt > incident.clientFailureAt && incident.recoveryVerifiedAt <= now);
    const cleared = incident.status === 'resolved' && incident.unhealthy === false && browserVerified;
    const state = !current ? 'stale' : cleared ? 'cleared' : incident.unhealthy === null || (incident.status === 'resolved' && !cleared) ? 'awaiting-verification' : incident.unhealthy === false ? 'recovering' : incident.status === 'confirming' ? 'confirming' : 'active';
    return { key: incident.key, title: incident.title, area: incident.area, state, evidence: incident.evidence,
      assessment: state === 'stale' ? 'Observer evidence is stale. Refresh the observation before drawing a current conclusion.' : state === 'cleared' ? 'The observer recorded recovery. Related historical lessons remain available if this condition returns.' : state === 'recovering' ? 'A healthy observation has arrived; the remaining confirmation checks are still pending.' : state === 'awaiting-verification' ? 'Current recovery evidence is missing. An old failure is not proof of a current failure, and silence is not proof of recovery.' : profile.assessment,
      nextChecks: state === 'stale' ? ['Restore a fresh observer read; compare its timestamp with the owning source.'] : profile.checks,
      verification: profile.verification, occurrences: incident.occurrences, firstSeenAt: incident.firstSeenAt, lastSeenAt: incident.lastSeenAt, resolvedAt: cleared ? incident.resolvedAt : null,
      matches: knowledge.available ? matchHistory(knowledge.entries, profile, now) : [] };
  }) : [];
  return { available: snapshot.available, current, observedAt: snapshot.checkedAt, evaluatedAt: new Date(now).toISOString(), knowledgeAvailable: knowledge.available,
    message: !snapshot.available ? 'Observer evidence is unavailable. No current diagnosis can be established.' : !current ? 'Observer evidence is stale. Past matches are research leads only.' : !knowledge.available ? 'Historical knowledge is unavailable. Source checks remain available; historical matches are paused.' : 'Automatically matched from the existing observer and local Second Brain records. Possible explanations require source verification; no repair is executed.', cases };
}
export function knowledgeTroubleshooting(snapshot: MaintenanceSnapshot, now = Date.now()) {
  return diagnoseFromKnowledge(snapshot, knowledgeSnapshot(true), now);
}
