import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LiveFinance } from '../live-finance';
import type { FinanceData, FinanceView } from '../lib/commercial-contract';
import '../app/globals.css';
import '../live-responsive.css';
import '../workspace-density.css';
import '../daily-finance-freshness.css';
const data: FinanceData = {
 date:'2026-09-16', available:true, generatedAt:new Date().toISOString(),
 daily:{revenue:4200,costs:1800,profit:2400,recyclingIncome:0},
 month:{label:'September 2026',through:'2026-09-16',complete:false,missingDates:['2026-09-10'],revenue:64500,jobs:145,costs:null,profit:null,source:'Fixture'},
 trends:[92000,118000,104000,133000,126000,64500].map((grossRevenue,index)=>({monthKey:`2026-${String(index+4).padStart(2,'0')}`,monthDisplay:'Fixture month',dataThroughDate:`2026-${String(index+4).padStart(2,'0')}-${index===5?'16':'30'}`,complete:index!==5,reportingComplete:index!==5,grossRevenue,totalOperatingExpenses:null,estimatedOperatingProfit:null,completedJobs:200,revenueSource:'Fixture'})),
 territories:['Baton Rouge','Jefferson Parish','New Orleans','Northshore'].map((territory,index)=>({territory:`Junk King ${territory}`,jobs:30+index,revenue:[14000,12000,23000,15500][index]})),
 costs:['Payroll','Dump Expense','Fuel Expense','Other Expense'].map(category=>({category,amount:null,source:'Cost inputs incomplete or stale'})),
 reconciliation:{status:'collected',generatedAt:new Date().toISOString(),merchantCenterAvailable:true,merchantCenterFresh:true,summary:{junkware_count:0,junkware_total:0,merchant_center_total:0,matched_count:0,net_difference:0,exception_count:0},paymentsByJob:[],exceptions:[]},
 resale:[],resaleUpdatedAt:null,recycling:[],recyclingVersion:'fixture',recyclingIncomeRows:[]
};
// Synthetic records only. This fixture never contacts financial providers.
data.reconciliation.recordedPayments = { total: 1200, cash: 200, check: 300 };
data.reconciliation.summary = { junkware_count: 4, junkware_total: 1200, merchant_center_total: 400, matched_count: 1, net_difference: -300, exception_count: 1 };
data.reconciliation.paymentsByJob = (['card','card','cash','check'] as const).map((tender,index)=>({date:data.date,jkNumber:`DEMO-${index+1}`,customer:['Sample card customer','Sample pending customer','Sample cash customer','Sample check customer'][index],paymentMethod:tender,tender,checkNumber:tender==='check'?'1234':undefined,truck:`Truck ${index+1}`,paidAmount:[400,300,200,300][index],revenueAmount:[380,300,200,300][index],tipAmount:index===0?20:0,qboTransactionId:index===0?'DEMO-QBO-1':null,qboStatus:index===0?'Posted':null,reconciliation:index===0?'Matched':'Unmatched'}));
data.resale = (['to_list','listed','sold'] as const).map((status,index)=>({itemId:`demo-item-${index}`,itemNumber:`DEMO-RS-${index+1}`,version:'fixture',itemName:['Oak sideboard','Vintage reading chair','Small writing desk'][index],acquiredDate:data.date,source:`DEMO-${index+1}`,cost:0,askingPrice:[250,180,120][index],soldPrice:status==='sold'?100:0,status,marketplace:index?'Local marketplace':'',notes:'Synthetic inventory for layout review.',createdAt:data.generatedAt!,updatedAt:data.generatedAt!}));
data.recycling = (['Submitted','Paid'] as const).map((status,index)=>({id:`demo-run-${index}`,version:'fixture',date:data.date,material:'Mixed metal',sourceJob:`DEMO-${index+1}`,yard:'Sample recycling yard',quantity:'420 lb',netWeightLb:420,expectedValue:null,realizedValue:status==='Paid'?86:null,ticket:`DEMO-TICKET-${index+1}`,paymentReference:status==='Paid'?'DEMO-CASHOUT':'',paymentDate:status==='Paid'?data.date:'',status,owner:'Sample crew',note:'Synthetic delivery evidence',updatedAt:data.generatedAt!}));
data.statements = {available:true,error:null,importedAt:data.generatedAt,records:(['qbo','workbook'] as const).map(sourceKind=>({id:`demo-${sourceKind}`,sourceId:'demo-statement',sourceKind,sourceName:sourceKind==='qbo'?'Sample QuickBooks report':'Sample accountant draft',sheet:'Profit and Loss',company:'Sample company',month:'2026-09',reportThrough:'2026-09-16',basis:'Accrual',status:sourceKind==='qbo'?'Current books':'Draft',periodEnd:'2026-09-16',observedAt:data.generatedAt!,totals:{income:6450000,cogs:1700000,grossProfit:4750000,expenses:2100000,operatingIncome:2650000,otherIncome:0,otherExpenses:0,netOtherIncome:0,netIncome:2650000},rows:[{label:'Income',cents:6450000,cell:'B2',formula:null},{label:'Net Income',cents:2650000,cell:'B3',formula:null}],supplemental:[],annotations:[],warnings:[]}))};
const fixture = {...data,
 dumpExpenses:{date:data.date,policyAvailable:true,geofencesAvailable:true,observedAt:data.generatedAt,actualTotal:240,assumedTotal:75,total:315,missingMinimumCount:0,records:[{id:'demo-disposal',date:data.date,truck:'Truck 1',location:'Sample disposal facility',enteredAt:data.generatedAt,departedAt:null,replaceUntil:null,amount:240,assumedAmount:75,status:'actual',window:'closed',actualExpenseId:'demo-expense',transactionAt:data.generatedAt}]},
 fuelReconciliation:{date:data.date,wexImportedAt:data.generatedAt,wexAvailable:true,matchedCount:1,differenceCount:0,reportedTotal:89,wexFuelTotal:89,rows:[{id:'demo-fuel',truck:'Truck 1',date:data.date,location:'Sample fuel station',status:'matched',reason:'Matching sample receipt and amount',reportedId:'demo-reported',wexId:'demo-wex',reportedAmount:89,wexFuelAmount:89,wexNetAmount:89,difference:0}]}
};
window.fetch = async () => new Response(JSON.stringify(fixture), {status:200,headers:{'Content-Type':'application/json'}});
function Fixture() { const [view,setView]=useState<FinanceView>('overview'); return <div className="ops-app ops-live"><aside className="ops-sidebar"><div className="brand-lockup"><strong>OpsCenter</strong></div><nav className="primary-nav">{['Command','Control','Crew','Convoy','Capital','Campaign'].map(name=><div className={`nav-item ${name==='Capital'?'active':''}`} key={name}>{name}</div>)}</nav></aside><main className="ops-content"><div className="workspace"><div className="workspace-heading"><div><h1>Capital</h1><p>Performance, payments and financial decisions. All in one place.</p></div><div className="workspace-tabs finance-view-switcher" role="tablist" aria-label="Capital views">{(['overview','payments','expenses','accounting','resale','recycling','trends'] as const).map(item=><button key={item} role="tab" aria-selected={view===item} className={view===item?'active':''} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div></div><LiveFinance date={data.date} view={view} onViewChange={setView}/></div></main></div>; }
createRoot(document.getElementById('root')!).render(<Fixture/>);
