import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import LiveFleet from '../live-fleet';
import { convoyTabs } from '../lib/convoy-presentation';
import type { DesktopFleetSnapshot, FleetView } from '../lib/people-fleet-contract';
import '../app/globals.css';
import '../live-responsive.css';
import '../workspace-density.css';

const date='2026-10-08';
const check={version:'fixture',inspector:'Example inspector',definitions:[{itemId:'tires',label:'Tires',guidance:'Check all tires'}],answers:[{itemId:'tires',status:'pass',notes:''}]};
const snapshot:DesktopFleetSnapshot={date,report:'overview',canWrite:true,sourceAvailable:true,sourceUpdatedAt:new Date().toISOString(),reportCoverageDays:15,warnings:['Truck# 4: load reconciliation needs attention. Check the pickup order.'],
  intervals:[],mileageRetrievedAt:new Date().toISOString(),mileageSourceDate:'2026-10-06',trucks:[1,2,3,4,5,6,7,8,9].map(id=>({id:`Truck# ${id}`,label:`Truck# ${id}`,vehicle:'2022 Isuzu NRR',vin:id===5?null:`JALC4W164M700000${id}`,vinNeedsVerification:id===8,fuel:id===5?null:{percent:id===2?100:id===4?25:75,at:date+'T15:00:00Z',source:id===2?'purchase':'inspection',detail:id===2?'Assumed full after fuel purchase':'Reported at inspection'},inspectionLevels:{fuel:id===2?25:75,load:25,at:date+'T12:00:00Z'},loadUpdatedAt:date+'T16:00:00Z',mileage:{value:id===5?null:id*30000+1000,source:id===4?'true':'virtual',reportedAt:new Date(Date.now()-([1,7].includes(id)?40*86400000:60000)).toISOString(),retrievedAt:new Date().toISOString(),estimated:id===3?143000:null,conflicting:[3,8,9].includes(id),duplicate:false},readiness:id===4?'Out of service':[1,2,7].includes(id)?'Attention':'Ready',operatingStatus:'Parked',driver:'Example driver',navigator:'Not assigned',assignment:'None',location:'Unavailable',gpsAt:null,gpsFreshness:'GPS unavailable',odometer:'Unavailable',serviceStatus:'Unavailable',nextService:'No source target',checklist:[1,7].includes(id)?'Missing':id===4?'Problem reported':'Complete',inspectionFindings:id===4?[{label:'Wheels & tires',notes:'Rear passenger tire has a cut in the sidewall. Inspect before the next route.'},{label:'Dashboard check',notes:'Check engine light remains on.'}]:[],loadPercent:id===2?50:0,loadLabel:id===2?'1/2 full':'Empty · provisional',loadNeedsVerification:id===4,loadNote:'Example inspection and load evidence',loadVersion:'fixture',checklistVersion:'fixture',checklists:{daily:check,weekly:check,monthly:check},checklistDefinitions:check.definitions,answers:check.answers,jobs:2,revenue:400,miles:null,idleMinutes:null,driverScore:null})),
  issues:[{issueId:'repair-4',truck:'Truck# 4',title:'Tire replacement',description:'Example tire issue',severity:'out_of_service',status:'open',owner:'Existing shop',dueDate:'2026-09-18',resolution:'',cost:null,downtimeHours:null,updatedAt:date,version:'fixture'} ,{issueId:'repair-2',truck:'Truck# 2',title:'Replace mirror',description:'Replacement part ordered',severity:'repair_soon',status:'in_progress',owner:'',dueDate:'',resolution:'',cost:null,downtimeHours:null,updatedAt:date,version:'fixture'},{issueId:'resolved-4',truck:'Truck# 4',title:'Tail light',description:'',severity:'monitor',status:'resolved',owner:'',dueDate:'',resolution:'Bulb replaced',cost:20,downtimeHours:0,updatedAt:date,version:'fixture'}],maintenance:[{recordId:'planned-2',truck:'Truck# 2',serviceDate:'2026-09-19',status:'scheduled',serviceType:'Brakes',description:'Inspection booked',odometer:null,cost:null,vendor:'Example shop',nextServiceDate:'',nextServiceOdometer:null,notes:'',version:'fixture'}],reportRows:[{truck:'Truck 4',jobsCompleted:2,revenue:400,miles:12,idleTimeMinutes:0,averageDriverScore:null}],drivingScores:[]};
const invoice={recordId:'invoice-example-100',truck:'Truck# 4',serviceDate:'2026-07-21',status:'completed',serviceType:'Other',description:'Invoice #100 — completed service and repairs\nOil change: replaced oil and filter\nBrakes: replaced rear brake shoes',odometer:120000,cost:520,vendor:'Example repair shop',nextServiceDate:'',nextServiceOdometer:null,notes:'Synthetic acceptance fixture.',version:'fixture'};
snapshot.maintenance.push(invoice,{...invoice,recordId:'invoice-example-100-oil',serviceType:'Oil change',description:'Replaced oil and filter',cost:null,notes:'Linked invoice record: invoice-example-100. Category cost is unallocated.'},{...invoice,recordId:'invoice-example-100-brakes',serviceType:'Brakes',description:'Replaced rear brake shoes',cost:null,notes:'Linked invoice record: invoice-example-100. Category cost is unallocated.'});
for (const [index,serviceDate] of ['2026-03-10','2025-08-19','2025-07-30','2025-04-14'].entries()) {
 snapshot.maintenance.push({...invoice,recordId:`invoice-example-${101+index}`,serviceDate,serviceType:index===1?'Tires':'Oil change',description:`Invoice #${101+index} — completed service and repairs\nEngine: Replaced belt tensioner and belt.\nOil change: Changed oil and filter; checked fluid levels.`,cost:index===0?723.68:index===1?null:index===2?0:510,photos:[{photoId:'fixture-photo',fileName:'Example invoice.svg',mimeType:'image/svg+xml'}]});
}
snapshot.intervals=[{truck:'Truck# 4',serviceType:'Oil change',miles:5000,months:null,enabled:true,updatedAt:date,version:'fixture'}];
const receipts=new Map<string,unknown>();
window.fetch=async(input,init)=>{
 const url=new URL(String(input),location.origin);
 if(url.pathname!=='/api/desktop/fleet')return Response.json({});
 if(init?.method==='POST'){
  const request=JSON.parse(String(init.body));
  const receipt={status:'verified',requestId:request.requestId};receipts.set(request.requestId,receipt);
  if(request.action==='maintenance'){snapshot.maintenance=snapshot.maintenance.filter(r=>r.recordId!==request.values.recordId);snapshot.maintenance.push({...request.values,recordId:request.values.recordId||request.requestId,truck:request.truck,odometer:request.values.odometer?Number(request.values.odometer):null,cost:request.values.cost?Number(request.values.cost):null,nextServiceOdometer:request.values.nextServiceOdometer?Number(request.values.nextServiceOdometer):null,version:'fixture-new'});}
  if(request.action==='interval'){snapshot.intervals=(snapshot.intervals||[]).filter(i=>!(i.truck===request.truck&&i.serviceType===request.values.serviceType));snapshot.intervals.push({...request.values,truck:request.truck,miles:Number(request.values.miles)||null,months:Number(request.values.months)||null,version:'fixture-new'});}
  if(request.action==='issue_delete')snapshot.issues=snapshot.issues.filter(issue=>issue.issueId!==request.values.issueId);
  if(request.action==='issue')snapshot.issues=snapshot.issues.map(issue=>issue.issueId===request.values.issueId?{...issue,...request.values,version:'fixture-new'}:issue);
  if(request.action==='load_reset')snapshot.trucks=snapshot.trucks.map(truck=>truck.id===request.truck?{...truck,loadPercent:0,loadLabel:'Empty',loadNeedsVerification:false,loadVersion:'fixture-reset'}:truck);
  if(request.action==='load_snapshot')snapshot.trucks=snapshot.trucks.map(truck=>truck.id===request.truck?{...truck,loadPercent:request.values.loadFraction*100,loadLabel:`${request.values.loadFraction*100}% full`,loadNeedsVerification:false,loadVersion:'fixture-new'}:truck);
  return Response.json({receipt});
 }
 if(url.searchParams.has('receipt'))return Response.json({receipt:receipts.get(url.searchParams.get('receipt')||'')});
 console.debug('Fixture Fleet read');
 await new Promise(resolve=>setTimeout(resolve,700));
 return Response.json(snapshot);
};
function Fixture(){const[view,setView]=useState<FleetView>('overview');return <div className="ops-app ops-live"><style>{'@font-face{font-family:ConvoyInter;src:url(/desktop-assets/fonts/InterVariable.woff2) format("woff2");font-weight:100 900;font-display:swap}'}</style><aside className="ops-sidebar"><div className="brand-lockup"><img src="/desktop-assets/opscenter-wordmark.png" alt="OpsCenter" width="160"/></div><nav className="primary-nav">{['Command','Control','Crew','Convoy','Capital','Campaign'].map(name=><div className={`nav-item ${name==='Convoy'?'active':''}`} key={name}>{name}</div>)}</nav></aside><main className="ops-content"><div className="workspace convoy-mode"><div className="workspace-heading"><div><span className="eyebrow">Convoy · synthetic acceptance data</span><h1>{view==='overview'?'Fleet overview':view==='service'?'Service planner':convoyTabs.find(([key])=>key===view)?.[1]}</h1><p>{view==='maintenance'?'Choose a truck. Review findings. Follow repairs through to resolution.':view==='service'?'Choose a truck. Check its next service. Schedule or record the work.':'Choose a truck. Find a visit. Open its work and photos.'}</p></div><nav className="workspace-tabs convoy-tabs" role="tablist" aria-label="Convoy views">{convoyTabs.map(([key,label])=><button key={key} role="tab" className={view===key?'active':''} aria-selected={view===key} onClick={()=>setView(key)}>{label}</button>)}</nav></div><LiveFleet date={date} view={view} onViewChange={setView}/></div></main></div>;}
createRoot(document.getElementById('root')!).render(<Fixture/>);
