/** Browser-safe commercial projections. Source IDs remain distinct from JK references. */
export type MarketingView = 'overview' | 'leads' | 'reviews' | 'performance';
export type FinanceView = 'overview' | 'payments' | 'resale' | 'recycling' | 'trends';
export type CommercialOperation = { requestId: string; date: string; action: 'lead.update' | 'review.assign' | 'resale.save' | 'recycling.save'; recordId: string; expectedVersion: string; values: Record<string, unknown> };
export type CommercialReceipt = { requestId: string; recordId: string; action: CommercialOperation['action']; actor: string; fingerprint: string; expectedVersion?: string; input?: Record<string, unknown>; permission?: string; authority?: 'opscenter_authoritative'; status: 'pending' | 'verified' | 'uncertain'; updatedAt: string; message: string };
export type Lead = { id: string; version: string; customer: string; phone: string; territory: string; intent: string; quotedValue: number | null; status: string; reason: string; note: string; contacted: boolean; calledAt: string; updatedAt: string; source: string; sourceUrl: string; appointmentId: string | null; jk: string | null; completed: boolean; revenue: number | null };
export type Review = { id: string; version: string; customer: string; location: string; excerpt: string; stars: number; createdAt: string; sourceUrl: string; attribution: { appointmentId?: string; jkNumber?: string; status: string; matchMethod?: string } | null; candidates: Array<{ appointmentId: string; jkNumber: string; label: string }> };
export type MarketingData = { date: string; range: string; fetchedAt: string | null; available: boolean; error: string | null; canAssignReviews: boolean; leads: Lead[]; reviews: Review[]; reviewAvailable: boolean; reviewFetchedAt: string | null; reviewError: string | null; totals: { calls: number; qualified: number; bookings: number; revenue: number; cost: number; completed: number }; sources: Array<{ source: string; calls: number | null; qualified: number; bookings: number; completed: number | null; revenue: number; cost: number }>; jobChange: string };
export type ResaleRecord = { itemId: string; version: string; itemName: string; acquiredDate: string; source: string; cost: number; askingPrice: number; soldPrice: number; status: 'to_list' | 'listed' | 'sold'; marketplace: string; notes: string; createdAt: string; updatedAt: string };
export type RecyclingRecord = { id: string; version: string; date: string; material: string; sourceJob: string; yard: string; quantity: string; expectedValue: number | null; realizedValue: number | null; ticket: string; paymentReference: string; status: 'Awaiting yard' | 'Submitted' | 'Paid'; owner: string; note: string; updatedAt: string };
export type FinanceData = { comparison?: {currentStart:string;currentEnd:string;priorStart:string;priorEnd:string;currentRevenue:number|null;priorRevenue:number|null;currentProfit:number|null;priorProfit:number|null}; date: string; available: boolean; generatedAt: string | null; daily: { revenue: number | null; costs: number | null; profit: number | null; recyclingExpense: number | null }; month: { label: string; through: string; complete: boolean; missingDates: string[]; revenue: number | null; jobs: number | null; costs: number | null; profit: number | null; source: string }; territories: Array<{ territory: string; jobs: number | null; revenue: number | null }>; costs: Array<{ category: string; amount: number | null; source: string }>; trends: Array<{ monthKey: string; monthDisplay: string; dataThroughDate: string; complete: boolean; grossRevenue: number; totalOperatingExpenses: number | null; estimatedOperatingProfit: number | null; completedJobs: number; revenueSource: string }>; reconciliation: { status: string; generatedAt: string | null; merchantCenterAvailable: boolean; merchantCenterFresh: boolean; summary: { junkware_count: number; junkware_total: number; merchant_center_total: number; matched_count: number; net_difference: number; exception_count: number }; paymentsByJob: Array<{ date: string; jkNumber: string; customer: string; paymentMethod: string; paidAmount: number; revenueAmount: number | null; tipAmount: number | null; qboTransactionId: string | null; qboStatus: string | null; reconciliation: string }>; exceptions: Array<{ date: string; type: string; reference: string; customer: string; junkwareAmount: number | null; merchantAmount: number | null }> }; resale: ResaleRecord[]; resaleUpdatedAt: string | null; recycling: RecyclingRecord[]; recyclingVersion: string; recyclingExpenses: Array<{ truck: string; value: number }> };
export const commercialMoney = (value: number | null | undefined) => value == null || !Number.isFinite(value) ? 'Unavailable' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value);
export const commercialPercent = (amount: number | null, total: number | null) => amount == null || !total ? 'Unavailable' : `${(100 * amount / total).toFixed(1)}%`;
export const commercialDate = (date: string) => date && Number.isFinite(Date.parse(date)) ? new Date(date.length === 10 ? `${date}T12:00:00Z` : date).toLocaleString('en-US', { timeZone: 'America/Chicago', month: 'short', day: 'numeric', ...(date.length === 10 ? {} : { hour: 'numeric', minute: '2-digit' }) }) : 'Time unavailable';
