import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { reconcileFleetMileage, type InspectionMileage } from '../lib/fleet-mileage';
import { readInspectionMileage } from '../lib/fleet-mileage-inspections';
import { mileageQuality, servicePlan, type FleetMileage } from '../lib/fleet-service-plan';
const now = Date.parse('2026-10-07T23:00:00Z');
const tracking: FleetMileage = {value:13000, source:'virtual', reportedAt:'2026-10-07T20:00:00Z', retrievedAt:'2026-10-07T20:00:00Z', estimated:143000, conflicting:true, duplicate:false};
const report = (odometer:string, startedAt:string, truck='Truck 2'): InspectionMileage => ({truck,odometer,startedAt,receivedAt:startedAt,inspectionDate:startedAt.slice(0,10),deviceId:'truck-phone',requestId:startedAt});
const latest=report('132782','2026-09-18T20:00:00Z'), prior=report('132767','2026-09-17T20:00:00Z');
const service={truck:'Truck# 2',status:'completed',serviceDate:'2026-05-18',odometer:128582,recordId:'oil',serviceType:'Oil change',nextServiceDate:'',nextServiceOdometer:null};
const rule={truck:'Truck# 2',serviceType:'Oil change',miles:5000,months:null,enabled:true,updatedAt:''};
const select=(rows:InspectionMileage[])=>reconcileFleetMileage('Truck# 2',tracking,rows,[service],now);
const corrected=select([prior,latest,report('1000000','2026-09-16T20:00:00Z')]);
assert.equal(corrected.value,132782);
assert.equal(corrected.reportedAt,latest.startedAt);
assert.equal(corrected.tracking?.value,13000);
assert.equal(corrected.source,'inspection');
assert.equal(mileageQuality(corrected,now),'stale');
assert.ok(corrected.inspectionHref?.includes('report=truck-phone%3A'));
assert.equal(select([report('11111',latest.startedAt),prior]).value,null);
assert.equal(select([report('1000000',latest.startedAt),prior]).conflicting,true);
assert.equal(select([report('132700',latest.startedAt),prior]).conflicting,true);
assert.equal(select([report('140000','2026-10-08T01:00:00Z'),prior]).conflicting,true);
assert.equal(reconcileFleetMileage('Truck 2',tracking,[latest],[],now).conflicting,true);
assert.equal(reconcileFleetMileage('Truck 2',tracking,[],[],now),tracking);
assert.equal(reconcileFleetMileage('Truck 3',tracking,[latest],[],now),tracking);
assert.equal(mileageQuality(select([report('0',latest.startedAt),prior]),now),'conflict');
assert.equal(servicePlan('Oil change',rule,[service],corrected,'2026-10-07',now).milesRemaining,null,'stale below-target observations cannot establish remaining miles');
const olderAbove={...corrected,value:135000};
const due=servicePlan('Oil change',rule,[service],olderAbove,'2026-10-07',now);
assert.equal(due.status,'due');assert.equal(due.milesRemaining,-1418);assert.equal(due.mileageAsOf,latest.startedAt);
assert.equal(servicePlan('Oil change',rule,[service],olderAbove,'2026-09-10',now).status,'unknown');
const fresh={...olderAbove,inspectionDate:'2026-10-07',reportedAt:'2026-10-07T20:00:00Z',retrievedAt:'2026-10-07T20:00:00Z'};
assert.equal(servicePlan('Oil change',rule,[service],fresh,'2026-10-06',now).status,'unknown','fresh observation after selected day is not historical evidence');
assert.equal(servicePlan('Oil change',rule,[{...service,serviceDate:'2026-10-01'}],olderAbove,'2026-10-07',now).status,'unknown','inspection before service is not evidence of current due status');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'fleet-mileage-')), oldRoot=process.env.OPS_TRUCK_INSPECTION_DIR;
try {
 process.env.OPS_TRUCK_INSPECTION_DIR=root;
 assert.deepEqual(readInspectionMileage(),[]);
 fs.mkdirSync(path.join(root,'reports'));const file=path.join(root,'reports','a'.repeat(64)+'.json');
 fs.writeFileSync(file,JSON.stringify({...latest,photos:['excluded-image']}));
 assert.deepEqual(readInspectionMileage(),[latest]);
 fs.writeFileSync(file,JSON.stringify({...latest,odometer:'132800',photos:[]}));fs.utimesSync(file,new Date(),new Date(Date.now()+1000));
 assert.equal(readInspectionMileage()[0].odometer,'132800');
 assert.ok(!('photos' in readInspectionMileage()[0]));
} finally {if(oldRoot===undefined)delete process.env.OPS_TRUCK_INSPECTION_DIR;else process.env.OPS_TRUCK_INSPECTION_DIR=oldRoot;fs.rmSync(root,{recursive:true,force:true});}
console.log('Inspection mileage reconciliation and maintenance evidence passed.');
