import assert from 'node:assert/strict';
import {trackAppointmentVisits} from '../lib/visit-tracking-agent';
import {reconcileAppointmentPositions} from '../lib/appointment-position-tracking';
import {appointmentVisitAlerts} from '../lib/appointment-visit-alerts';
import {scheduleVisitState} from '../lib/desktop-schedule-visits';

const date='2026-09-15',now=Date.parse('2026-09-15T16:10:00Z');
const location={latitude:30,longitude:-90};
const job={appointmentId:'100',jkNumber:'JK100',truck:'Truck 9',location,customerName:'Example',address:'Verified example',territory:'New Orleans'};
const source={appointment_id:'100',jk_number:'JK100',truck_number:'4',match_confidence:'confirmed',visit_count:1,first_arrival:'2026-09-15T16:00:00Z',visit_intervals:[{arrival:'2026-09-15T16:00:00Z',source_timestamps:['2026-09-15T16:05:00Z']}]};
const point=(minute:number,inside=false)=>({timestamp:`2026-09-15T16:${String(minute).padStart(2,'0')}:00Z`,latitude:inside?30:29.99,longitude:inside?-90:-90.1});
const truck={truck:'Truck 4',lastGpsUpdate:'2026-09-15T16:07:00Z',latitude:29.99,longitude:-90.1,routePoints:[point(5,true),point(6),point(7)]};
const original=JSON.stringify(source);
const tracked=trackAppointmentVisits(date,[source],now);
assert.equal(tracked[0].lastSeenAt,'2026-09-15T16:05:00.000Z');
const run=(trucks=[truck],jobs=[job])=>reconcileAppointmentPositions(tracked,jobs,trucks,now);
const visit=run()[0];
assert.equal(visit.truck,'Truck 4','actual visit truck wins over current assignment');
assert.equal(visit.departureSource,'later_position');
assert.deepEqual(visit.departureBounds,{after:'2026-09-15T16:05:00.000Z',by:'2026-09-15T16:06:00.000Z'});
assert.equal(visit.durationSeconds,null,'bounded departure never becomes precise onsite duration');
assert.equal(JSON.stringify(source),original,'collector evidence remains unchanged for closeout/truck attribution');
assert.equal(run([{...truck,routePoints:[]}])[0].departedAt,null,'one noisy latest fix cannot close a visit');
assert.equal(run([{...truck,routePoints:[point(6),point(7,true)],latitude:30,longitude:-90}])[0].departedAt,null,'return inside before confirmation cancels noise');
assert.equal(run([{...truck,routePoints:[point(1),point(7)]}])[0].departedAt,null,'sparse points do not prove a continuous outside interval');
assert.equal(run([{...truck,truck:'Truck 9'}])[0].departedAt,null,'assigned truck cannot close another actual truck visit');
assert.equal(run([truck],[{...job,appointmentId:'200'}])[0].departedAt,null);
assert.equal(run([truck],[job,job])[0].departedAt,null,'ambiguous appointment coordinates fail closed');
assert.equal(reconcileAppointmentPositions(tracked,[{...job,location:null}],[truck],now)[0].departedAt,null,'unverified address cannot infer departure');
assert.equal(reconcileAppointmentPositions(tracked,[job],[truck],Date.parse('2026-09-15T16:06:30Z'))[0].departedAt,null,'future corroborating sample rejected');
const boundary={...truck,latitude:30.0015,longitude:-90,routePoints:[{...point(6),latitude:30.0015,longitude:-90}]};
assert.equal(run([boundary])[0].departedAt,null,'site edge jitter uses an additional distance buffer');
const operational=trackAppointmentVisits(date,[{...source,operational_confirmation:true}],now);
assert.equal(reconcileAppointmentPositions(operational,[job],[truck],now)[0].departedAt,null,'operational confirmation does not supply GPS arrival bounds');
const closed=trackAppointmentVisits(date,[{...source,visit_intervals:[{...source.visit_intervals[0],departure:'2026-09-15T16:05:30Z'}]}],now);
assert.equal(reconcileAppointmentPositions(closed,[job],[truck],now)[0].departedAt,'2026-09-15T16:05:30.000Z','source exact exit takes precedence');
const alert=appointmentVisitAlerts([], [source], [job],date,now,[visit])[0];
assert.equal(alert.label,'Departure');
assert.match(alert.facts.find(f=>f.label==='Departed')!.value,/After.*by/);
assert.match(alert.facts.find(f=>f.label==='Time on site')!.value,/Unavailable/);
assert.equal(alert.id,appointmentVisitAlerts([], [source], [job],date,now)[0].id,'arrival review identity survives bounded departure');
const schedule=scheduleVisitState(job,[source],truck.lastGpsUpdate,[truck],now,[visit]);
assert.equal(schedule.hasDepartedVisit,true);
assert.equal(schedule.truckOnSite,false);
assert.equal(schedule.lastSeenOnsiteTruck,undefined);
assert.equal(schedule.onsiteTime.departure,null);
assert.equal(schedule.onsiteTime.minutes,null);
assert.match(schedule.onsiteTime.label,/exact time unavailable/);
console.log('PASS appointment position tracking: confirmed identity, corroborated coordinates, bounds, noisy samples, unchanged source, Command/Schedule consistency');
const nextSource={...source,visit_intervals:[{arrival:'2026-09-15T16:06:00Z',departure:'2026-09-15T16:08:00Z'}]};
const segments=trackAppointmentVisits(date,[source,nextSource],now);
const reconciled=reconcileAppointmentPositions(segments,[job],[truck],now);
assert.equal(reconciled[0].departedAt,null,'positions in the next recorded segment cannot close the earlier segment');
assert.equal(reconciled[0].supersededAt,'2026-09-15T16:06:00.000Z');
assert.equal(reconciled[1].departedAt,'2026-09-15T16:08:00.000Z');
const segmentAlert=appointmentVisitAlerts([], [source,nextSource], [job],date,now,reconciled).find(alert=>alert.id===reconciled[0].id)!;
assert.equal(segmentAlert.label,'Visit segment');
assert.match(segmentAlert.facts.find(f=>f.label==='Departed')!.value,/Earlier GPS segment; departure time unavailable/);
const instant=trackAppointmentVisits(date,[{...source,visit_intervals:[{arrival:'2026-09-15T16:00:00Z',departure:'2026-09-15T16:00:00Z',departure_confirmed:true}]}],now)[0];
assert.equal(instant.departureSource,'confirmed_appointment','zero-duration source-confirmed visit must not become a false open arrival');
