import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { chromium } from "playwright";
import { AUTH_SESSION_COOKIE, createAuthSessionCookieValue, opsAuthIdentity } from "../lib/auth";
import { inspectionDate } from "../lib/truck-inspection";

async function main() {
  const state = fs.mkdtempSync(path.join(os.tmpdir(), "inspection-browser-"));
  const generatedFiles = ["next-env.d.ts", "tsconfig.json"].map(file => ({ file, content: fs.readFileSync(file, "utf8") }));
  const base = "http://127.0.0.1:3198";
  const productionBuild = process.env.OPS_INSPECTION_BROWSER_BUILD === "1";
  const settings = { OPS_AUTH_USERNAME: "inspectiontest", OPS_AUTH_SESSION_SECRET: randomBytes(32).toString("hex"), OPS_AUTH_ROLE: "admin", OPS_AUTH_ROLE_BINDINGS: "", OPS_ACCESS_AUD: "", OPS_ACCESS_TEAM_DOMAIN: "", OPS_CREW_ACCESS_TEAM_DOMAIN: "", OPS_CREW_ROSTER_JSON: JSON.stringify([{ username: "test.driver", employee: "Test Driver", active: true }]), OPS_TRUCK_INSPECTION_DIR: state, NEXT_DIST_DIR: productionBuild ? ".next" : ".next-inspection-preview", NEXT_TELEMETRY_DISABLED: "1" };
  Object.assign(process.env, settings);
  const output = fs.openSync("/tmp/five-point-preview.log", "w");
  const server = spawn(process.execPath, ["node_modules/next/dist/bin/next", ...(productionBuild ? ["start"] : ["dev", "--webpack"]), "--hostname", "127.0.0.1", "--port", "3198"], { cwd: process.cwd(), env: { ...process.env, ...settings }, stdio: ["ignore", output, output] });
  const browser = await chromium.launch({ headless: true });
  try {
    let ready = false;
    for (let i = 0; i < 60; i++) { try { const r = await fetch(`${base}/truck-inspection`); if (r.ok) { ready = true; break; } } catch {} await new Promise(r => setTimeout(r, 1000)); }
    assert.equal(ready, true, "preview must be ready");
    const manager = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
    await manager.addCookies([{ name: AUTH_SESSION_COOKIE, value: await createAuthSessionCookieValue(opsAuthIdentity()), url: base }]);
    const management = await manager.newPage();
    await management.goto(`${base}/fleet-inspections`);
    await management.getByRole("button", { name: "Manage truck phones", exact: true }).click();
    assert.equal(await management.getByRole("button", { name: "Create one-time setup code" }).count(), 0);
    const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
    const page = await mobile.newPage(); page.setDefaultTimeout(10_000); management.setDefaultTimeout(10_000); const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    const unconnected = await (await mobile.request.get(`${base}/api/truck-inspection`)).json();
    assert.equal(unconnected.device, null);
    assert.equal(unconnected.inspectors, undefined, "unconnected phones receive no crew directory");
    assert.ok(unconnected.trucks.includes("Truck 4"));
    await page.goto(`${base}/truck-inspection`);
    await page.getByRole("heading", { name: "Morning, crew." }).waitFor();
    assert.equal(await page.getByRole("button", { name: "Start inspection" }).isDisabled(), true);
    const connected = await (await mobile.request.get(`${base}/api/truck-inspection`)).json();
    assert.equal(connected.device.truck, undefined);
    assert.deepEqual(connected.inspectors, []);
    await page.reload();
    await page.getByRole("heading", { name: "Morning, crew." }).waitFor();
    assert.equal((await (await mobile.request.get(`${base}/api/truck-inspection`)).json()).device.deviceId, connected.device.deviceId);
    assert.equal(await page.getByRole("combobox", { name: /Truck for this inspection/ }).inputValue(), "");
    await page.getByRole("combobox", { name: /Truck for this inspection/ }).selectOption("Truck 4");
    await page.getByLabel("Your name", { exact: true }).fill("Test Driver");
    await page.getByLabel("Odometer · miles").fill("125040");
    await page.getByRole("button", { name: "Start inspection" }).click();
    await page.getByRole("button", { name: "✓ Good — next check", exact: true }).dblclick();
    await page.getByRole("heading", { name: "Check every wheel." }).waitFor();
    // Changing trucks mid-draft requires an explicit reset; cancel preserves the draft.
    await page.getByRole("button", { name: "← Back", exact: true }).click();
    await page.getByRole("button", { name: "← Back", exact: true }).click();
    page.once("dialog", dialog => dialog.dismiss());
    await page.getByRole("combobox", { name: /Truck for this inspection/ }).selectOption("Truck 8");
    assert.equal(await page.getByRole("combobox", { name: /Truck for this inspection/ }).inputValue(), "Truck 4");
    assert.equal(await page.getByLabel("Odometer · miles").inputValue(), "125040");
    page.once("dialog", dialog => dialog.accept());
    await page.getByRole("combobox", { name: /Truck for this inspection/ }).selectOption("Truck 8");
    assert.equal(await page.getByLabel("Odometer · miles").inputValue(), "");
    await page.getByRole("combobox", { name: /Truck for this inspection/ }).selectOption("Truck 4");
    await page.getByLabel("Odometer · miles").fill("125040");
    await page.getByRole("button", { name: "Start inspection" }).click();
    await page.waitForTimeout(500);
    await page.getByRole("button", { name: "✓ Good — next check", exact: true }).click();
    await page.getByRole("button", { name: "! Report a problem", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "Save problem & continue" }).isDisabled(), true);
    await page.getByLabel("What did you find?").fill("Synthetic test: tire damage requires supervisor review.");
    const photo = await page.screenshot({ clip: { x: 0, y: 0, width: 200, height: 120 } });
    await page.locator('input[type="file"]').setInputFiles({ name: "test-photo.png", mimeType: "image/png", buffer: photo });
    await page.getByRole("img", { name: "Wheels & tires problem photo" }).waitFor();
    await page.getByText("Draft saved on this phone", { exact: true }).waitFor();
    await mobile.setOffline(true);
    await page.getByLabel("What did you find?").fill("Synthetic test: tire damage recorded offline.");
    await page.getByRole("button", { name: "Save problem & continue" }).click();
    assert.equal(await page.getByRole("button", { name: "✓ Good — next check", exact: true }).isDisabled(), true);
    await page.getByRole("button", { name: "Fuel tank 1/2", exact: true }).click();
    await page.waitForTimeout(500);
    await page.getByRole("button", { name: "✓ Good — next check", exact: true }).click();
    await mobile.setOffline(false);
    // Wait for the actual IndexedDB write before testing a reload.
    await page.waitForFunction(async () => new Promise<boolean>(resolve => { const open = indexedDB.open("junk-king-truck-inspection", 1); open.onsuccess = () => { const db = open.result; const req = db.transaction("drafts").objectStore("drafts").getAll(); req.onsuccess = () => { const ok = req.result.some(d => d.fuel === "1/2" && d.answers.some((a: {id:string;status:string}) => a.id === "dashboard" && a.status === "good")); db.close(); resolve(ok); }; }; }));
    await page.reload();
    await page.getByRole("heading", { name: "Test the essentials." }).waitFor();
    await page.locator("header").getByText("Truck 4", { exact: true }).waitFor();
    assert.equal(await page.getByRole("button", { name: "✓ Good — next check", exact: true }).isDisabled(), true);
    await page.getByRole("button", { name: "Truck fullness 3/4", exact: true }).click();
    await page.waitForFunction(async () => new Promise<boolean>(resolve => { const open = indexedDB.open("junk-king-truck-inspection", 1); open.onsuccess = () => { const db = open.result; const req = db.transaction("drafts").objectStore("drafts").getAll(); req.onsuccess = () => { const ok = req.result.some(d => d.loadLevel === "3/4" && d.fuel === "1/2"); db.close(); resolve(ok); }; }; }));
    await page.reload();
    assert.equal(await page.getByRole("button", { name: "Truck fullness 3/4", exact: true }).getAttribute("aria-pressed"), "true");
    await page.getByRole("button", { name: "Truck fullness 3/4", exact: true }).click();
    await page.screenshot({ path: "/tmp/five-point-inspection-review/mobile-fullness.png" });
    await page.getByRole("button", { name: "✓ Good — next check", exact: true }).click();
    await page.waitForTimeout(500);
    await page.getByRole("button", { name: "✓ Good — finish checks", exact: true }).click();
    await page.getByRole("heading", { name: "Can this truck operate?" }).waitFor();
    assert.equal(await page.getByRole("radio", { name: "No problems", exact: true }).isDisabled(), true);
    assert.equal(await page.getByRole("button", { name: "Review report" }).isDisabled(), true);
    await page.getByLabel("Do not operate", { exact: true }).check();
    await page.getByRole("button", { name: "Review report" }).click();
    assert.equal(await page.getByRole("button", { name: "Send to OpsCenter", exact: true }).isDisabled(), true);
    await page.getByLabel("Your initials", { exact: true }).fill("TD");
    // Editing a result returns to review and requires a new operating decision.
    await page.getByRole("button", { name: "Edit Dashboard check", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "Fuel tank 1/2", exact: true }).getAttribute("aria-pressed"), "true");
    await page.waitForTimeout(500);
    await page.getByRole("button", { name: "✓ Good — review", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "Send to OpsCenter", exact: true }).isDisabled(), true);
    await page.getByRole("button", { name: "OPERATING STATUS · CHANGE Choose operating status" }).click();
    await page.getByLabel("Do not operate", { exact: true }).check();
    await page.getByRole("button", { name: "Review report" }).click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.screenshot({ path: "/tmp/five-point-inspection-review/mobile-review.png", fullPage: true });
    let lost = false;
    await page.route("**/api/truck-inspection", async route => {
      if (route.request().method() === "POST" && route.request().postDataJSON().action === "submit" && !lost) { lost = true; const received = await route.fetch(); assert.equal(received.status(), 200); await route.abort("failed"); }
      else await route.continue();
    });
    await page.getByRole("button", { name: "Send to OpsCenter", exact: true }).click();
    await page.getByRole("button", { name: "Check saved result", exact: true }).waitFor();
    await page.getByRole("button", { name: "Check saved result", exact: true }).click();
    await page.getByText("✓ RECEIVED BY OPSCENTER", { exact: true }).waitFor();
    await page.getByRole("heading", { name: "! Do not operate", exact: true }).waitFor();
    await page.getByRole("button", { name: "View submitted report", exact: true }).click();
    await page.getByRole("region", { name: "Submitted report", exact: true }).waitFor();
    await page.screenshot({ path: "/tmp/five-point-inspection-review/mobile-receipt.png", fullPage: true });
    const reportResponse = await manager.request.get(`${base}/api/fleet-inspections?date=${inspectionDate()}`);
    const saved = await reportResponse.json();
    assert.equal(saved.reports.length, 1);
    assert.equal(saved.reports[0].photos.length, 1);
    assert.equal(saved.reports[0].answers[1].notes, "Synthetic test: tire damage recorded offline.");
    assert.equal(saved.reports[0].inspector, "Test Driver");
    assert.equal(saved.reports[0].truck, "Truck 4");
    assert.equal(saved.reports[0].loadLevel, "3/4");
    assert.equal(saved.reports[0].fuel, "1/2");
    assert.equal(saved.reports[0].version, 2);
    const duplicate = await mobile.request.post(`${base}/api/truck-inspection`, { data: { action: "submit", report: saved.reports[0] } });
    assert.equal(duplicate.status(), 200);
    assert.equal((await mobile.request.post(`${base}/api/truck-inspection`, { data: { action: "submit", report: { ...saved.reports[0], truck: "Truck 8" } } })).status(), 409);
    assert.equal((await mobile.request.post(`${base}/api/truck-inspection`, { data: { action: "submit", report: { ...saved.reports[0], truck: "Truck 99" } } })).status(), 400);
    assert.equal((await duplicate.json()).report.receivedAt, saved.reports[0].receivedAt);
    assert.equal((await mobile.request.get(`${base}/api/fleet-inspections`)).status(), 401);
    const stranger = await browser.newContext();
    assert.equal((await stranger.request.get(`${base}/api/truck-inspection?requestId=${saved.reports[0].requestId}`)).status(), 401);
    await stranger.request.post(`${base}/api/truck-inspection`, { data: { action: "connect", connectionToken: "c".repeat(64) } });
    assert.equal((await (await stranger.request.get(`${base}/api/truck-inspection?requestId=${saved.reports[0].requestId}`)).json()).report, null, "a second phone selecting the same truck cannot read the first phone’s report");
    const hooksManagement = await fetch(`${base}/fleet-inspections`, { headers: { "x-forwarded-host": "hooks.junk-king.app" } });
    assert.equal(hooksManagement.status, 404);
    await management.getByRole("button", { name: "Refresh reports" }).click();
    await management.getByRole("button", { name: /Truck 4 · Test Driver/ }).click();
    await management.getByRole("region", { name: "Selected inspection report" }).getByText("Synthetic test: tire damage recorded offline.", { exact: true }).waitFor();
    const levels = await management.getByRole("region", { name: "Selected inspection report" }).locator("dl").innerText();
    assert.match(levels, /Truck fullness\s+3\/4/);
    assert.match(levels, /Fuel tank\s+1\/2/);
    await management.getByRole("combobox", { name: /^Status/ }).selectOption("missing");
    assert.equal(await management.getByRole("button", { name: /Truck 4 · Test Driver/ }).count(), 0);
    await management.getByRole("combobox", { name: /^Status/ }).selectOption("stop");
    await management.getByRole("button", { name: /Truck 4 · Test Driver/ }).click();
    await management.screenshot({ path: "/tmp/five-point-inspection-review/management-report.png", fullPage: true });
    await page.getByRole("button", { name: "Start another inspection", exact: true }).click();
    assert.equal(await page.getByRole("combobox", { name: /Truck for this inspection/ }).inputValue(), "", "each new inspection asks for its truck");
    await page.getByRole("combobox", { name: /Truck for this inspection/ }).selectOption("Truck 8");
    await page.getByLabel("Your name", { exact: true }).fill("Test Driver Two");
    await page.getByLabel("Odometer · miles").fill("125050");
    await page.getByRole("button", { name: "Start inspection" }).click();
    for (let step = 1; step <= 5; step++) {
      if (step === 4) await page.getByRole("button", { name: "Truck fullness Empty", exact: true }).click();
      if (step === 3) await page.getByRole("button", { name: "Fuel tank Full", exact: true }).click();
      await page.waitForTimeout(500);
      await page.getByRole("button", { name: step === 5 ? "✓ Good — finish checks" : "✓ Good — next check", exact: true }).click();
    }
    assert.equal(await page.getByRole("radio", { name: "Safe to operate — problem reported", exact: true }).isDisabled(), true);
    await page.getByRole("radio", { name: "No problems", exact: true }).check();
    await page.getByRole("button", { name: "Review report" }).click();
    await page.getByLabel("Your initials", { exact: true }).fill("TT");
    await page.setViewportSize({ width: 320, height: 640 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.getByRole("button", { name: "Send to OpsCenter", exact: true }).click();
    await page.getByRole("heading", { name: "✓ No problems reported", exact: true }).waitFor();
    const afterClear = await (await manager.request.get(`${base}/api/fleet-inspections?date=${inspectionDate()}`)).json();
    assert.equal(afterClear.reports.length, 2);
    assert.equal(afterClear.reports.find((r: {status:string}) => r.status === "clear").loadLevel, "Empty");
    assert.equal(afterClear.reports.find((r: {status:string}) => r.status === "clear").fuel, "Full");
    assert.equal(afterClear.reports.find((r: {status:string}) => r.status === "clear").truck, "Truck 8");
    assert.equal(afterClear.reports.find((r: {status:string}) => r.status === "clear").deviceId, connected.device.deviceId);
    assert.deepEqual(afterClear.reports.find((r: {requestId:string}) => r.requestId === saved.reports[0].requestId), saved.reports[0], "switching trucks must preserve the original report");
    await management.getByRole("button", { name: "Refresh reports" }).click();
    await management.getByRole("combobox", { name: /^Status/ }).selectOption("clear");
    await management.getByRole("button", { name: /Truck 8 · Test Driver Two/ }).click();
    await management.getByRole("region", { name: "Selected inspection report" }).getByRole("heading", { name: "Truck 8", exact: true }).waitFor();
    assert.equal(afterClear.reports.filter((r: {status:string}) => r.status === "stop").length, 1, "a clear report cannot erase the original stop report");
    await manager.request.post(`${base}/api/fleet-inspections`, { data: { action: "revoke", deviceId: saved.devices[0].deviceId } });
    assert.equal((await (await mobile.request.get(`${base}/api/truck-inspection`)).json()).device, null);
    assert.equal((await mobile.request.get(`${base}/api/truck-inspection?requestId=${saved.reports[0].requestId}`)).status(), 401);
    assert.deepEqual(errors, []);
    console.log("Browser acceptance passed: required independent truck fullness and fuel tank, preserved levels on reload and receipt, per-inspection truck selection, same phone with two trucks, immutable original report, required truck and invalid truck rejection, no crew directory, Figma mobile layout, double-tap guard, required fuel, operating decision reset on edit, stop receipt, status filters, five checks, problem note/photo, offline draft reload, lost acknowledgement recovery, duplicate safety, report read-back, revoked device and management isolation.");
  } finally {
    await browser.close();
    server.kill("SIGTERM");
    await new Promise<void>(resolve => { if (server.exitCode !== null) resolve(); else server.once("exit", () => resolve()); });
    fs.closeSync(output);
    for (const item of generatedFiles) fs.writeFileSync(item.file, item.content);
    fs.rmSync(state, { recursive: true, force: true });
  }
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
