import assert from 'node:assert/strict';
import { browseLeads, defaultLeadFilters, leadPhoneHref } from '../desktop-ui/lib/lead-browser';
import type { Lead } from '../desktop-ui/lib/commercial-contract';

const lead = (id: string, extra: Partial<Lead> = {}): Lead => ({ id, version: '1', customer: `Customer ${id}`, phone: '(225) 555-0123', territory: 'Baton Rouge', intent: 'Sofa removal', quotedValue: null, status: 'lost', reason: '', note: '', contacted: false, calledAt: '2026-09-01T12:00:00Z', updatedAt: '', source: 'SearchKings', sourceUrl: '', appointmentId: null, jk: null, completed: false, revenue: null, ...extra });
const rows = [lead('lost'), lead('recent', { status: 'needs_follow_up', calledAt: '2026-09-15T12:00:00Z', quotedValue: 200, contacted: true, note: 'Call after lunch', territory: 'Northshore' }), lead('booked', { status: 'booked', appointmentId: '123', jk: 'JK123' }), lead('recovered', { status: 'recovered' }), lead('unqualified', { status: 'unqualified' })];
assert.deepEqual(browseLeads(rows, defaultLeadFilters).rows.map(row => row.id), ['recent', 'lost']);
assert.equal(browseLeads(rows, { ...defaultLeadFilters, query: '2255550123' }).total, 2, 'Unformatted phone matches formatted calls');
assert.equal(browseLeads(rows, { ...defaultLeadFilters, query: '(225) 555-0123' }).total, 2);
assert.equal(browseLeads(rows, { ...defaultLeadFilters, query: 'lunch', territory: 'Northshore', contact: 'contacted' }).total, 1, 'Search notes and combine filters');
assert.equal(browseLeads(rows, { ...defaultLeadFilters, query: 'lunch', contact: 'uncontacted' }).total, 0);
assert.deepEqual(browseLeads(rows, { ...defaultLeadFilters, queue: 'booked' }).rows.map(row => row.id), ['booked', 'recovered']);
assert.equal(browseLeads(rows, { ...defaultLeadFilters, queue: 'all' }).total, 5);
assert.equal(browseLeads(rows, { ...defaultLeadFilters, order: 'priority' }).rows[0].id, 'lost');
assert.equal(browseLeads(rows, { ...defaultLeadFilters, order: 'value' }).rows[0].id, 'recent', 'Missing quotes sort after known values');
assert.equal(browseLeads(rows, { ...defaultLeadFilters, order: 'oldest' }).rows[0].id, 'lost');
const many = Array.from({ length: 23 }, (_, i) => lead(String(i)));
const first = browseLeads(many, defaultLeadFilters);
const second = browseLeads(many, defaultLeadFilters, 2);
assert.equal(first.rows.length, 10);
assert.equal(second.start, 11);
assert.equal(new Set([...first.rows, ...second.rows].map(row => row.id)).size, 20, 'Pages do not repeat leads');
const last = browseLeads(many, defaultLeadFilters, 99);
assert.deepEqual([last.page, last.start, last.end, last.rows.length], [3, 21, 23, 3]);
assert.equal(browseLeads(many.slice(0, 3), defaultLeadFilters, 3).page, 1, 'Live removals clamp a stale page');
assert.deepEqual([browseLeads([], defaultLeadFilters).start, browseLeads([], defaultLeadFilters).end], [0, 0]);
assert.equal(leadPhoneHref('+1 (225) 555-0123'), 'tel:+12255550123');
assert.equal(leadPhoneHref('(225) 555-0123'), 'tel:+12255550123');
assert.equal(leadPhoneHref(''), undefined);
console.log('Lead browsing: queues, combined search, phones, sorting, pagination and live shrink passed.');
