import assert from 'node:assert/strict';
import { isDesktopWriteOriginAllowed } from '../lib/desktop-request-origin';
import { classifyCloseoutFailure } from '../lib/junkware-job-closeout';
const request = (headers: Record<string, string>, url = 'http://127.0.0.1:3000/api/desktop/finance') => new Request(url, { method: 'POST', headers });
const proxy = { 'x-forwarded-host': 'ops.example.invalid', 'x-forwarded-proto': 'https', host: '127.0.0.1:3000', origin: 'https://ops.example.invalid', 'sec-fetch-site': 'same-origin' };
assert.equal(isDesktopWriteOriginAllowed(request(proxy)), true, 'Proxy public Origin must match forwarded HTTPS host, not the loopback upstream');
assert.equal(isDesktopWriteOriginAllowed(request({ ...proxy, origin: 'https://attacker.invalid' })), false);
assert.equal(isDesktopWriteOriginAllowed(request({ ...proxy, origin: 'https://sibling.example.invalid', 'sec-fetch-site': 'same-site' })), false);
assert.equal(isDesktopWriteOriginAllowed(request({ ...proxy, origin: 'http://ops.example.invalid' })), false, 'Wrong browser scheme stays cross-origin');
assert.equal(isDesktopWriteOriginAllowed(request({ ...proxy, 'sec-fetch-site': 'cross-site' })), false);
assert.equal(isDesktopWriteOriginAllowed(request({ ...proxy, origin: 'null' })), false);
assert.equal(isDesktopWriteOriginAllowed(request({ origin: 'http://127.0.0.1:3000' })), true);
assert.equal(isDesktopWriteOriginAllowed(request({ origin: 'http://127.0.0.1:3001' })), false);
assert.equal(isDesktopWriteOriginAllowed(request({})), true, 'Authenticated internal handler requests remain compatible');
assert.equal(isDesktopWriteOriginAllowed(request({ 'sec-fetch-site': 'cross-site' })), false, 'No-Origin cross-site requests are still rejected');
assert.equal(classifyCloseoutFailure({ stderr: JSON.stringify({ stage: 'preflight', code: 'source_version_conflict', error: 'Source changed' }) }).stage, 'preflight');
assert.equal(classifyCloseoutFailure({ stderr: JSON.stringify({ stage: 'uncertain', error: 'Lost verification after save' }) }).stage, 'uncertain');
assert.equal(classifyCloseoutFailure(new Error('Child timed out')).stage, 'uncertain');
console.log('Desktop proxy origin passed: forwarded HTTPS public host, local preview, wrong origins/schemes/ports, cross-site rejection, internal handlers, and preflight versus uncertain closeout errors.');
