import assert from 'node:assert/strict';
import {correctedCrewPay} from '../lib/corrected-crew-pay';
import type {HoursWeek,HoursDay} from '../desktop-ui/lib/krewe-hours-contract';
const day=(date:string,hours:number,extra:Partial<HoursDay>={}):HoursDay=>({date,hours,regular:hours,overtime:0,clockIn:'8:00 AM',clockOut:'4:00 PM',corrected:false,status:'Recorded',role:'Crew',truck:'Truck 2',jobs:0,jobRevenueWorked:0,...extra});
const week:HoursWeek={start:'2026-08-31',end:'2026-09-06',total:45.22,regular:40,overtime:5.22,incomplete:false,days:[day('2026-08-31',11.6),day('2026-09-01',11.07),day('2026-09-02',0),day('2026-09-03',11.8),day('2026-09-04',0),day('2026-09-05',0),day('2026-09-06',10.75,{corrected:true})]};
const amounts={hours:11.1,regularHours:null,overtimeHours:null,jobs:7,revenue:900,labor:188.7,tips:36.98,bonuses:0,supplemental:0,totalPay:225.68};
const input={date:'2026-09-06',clockIn:'07:15 AM',clockOut:'06:00 PM',hourlyRate:17,corrected:true,isSalary:false,amounts,week,sourcePriorHours:null};
const result=correctedCrewPay(input);
assert.equal(result.amounts.hours,10.75);
assert.equal(result.amounts.regularHours,5.53);
assert.equal(result.amounts.overtimeHours,5.22);
assert.equal(result.amounts.labor,227.12);
assert.equal(result.amounts.totalPay,264.10);
assert.equal(result.issue,'');
assert.equal(amounts.totalPay,225.68,'Published source amounts remain untouched');
assert.equal(correctedCrewPay({...input,corrected:false}).amounts.totalPay,225.68,'No correction means published pay');
assert.equal(correctedCrewPay({...input,week:{...week,days:week.days.map((d,i)=>i===1?{...d,hours:null,status:'No Record'}:d)}}).amounts.totalPay,null,'Missing prior shifts are not zero');
assert.equal(correctedCrewPay({...input,week:undefined,sourcePriorHours:34.47}).amounts.totalPay,264.1,'Explicit prior hours remain a supported source');
assert.equal(correctedCrewPay({...input,week:undefined}).amounts.hours,10.75,'Corrected hours survive incomplete pay evidence');
assert.equal(correctedCrewPay({...input,amounts:{...amounts,tips:null}}).amounts.totalPay,null,'Missing pay components are not zero');
assert.equal(correctedCrewPay({...input,isSalary:true}).amounts.totalPay,225.68,'Clock edits do not manufacture hourly salary earnings');
const earlier={...week,days:week.days.map((d,i)=>i===0?{...d,corrected:true,hours:8}:d)};
assert.equal(correctedCrewPay({...input,corrected:false,week:earlier}).amounts.overtimeHours,1.97,'Earlier corrections adjust overtime on a later unedited day');
const missingEarlier={...earlier,days:earlier.days.map((d,i)=>i===1?{...d,hours:null,status:'No Record' as const}:d)};
assert.equal(correctedCrewPay({...input,corrected:false,week:missingEarlier,sourcePriorHours:34.47}).amounts.totalPay,null,'Stale published prior hours cannot override an earlier correction');
assert.equal(correctedCrewPay({...input,clockOut:'05:00 AM'}).amounts.totalPay,null);
assert.equal(correctedCrewPay({...input,week:{...week,days:week.days.map(d=>({...d,corrected:false,hours:0}))}}).amounts.totalPay,219.73,'A known zero-hour week remains straight-time');
console.log('Corrected pay passed: weekly overtime, later-day impact, source preservation, missing history/components, salary and invalid time.');
assert.match(correctedCrewPay({...input,corrected:false,week:missingEarlier}).issue,/correction on 2026-08-31/, 'Later-day warnings identify the actual correction date');
