import assert from 'node:assert/strict';
import { reconcileFuel } from '../lib/fuel-reconciliation';
import type { TruckExpense } from '../lib/truck-expense-notifications';
import type { WexFuelTransaction, WexFuelFinanceData } from '../lib/wex-fuel';
const date = '2026-09-15';
const report: TruckExpense = { id: 'a'.repeat(32), date, market: '477', truck: 'Truck# 7', kind: 'fuel', transactionAt: `${date}T09:05:00-05:00`, location: 'Shell', receipt: 'T1', amount: 75.12, notify: true };
const purchase: WexFuelTransaction = { transactionId: 'w1', transactionDate: date, transactionTime: '09:00:00', postedDate: '2026-09-17', truck: 'Truck 7', driver: 'Test', driverPromptId: '', cardLastFive: '', units: 20, unitOfMeasure: 'GA', gallons: 20, unitCost: 3.756, totalFuelCost: 75.12, totalNonFuelCost: 0, netCost: 75.12, product: '001', productDescription: 'Fuel', merchant: 'Shell 123', city: '', state: '', postalCode: '', odometer: null, ticketNumber: 'T1', status: 'posted' };
const source = (transactions: WexFuelTransaction[]): WexFuelFinanceData => ({ available: true, status: 'available', importedAt: '2026-09-17T15:00:00Z', sourceFileModifiedAt: '2026-09-17T15:00:00Z', coverageFrom: date, coverageThrough: date, transactionCount: transactions.length, selectedDate: { count: transactions.length, gallons: 0, netCost: 0 }, month: { count: transactions.length, gallons: 0, netCost: 0 }, transactions });
const run = (w = [purchase], r = [report]) => reconcileFuel(date, source(w), r);
assert.equal(run().rows[0].status, 'matched', 'match purchase date, not delayed posting date');
assert.equal(run().rows.length, 1, 'a matched expense appears once');
assert.equal(run([{ ...purchase, totalFuelCost: 80, netCost: 80 }]).rows[0].difference, 4.88);
assert.equal(run([{ ...purchase, totalFuelCost: 80, netCost: 80 }]).rows[0].status, 'amount_difference');
assert.equal(run([{ ...purchase, ticketNumber: '', transactionTime: '09:00 AM' }]).matchedCount, 1, 'merchant and nearby time support a match');
assert.equal(run([{ ...purchase, ticketNumber: '', merchant: 'Unrelated station' }]).matchedCount, 0, 'same amount alone cannot match');
assert.equal(run([{ ...purchase, truck: 'Truck 17' }]).matchedCount, 0, 'truck identity is exact');
assert.equal(run([{ ...purchase, truck: 'Asset 7 unknown' }]).matchedCount, 0, 'unknown asset labels do not guess a truck');
assert.equal(run([{ ...purchase, ticketNumber: '', transactionTime: '13:00:00' }]).matchedCount, 0, 'same merchant at another time does not match');
assert.equal(run([purchase, { ...purchase, transactionId: 'w2' }]).matchedCount, 0, 'two purchases cannot consume one report');
assert.ok(run([purchase, { ...purchase, transactionId: 'w2' }]).rows.every(row => row.status === 'ambiguous'));
assert.equal(run([purchase], [report, { ...report, id: 'b'.repeat(32) }]).matchedCount, 0, 'duplicate reports remain for review');
assert.equal(run([], [report, { ...report, id: 'b'.repeat(32), market: '352' }]).reportedTotal, null, 'repeated observations cannot inflate the reported total');
assert.ok(run([], [report, { ...report, id: 'b'.repeat(32), market: '352' }]).rows.every(row => row.status === 'ambiguous'));
assert.equal(run([], [report]).rows[0].status, 'awaiting_wex');
assert.equal(run([purchase], []).rows[0].status, 'wex_only');
assert.equal(run([purchase], [{ ...report, kind: 'dump' }]).reportedTotal, 0, 'dump expenses cannot match fuel');
assert.equal(run([{ ...purchase, totalNonFuelCost: 10, netCost: 85.12 }]).rows[0].status, 'matched', 'non-fuel charges do not inflate the fuel comparison');
assert.equal(run([{ ...purchase, totalFuelCost: null, totalNonFuelCost: 10, netCost: 85.12 }]).rows[0].status, 'ambiguous', 'unknown fuel portion stays unresolved');
assert.equal(reconcileFuel(date, { ...source([]), available: false, status: 'missing' }, [report]).wexFuelTotal, null);
assert.equal(run().reportedTotal, 75.12);
assert.equal(run().wexFuelTotal, 75.12);
console.log('Fuel reconciliation tests passed.');
