import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {trackedGeofenceVisits} from '../lib/linxup-geofence-alerts';
import {projectVerifiedExpenseUnloadEvents,runUnloadCostAgent} from '../lib/unload-cost-agent';
import {defaultDumpFeePolicy,readDumpExpenses} from '../lib/dump-expenses';
import {readTruckExpenses,readOperationalTruckExpenses,truckExpenseTimelineAlerts,mergeTruckExpenseAlerts,type TruckExpense} from '../lib/truck-expense-notifications';
import {readExpenseUnloadLinks,withoutDuplicateExpenseUnloads} from '../lib/expense-unload-links';
import {deriveTruckLoadStatus,type TruckLoadEvent} from '../lib/truck-load-status';
import {canonicalDumpLocation} from '../lib/dump-expense-identity';
const date='2026-09-15',at=(clock:string)=>`${date}T${clock}:00-05:00`,now=Date.parse(at('23:59'));
const position=(clock:string,name:string)=>({truck_number:'4',occurred_at:at(clock),geofence_name:name});
const visits=trackedGeofenceVisits(date,[position('13:49','Gentilly'),position('14:03','Gentilly'),position('14:15','Warehouse')],[],now);
const actual:TruckExpense={id:'a'.repeat(32),date,market:'352',truck:'Truck# 4',kind:'dump',transactionAt:at('14:00'),location:'Gentillt',receipt:'',amount:44,notify:false};
const before=runUnloadCostAgent(date,visits,[],defaultDumpFeePolicy,now);
assert.equal(before.records.length,1);assert.equal(before.unloads.length,1);assert.equal(before.total,44);
const after=runUnloadCostAgent(date,[...visits,...visits],[actual],defaultDumpFeePolicy,now);
assert.equal(after.records.length,1);assert.equal(after.records[0].status,'actual');assert.equal(after.records[0].location,'Gentilly');
assert.deepEqual(after.unloads,before.unloads,'Actual receipt cannot move/repeat physical unload');
assert.equal(after.records[0].id,before.records[0].id);
assert.equal(projectVerifiedExpenseUnloadEvents(date,[actual],after.records,[]).length,0,'A matched actual cannot create a second unload');
const unmatched=runUnloadCostAgent(date,[],[actual],defaultDumpFeePolicy,now);
const expenseUnloads=projectVerifiedExpenseUnloadEvents(date,[actual],unmatched.records,[
  {appointmentId:'before',truck:'Truck# 4',completedAt:at('13:30')},
  {appointmentId:'after',truck:'Truck# 4',completedAt:at('14:30')},
]);
assert.equal(expenseUnloads.length,1,'A verified unmatched dump expense establishes one unload');
assert.equal(expenseUnloads[0].occurredAt,new Date(actual.transactionAt).toISOString());
assert.deepEqual(expenseUnloads[0].coveredAppointmentIds,['before'],'Only jobs completed before the expense are covered');
const prePickup:TruckLoadEvent={...expenseUnloads[0],eventId:'pre-pickup',kind:'job_closeout',loadFraction:.5,occurredAt:new Date(at('13:30')).toISOString(),appointmentId:'before'};
const postPickup:TruckLoadEvent={...expenseUnloads[0],eventId:'post-pickup',kind:'job_closeout',loadFraction:.25,occurredAt:new Date(at('14:30')).toISOString(),appointmentId:'after'};
assert.equal(deriveTruckLoadStatus(date,'Truck# 4',[prePickup,...expenseUnloads,postPickup]).currentLoadFraction,.25,'The verified expense clears earlier work without erasing later pickups');
assert.equal(projectVerifiedExpenseUnloadEvents(date,[{...actual,reconciliationNote:'review'}],unmatched.records,[]).length,0,'An unresolved expense cannot reset load');
assert.equal(projectVerifiedExpenseUnloadEvents(date,[actual],unmatched.records,[],new Set([actual.id])).length,0,'An explicitly linked saved reset is not duplicated');
assert.equal(canonicalDumpLocation('Gentility'),'Gentilly');
const pickup:TruckLoadEvent={...after.unloads[0],eventId:'later-pickup',kind:'job_closeout',loadFraction:.25,occurredAt:new Date(at('15:00')).toISOString(),appointmentId:'123'};
assert.equal(deriveTruckLoadStatus(date,'Truck# 4',[...after.unloads,pickup]).currentLoadFraction,.25,'Late cost reconciliation preserves later pickup');
const competing=runUnloadCostAgent(date,visits,[actual,{...actual,id:'b'.repeat(32),transactionAt:at('17:00')}],defaultDumpFeePolicy,now);
assert.equal(competing.total,null);assert.equal(competing.records.length,3);assert.ok(competing.records.every(row=>row.reconciliationNote),'Two actuals competing for one visit require review');
assert.equal(runUnloadCostAgent(date,visits,[{...actual,date:'2026-09-16',transactionAt:'2026-09-16T14:00:00-05:00'}],defaultDumpFeePolicy,Date.parse('2026-09-17T00:00:00Z')).records[0].status,'assumed','Unrelated later-day actual cannot replace a visit');
const bothVisits=[...visits,...visits.map(visit=>({...visit,id:`truck8:${visit.id}`,truck:'Truck 8',entryIds:visit.entryIds.map(id=>`truck8:${id}`)}))];
const differentTrucks=[{...actual,receipt:'R1'},{...actual,id:'8'.repeat(32),truck:'Truck# 8',receipt:'R2'}];
const independent=runUnloadCostAgent(date,bothVisits,differentTrucks,defaultDumpFeePolicy,now);
assert.equal(independent.records.length,2);assert.equal(independent.unloads.length,2);assert.equal(independent.total,88,'Simultaneous equal-value costs on different trucks both remain');
const wrongTruck=runUnloadCostAgent(date,bothVisits,[actual,{...actual,id:'b'.repeat(32)}],defaultDumpFeePolicy,now);
assert.equal(wrongTruck.records.filter(row=>row.status==='assumed').length,2);assert.equal(wrongTruck.total,null,'Two receipts on one recorded truck do not cancel the other truck assumption');
assert.ok(wrongTruck.records.filter(row=>row.status==='actual').every(row=>row.truck==='Truck 4'),'GPS co-location cannot reassign recorded expense ownership');
const sameReceipt=differentTrucks.map(row=>({...row,receipt:'SAME-RECEIPT'}));
const ownership=runUnloadCostAgent(date,bothVisits,sameReceipt,defaultDumpFeePolicy,now);
assert.equal(ownership.actualTotal,null);assert.equal(ownership.total,null);assert.equal(ownership.records.filter(row=>row.status==='assumed').length,2);assert.ok(ownership.records.every(row=>row.reconciliationNote?.includes('ownership') || row.reconciliationNote?.includes('competing')));
assert.ok(sameReceipt.every(row=>!row.reconciliationNote),'Source expense records remain intact');
const twoRows=[['entered','09:02'],['exited','09:10'],['entered','11:01'],['exited','11:08']].map(([type,time])=>({alert_type:`geofence_${type}`,occurred_at:at(time),geofence_name:'Stranco',truck_number:'8'}));
const twoVisits=trackedGeofenceVisits(date,[],twoRows,now);
const twoActuals=[{...actual,id:'1'.repeat(32),truck:'Truck# 8',transactionAt:at('09:09'),location:'Stranco',amount:85},{...actual,id:'2'.repeat(32),truck:'Truck# 8',transactionAt:at('11:07'),location:'Stranco',amount:92.65}];
const returns=runUnloadCostAgent(date,twoVisits,twoActuals,defaultDumpFeePolicy,now);
assert.equal(returns.records.length,2);assert.equal(returns.unloads.length,2);assert.equal(returns.actualTotal,177.65);assert.equal(returns.assumedTotal,0,'Each actual replaces its own repeated visit minimum');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'unload-cost-agent-')),original=process.env.OPSCENTER_DATA_DIR;
process.env.OPSCENTER_DATA_DIR=root;
const write=(relative:string,value:unknown)=>{const file=path.join(root,relative);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value));};
const snapshot=(market:string,amount:string,entries:TruckExpense[])=>write(`history/junkware/expenses/${date}/${market}/4.json`,{date,market,truck:'Truck# 4',verified:true,observedAt:at('14:23'),signature:[amount,'--'],entries:entries.map(entry=>({...entry,market}))});
try {
  write(`history/linxup/geofence_positions/${date}.json`,{date,observations:[position('13:49','Gentilly'),position('14:03','Gentilly'),position('14:15','Warehouse')]});
  snapshot('352','$34.34',[actual]);snapshot('484','$9.66',[{...actual,id:'b'.repeat(32)}]);
  assert.equal(readTruckExpenses(date).length,2,'Raw source/notification identities stay intact');
  const canonical=readOperationalTruckExpenses(date);assert.equal(canonical.length,1);assert.equal(canonical[0].amount,44);assert.equal(canonical[0].location,'Gentilly');assert.equal(canonical[0].sourceExpenseIds?.length,2);
  const summary=readDumpExpenses(date,now);assert.equal(summary.actualTotal,44);assert.equal(summary.assumedTotal,0);assert.equal(summary.records.length,1);
  write('integrations/whatsapp-crew-expenses/transactions-completed/fixture.json',{stage:'slack_sent',record:{date,kind:'dump',messageId:'wamid.fixture',truck:'Truck 4',cost:44,location:'Gentillt',reportedAt:actual.transactionAt}});
  const expenseReset:TruckLoadEvent={...after.unloads[0],eventId:'yard-reset:expense:wamid-fixture',recordedBy:'Verified OpsBot dump expense',occurredAt:new Date(at('17:00')).toISOString()};
  const retained=withoutDuplicateExpenseUnloads([expenseReset,pickup],summary.records,readExpenseUnloadLinks(date,canonical));
  assert.deepEqual(retained,[pickup],'Explicitly linked delayed receipt reset is suppressed in read projection');
  assert.equal(deriveTruckLoadStatus(date,'Truck# 4',[...summary.unloads,...retained]).currentLoadFraction,.25);
  assert.equal(withoutDuplicateExpenseUnloads([{...expenseReset,recordedBy:'Dispatcher verified unload'}],summary.records,readExpenseUnloadLinks(date,canonical)).length,1,'Manual unload always remains');
  fs.unlinkSync(path.join(root,'integrations/whatsapp-crew-expenses/transactions-completed/fixture.json'));
  write('integrations/whatsapp-crew-expenses/transactions-processing/fixture.json',{stage:'junkware_verified',record:{date,kind:'dump',messageId:'wamid.fixture',truck:'Truck 4',cost:44,location:'Gentillt',reportedAt:actual.transactionAt}});
  assert.equal(withoutDuplicateExpenseUnloads([expenseReset],summary.records,readExpenseUnloadLinks(date,canonical)).length,0,'Verified source links do not depend on Slack delivery');
  const alerts=truckExpenseTimelineAlerts(date);assert.equal(alerts.length,1);assert.equal(alerts[0].facts.find(row=>row.label==='Location')?.value,'Gentilly');
  const rawAlerts=[{...alerts[0],id:'slack1',eventFingerprint:`truck_expense:${date}:${actual.id}`},{...alerts[0],id:'slack2',eventFingerprint:`truck_expense:${date}:${'b'.repeat(32)}`}];
  assert.equal(mergeTruckExpenseAlerts(rawAlerts,alerts).length,1,'Source fingerprint aliases replace both existing duplicate cards');
  snapshot('352','$40.00',[{...actual,amount:50}]);snapshot('484','$10.00',[{...actual,id:'b'.repeat(32),amount:50}]);
  assert.equal(readOperationalTruckExpenses(date)[0].id,canonical[0].id,'Source amount correction preserves physical identity');
  assert.equal(readDumpExpenses(date,now).actualTotal,50);
  snapshot('484','$9.66',[{...actual,id:'b'.repeat(32),amount:50}]);
  assert.equal(readOperationalTruckExpenses(date).length,2);assert.equal(readDumpExpenses(date,now).actualTotal,null,'Unproved duplicates cannot inflate Actual headline');assert.equal(readDumpExpenses(date,now).total,null,'Unproved allocation sum cannot collapse or double certain cost');
  snapshot('352','$88.00',[actual,{...actual,id:'c'.repeat(32)}]);snapshot('484','--',[{...actual,id:'b'.repeat(32)},{...actual,id:'d'.repeat(32)}]);
  assert.equal(readOperationalTruckExpenses(date).length,4,'Same-market repeated physical rows remain distinct for review');
  snapshot('352','--',[actual]);snapshot('484','$44.00',[{...actual,id:'b'.repeat(32)}]);
  assert.equal(readOperationalTruckExpenses(date).length,1,'Known -- marker is zero allocation');
  snapshot('352','unknown',[actual]);assert.equal(readOperationalTruckExpenses(date).length,2,'Arbitrary missing text never means zero');
  for(const market of ['352','484'])write(`history/junkware/expenses/${date}/${market}/4.json`,{date,market,truck:'Truck# 4',verified:true,signature:['--',market==='352'?'--':'$93.52'],entries:[{...actual,id:(market==='352'?'e':'f').repeat(32),market,kind:'fuel',location:'Exxon',amount:93.52}]});
  assert.equal(readTruckExpenses(date).length,2);assert.equal(readOperationalTruckExpenses(date).length,1,'Proved full-table fuel market mirrors count once operationally');
} finally {if(original===undefined)delete process.env.OPSCENTER_DATA_DIR;else process.env.OPSCENTER_DATA_DIR=original;fs.rmSync(root,{recursive:true,force:true});}
console.log('Unload/cost agent checks passed: V3 visits, one reset, late actuals, ambiguous matching, allocation proof, canonical labels, aliases, corrections and source isolation.');
