import assert from 'node:assert/strict';
import { crewAssignedDay } from '../lib/crew-assigned-day';
import type { CrewPhone } from '../lib/crew-phone';

const date='2026-09-22',now=Date.parse(`${date}T18:00:00Z`);
const phone={deviceId:'test-phone',truck:'Truck 1'} as CrewPhone;
const row=(id:string,truck='Truck# 1',status='Confirmed')=>({appt_id:id,job_id:`JK${id}`,truck,job_status:status,customer_name:`Customer ${id}`,address:`${id} Example Street`,appointment_time:'09:00 AM - 10:00 AM'});
let snapshot={date,scrapedAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString(),updatedAtMs:now,freshnessAtMs:now,appointments:[row('100'),row('101'),row('102','Truck 2'),row('103','Truck 1','Completed')],cancelled:[row('104','Truck 1','Cancelled')]};
const overrides=new Map();
const deps={snapshot:()=>snapshot,rows:()=>[],overrides:()=>overrides,dispatch:()=>({truck:'Truck 1',version:1,current:{assignmentId:'released-100',appointmentId:'100',date,releasedAt:new Date(now).toISOString()},queued:null})};
const result=crewAssignedDay(phone,date,deps,now);
assert.equal(result.state,'assigned');
assert.deepEqual(result.jobs?.map(job=>job.appointmentId),['100','101','103'],'All truck jobs are visible without a separate release, including completed work');
assert.equal(result.job?.assignmentId,'released-100');
assert.equal(result.jobs?.find(job=>job.appointmentId==='101')?.assignmentId,undefined,'Browsing does not invent closeout authority');
assert.equal(JSON.stringify(result).includes('Customer 102'),false,'Other truck customer data never leaves the server');
assert.equal(JSON.stringify(result).includes('Customer 104'),false,'Canceled appointments are excluded');
overrides.set('appt:101',{truck:'Truck 2',junkwareSyncStatus:'pending'});
assert.deepEqual(crewAssignedDay(phone,date,deps,now).jobs?.map(job=>job.appointmentId),['100','103'],'A pending move is withheld');
overrides.clear();
snapshot={...snapshot,appointments:[...snapshot.appointments,row('101')]};
assert.equal(crewAssignedDay(phone,date,deps,now).jobs?.some(job=>job.appointmentId==='101'),false,'Ambiguous identities are withheld');
snapshot={...snapshot,freshnessAtMs:now-121_000};
assert.equal(crewAssignedDay(phone,date,deps,now).state,'unavailable','Stale source fails promptly without opening a browser');
snapshot={...snapshot,freshnessAtMs:now+1};
assert.equal(crewAssignedDay(phone,date,deps,now).state,'unavailable');
snapshot={...snapshot,freshnessAtMs:now,appointments:[row('101')],cancelled:[]};
assert.equal(crewAssignedDay(phone,date,deps,now).jobs?.length,1,'An old or missing current release does not hide scheduled jobs');
snapshot={...snapshot,appointments:[{...row('103','Truck 1','Completed'),appointment_type:'Estimate',closeout:{total:'568.00'},appointment_notes:['Other: Training only, no discount: internal test (9/22/2026)']} as ReturnType<typeof row>]};
const closed=crewAssignedDay(phone,date,deps,now).jobs![0];
assert.equal(closed.appointmentType,'Estimate');assert.equal(closed.closedTotal,568);
assert.deepEqual(closed.estimateOutcomes,['Other: Training only, no discount: internal test (9/22/2026)']);
snapshot={...snapshot,appointments:[{...snapshot.appointments[0],job_status:'Confirmed'}]};
assert.equal(crewAssignedDay(phone,date,deps,now).jobs![0].closedTotal,undefined,'An open appointment never claims a saved closeout amount');
console.log('PASS: full assigned day, truck isolation, verified feed freshness, pending move exclusion, duplicate identity rejection, and independent closeout authority; no provider calls.');
