import assert from 'node:assert/strict';
import { scheduleTruckVisitGaps, scheduleTruckVisits } from '../lib/schedule-visit-intervals';
import { scheduleBoardJobs, scheduleDisplayTruck, scheduleTimelineBlockMovable, scheduleTruckMismatch, timelinePlacement, timelineRange, timelineWindow, type ScheduleAppointment } from '../desktop-ui/lib/schedule-contract';
import { scheduleTravelLayout } from '../desktop-ui/lib/schedule-travel-layout';
const now=Date.parse('2026-09-14T18:00:00Z');
const location={latitude:30,longitude:-90};
const job={recordId:'2026-09-14:appointment:1',appointmentId:'1',jkNumber:'JK1',truck:'Truck 8',status:'Confirmed',appointmentType:'Job',appointmentStartMinutes:480,appointmentEndMinutes:540,hasScheduledTime:true,location} as ScheduleAppointment;
const ledger=[
  {appointment_id:'1',truck_number:'Truck 8',match_confidence:'confirmed',visit_intervals:[{arrival:'2026-09-14T14:00:00Z',departure:'2026-09-14T15:00:00Z'},{arrival:'2026-09-14T16:00:00Z',departure:'2026-09-14T16:15:00Z'}]},
  {appointment_id:'1',truck_number:'Truck 3',match_confidence:'confirmed',visit_intervals:[{arrival:'2026-09-14T17:00:00Z',departure:null,source_timestamps:['2026-09-14T17:58:00Z']}]},
];
const truck={truck:'Truck 3',...location,lastGpsUpdate:'2026-09-14T18:00:00Z',speed:0,ignition:'ON',routePoints:[0,1,2,3].map(i=>({...location,timestamp:new Date(now-(3-i)*60_000).toISOString()}))};
const original=JSON.stringify({job,ledger,truck});
const visits=scheduleTruckVisits(job,ledger,[truck],[job],now);
const truckVisitGaps=scheduleTruckVisitGaps(visits,[{kind:'geofence',truck:'Truck 8',name:'Gentilly',enteredAt:'2026-09-14T15:20:00Z',resetLocation:'dump'}]);
const shown={...job,truckVisits:visits,truckVisitGaps};
const range=timelineRange([shown],now);
assert.equal(visits.length,3);
assert.deepEqual(truckVisitGaps,[{truck:'Truck 8',departedAt:'2026-09-14T15:00:00.000Z',returnedAt:'2026-09-14T16:00:00.000Z',kind:'dump',facilityName:'Gentilly',facilityEnteredAt:'2026-09-14T15:20:00Z'}]);
const old=timelinePlacement(shown,range,'Truck 8',now)!;
assert.equal(old.start,540,'Recorded arrival replaces the 8 AM booking');
assert.equal(old.segments.length,2,'Separate trips retain the time-away gap');
assert.deepEqual(old.gaps,[{start:600,end:660,kind:'dump',facilityName:'Gentilly'}],'Confirmed dump evidence labels the exact time-away gap');
assert.equal(old.gapSegments[0].width*range.duration,60,'The connector spans departure through return');
assert.equal(old.segments.reduce((sum,p)=>sum+p.width*range.duration,0),75);
const offSite=scheduleTruckVisitGaps(visits,[]);
assert.equal(offSite[0].kind,'off_site','Leave and return without dump evidence stays neutral');
const active=timelinePlacement(shown,range,'Truck 3',now)!;
assert.equal(active.start,720,'Other truck uses its own arrival');
assert.equal(active.end,780,'Active visit grows to now');
assert.equal(timelineWindow(shown,'Truck 3',now+60_000)?.end,781);
assert.equal(timelineWindow(shown,'Truck 9',now),null,'Do not repeat a booked block on unrelated trucks');
assert.equal(scheduleTravelLayout([shown],[],range,'Truck 3',now).placed.length,1);
assert.equal(scheduleTravelLayout([shown],[],range,'Truck 8',now).placed[0].position.segments.length,2);
const reassigned=timelineWindow({...shown,truck:'Truck 9'},'Truck 9',now);
assert.equal(reassigned?.actual,false,'A new assignment remains visible alongside prior physical visits');
assert.equal(reassigned?.start,480,'A new assignment keeps its booked source window');
const stale={...shown,truckVisits:scheduleTruckVisits(job,ledger,[],[job],now)};
assert.equal(timelineWindow(stale,'Truck 3',now)?.end,778,'Unconfirmed departure stops at recorded evidence, not now');
assert.equal(timelineWindow(stale,'Truck 3',now)?.intervals[0].complete,false);
assert.equal(scheduleTruckVisits(job,[...ledger,ledger[0]],[],[job],now).length,3,'Duplicate visits do not inflate time');
for(const changed of [{...ledger[0],appointment_id:'2'},{...ledger[0],match_confidence:'ambiguous'},{...ledger[0],pass_by_only:true}]) assert.equal(scheduleTruckVisits(job,[changed],[],[job],now).length,0);
const instant={...ledger[0],visit_intervals:[{arrival:'2026-09-14T14:00:00Z',departure:null}]};
assert.equal(scheduleTruckVisits(job,[instant],[],[job],now).length,0,'No measured duration retains planned fallback');
const closed={...job,status:'Completed'};
assert.ok(scheduleTruckVisits(closed,ledger,[truck],[closed],now).every(v=>!v.currentUntil),'Closed work cannot keep growing');
const future={...ledger[0],visit_intervals:[{arrival:'2026-09-14T19:00:00Z',departure:'2026-09-14T20:00:00Z'}]};
assert.equal(scheduleTruckVisits(job,[future],[],[job],now).length,0);
assert.equal(timelineWindow({...job,truckVisits:[]},'Truck 8',now)?.actual,false,'Unvisited appointments remain explicitly planned');
const sharedPremises={...job,truck:'Truck 1',truckVisits:visits};
assert.equal(timelineWindow(sharedPremises,'Truck 1',now)?.actual,false,'Unrelated GPS visits cannot hide the Truck 1 assignment');
assert.equal(timelineWindow(sharedPremises,'Truck 3',now)?.actual,true,'Cross-truck GPS evidence remains available outside the assignment lanes');
assert.deepEqual(scheduleBoardJobs([sharedPremises],'Truck 1',now).map(row=>row.appointmentId),['1'],'The booked appointment appears in its assigned Truck 1 lane');
assert.equal(scheduleBoardJobs([sharedPremises],'Truck 3',now).length,0,'A cross-truck GPS visit cannot duplicate the appointment into another schedule lane');
assert.equal(scheduleBoardJobs([sharedPremises],'Truck 8',now).length,0,'Prior GPS history cannot duplicate a reassigned appointment into its old lane');
assert.equal(scheduleTravelLayout(scheduleBoardJobs([sharedPremises],'Truck 3',now),[],range,'Truck 3',now).placed.length,0,'Board layout cannot reintroduce cross-truck visit blocks');
assert.equal(scheduleTimelineBlockMovable(sharedPremises,false),true,'The booked assignment remains draggable');
assert.equal(scheduleTimelineBlockMovable(sharedPremises,true),false,'Recorded GPS history is never draggable');
const completedMismatch={...sharedPremises,status:'Completed',recordedOnsiteTime:{minutes:60,arrival:'2026-09-14T14:00:00Z',departure:'2026-09-14T15:00:00Z',label:'60 min',truck:'Truck 8'}};
assert.equal(scheduleDisplayTruck(completedMismatch),'Truck 8','Completed work defaults to the unique GPS-confirmed truck');
assert.deepEqual(scheduleTruckMismatch(completedMismatch),{gpsTruck:'Truck 8',junkwareTruck:'Truck 1'});
assert.equal(scheduleBoardJobs([completedMismatch],'Truck 1',now).length,0,'A completed mismatch does not remain on the stale JunkWare lane');
assert.deepEqual(scheduleBoardJobs([completedMismatch],'Truck 8',now).map(row=>row.appointmentId),['1'],'The completed appointment appears once on the GPS truck lane');
assert.equal(scheduleTimelineBlockMovable(completedMismatch,true),true,'A completed GPS block can correct its JunkWare assignment or window');
assert.equal(JSON.stringify({job,ledger,truck}),original,'Rendering cannot mutate booking, GPS or visit history');
const shortArrival={...truck,speed:0,ignition:'OFF',routePoints:[{...location,timestamp:'2026-09-14T17:59:01Z',speed:1,ignition:'ON'}]};
const shortLedger=[{...ledger[1],visit_intervals:[{arrival:'2026-09-14T17:59:01Z',departure:null,source_timestamps:['2026-09-14T18:00:00Z']}]}];
const shortActive={...job,truckVisits:scheduleTruckVisits(job,shortLedger,[shortArrival],[job],now+25*60_000)};
assert.equal(timelineWindow(shortActive,'Truck 3',now+25*60_000)?.end,805,'Parking-speed shutdown keeps the actual block growing through the parked reporting interval');
assert.equal(timelineWindow(shortActive,'Truck 3',now+25*60_000)?.intervals[0].complete,false,'An active truck visit never receives the departed checkmark');
console.log('Truck visit blocks passed: per-truck intervals, split trips, active growth, stale stop, assignment changes, duplicates, identity, invalid evidence and unchanged sources.');
