import assert from 'node:assert/strict';
import { groupNearbyHqStops, recordedStopSequence } from '../desktop-ui/lib/schedule-recorded-sequence';
import type { ScheduleAppointment, ScheduleOperationalStop } from '../desktop-ui/lib/schedule-contract';
const hq = (id: string, start: number, end: number, name='NOHQ'): ScheduleOperationalStop => ({id, truck:'Truck 4', name, facility:name, kind:'hq', label:`${name} Visit`, startMinutes:start, endMinutes:end, enteredAt:new Date(Date.UTC(2026,9,2,5,start)).toISOString(), departedAt:new Date(Date.UTC(2026,9,2,5,end)).toISOString(), observedThrough:new Date(Date.UTC(2026,9,2,5,end)).toISOString(), ongoing:false});
const job = (id: string, start: number, end: number): ScheduleAppointment => ({recordId:`2026-10-02:${id}`, jkNumber:id, customerName:'Fixture', status:'Completed', truck:'Truck 4', truckVisits:[{truck:'Truck 4',arrival:new Date(Date.UTC(2026,9,2,5,start)).toISOString(),departure:new Date(Date.UTC(2026,9,2,5,end)).toISOString(),observedThrough:new Date(Date.UTC(2026,9,2,5,end)).toISOString()}]} as ScheduleAppointment);
const first=hq('first',643.4333,644.4667), second=hq('second',660.8833,661.9);
const original=JSON.stringify([first,second]);
const grouped=groupNearbyHqStops([second,first],[],'Truck# 4');
assert.equal(grouped.length,1);
assert.equal(grouped[0].groupedVisits,2);
assert.equal(grouped[0].startMinutes,first.startMinutes);
assert.equal(grouped[0].endMinutes,second.endMinutes);
assert.equal(JSON.stringify([first,second]),original,'Source records are never mutated');
assert.equal(groupNearbyHqStops([first,second],[job('intervening',645,658)],'Truck 4').length,2,'An intervening job preserves both HQ visits');
assert.equal(groupNearbyHqStops([first,hq('later',665,666)],[],'Truck 4').length,2,'Over twenty minutes stays separate');
assert.equal(groupNearbyHqStops([first,hq('other-hq',650,651,'BRHQ')],[],'Truck 4').length,2);
assert.equal(groupNearbyHqStops([first,{...second,truck:'Truck 6'}],[],'Truck 4').length,2);
const dump={...hq('dump',650,655),kind:'dump' as const,name:'Landfill',label:'Dump'};
assert.equal(groupNearbyHqStops([first,dump,second],[],'Truck 4').length,3,'Dump stops prevent HQ grouping');
const sequence=recordedStopSequence([job('before',620,635),job('after',670,680)],[first,dump,second],'Truck 4');
assert.deepEqual(sequence.map(stop=>stop.label),['before · Fixture','NOHQ Visit','Dump','NOHQ Visit','after · Fixture']);
const planned={...job('planned',690,700),truckVisits:[],hasScheduledTime:true,appointmentStartMinutes:690,appointmentEndMinutes:700};
assert.equal(recordedStopSequence([planned],[],'Truck 4').length,0,'Planned windows are not recorded history');
assert.equal(recordedStopSequence([job('before',620,635)],[first],'Truck 6').length,0,'Other trucks do not leak into history');
console.log('Recorded stop sequence passed: job/HQ/dump order, truthful history, and bounded HQ grouping with intervening stops preserved.');
