import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { detectMaintenance, reconcileMaintenance, initialMaintenanceState, maintenanceSnapshot, saveMaintenanceState, recordClientEvent, readClientEvents, verifyClientInteraction, readClientVerifications } from '../lib/maintenance-monitor';
import { diagnoseMaintenance } from '../lib/maintenance-diagnosis';
import { maintenanceAttention } from '../lib/maintenance-attention';
import { maintenanceOperation, validClientEvidence, validReadSnapshot } from '../desktop-ui/lib/maintenance-evidence';
import type { MaintenanceObservation } from '../desktop-ui/lib/maintenance-contract';
const now = Date.parse('2026-09-11T13:00:00Z');
const outage: MaintenanceObservation = { key: 'client-schedule-closeout', title: 'Appointment closeout failure', area: 'Schedule', kind: 'technical', unhealthy: true, evidence: 'POST Appointment closeout: http (HTTP 503)', nextStep: 'Verify closeout.', verificationRequired: true };
async function main() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'maintenance-reliability-'));
  try {
    assert.equal(maintenanceOperation('/api/desktop/schedule/closeout'), 'schedule-closeout');
    assert.equal(maintenanceOperation('/api/desktop/finance'), 'finance');
    assert.equal(maintenanceOperation('/api/desktop/maintenance'), null, 'reporting cannot recursively report itself');
    for (const extra of [{message:'private'}, {url:'private'}, {status:200}, {method:'private'}, {failure:'private'}]) assert.equal(validClientEvidence({category:'schedule',...extra}), false);
    assert.equal(validReadSnapshot('schedule', {date:'2026-09-11',appointments:[],fleet:{trucks:[]}}), true, 'zero appointments can be valid');
    assert.equal(validReadSnapshot('schedule', {date:'2026-09-11'}), false);
    assert.equal(validReadSnapshot('command', '<html>'), false);
    assert.equal(recordClientEvent({category:'schedule-closeout',failure:'http',status:503,method:'POST'}, directory, now), true);
    const event = readClientEvents(directory)['schedule-closeout'];
    const rows = detectMaintenance({ health:{ok:true,status:'healthy',signals:{exceptions:{status:'critical',critical:3,summary:'private'},gpsCoverage:{status:'critical',mappedTrackers:6,reportingTrackers:4}}}, readiness:null,login:true,clientEvents:{'schedule-closeout':event},workflows:{schedule:false,fleet:true} }, now);
    assert(rows.find(r=>r.key==='signal-exceptions')?.unhealthy);
    assert(rows.find(r=>r.key==='signal-gpsCoverage')?.unhealthy);
    assert(rows.find(r=>r.key==='workflow-schedule')?.unhealthy);
    assert.equal(rows.find(r=>r.key==='workflow-fleet')?.unhealthy,false);
    assert(!JSON.stringify(rows).includes('private'));
    assert(rows.find(r=>r.key==='client-schedule-closeout')?.evidence.includes('HTTP 503'));
    const state = initialMaintenanceState();
    reconcileMaintenance(state, [outage], now); reconcileMaintenance(state, [outage], now+60_000);
    const clear = {...outage, unhealthy:false};
    for (let i=2;i<8;i++) reconcileMaintenance(state,[clear],now+i*60_000);
    assert.equal(state.incidents[0].status,'verification-needed','silence cannot clear browser failures');
    assert(verifyClientInteraction('schedule-closeout',now,directory));
    assert.equal(readClientVerifications(directory)['schedule-closeout'],now);
    assert(!verifyClientInteraction('../../escape',now,directory));
    recordClientEvent({category:'schedule-closeout',failure:'http',status:500,method:'POST'}, directory, now+60_000);
    assert(!verifyClientInteraction('schedule-closeout',now,directory),'stale verification is rejected');
    const newer = detectMaintenance({health:null,readiness:null,login:true,clientEvents:readClientEvents(directory),verifications:readClientVerifications(directory)},now+120_000);
    assert(newer.find(r=>r.key==='client-schedule-closeout')?.unhealthy,'new failure cannot inherit old verification');
    for(let i=8;i<11;i++) reconcileMaintenance(state,[{...clear,verified:true}],now+i*60_000);
    assert.equal(state.incidents[0].status,'resolved');
    reconcileMaintenance(state,[outage],now+11*60_000);
    assert.equal(state.incidents[0].verifiedAt,undefined);
    for(let i=12;i<16;i++) reconcileMaintenance(state,[clear],now+i*60_000);
    assert.equal(state.incidents[0].status,'verification-needed');
    saveMaintenanceState(state,directory);
    const snapshot=maintenanceSnapshot(now+16*60_000,directory);
    assert(maintenanceAttention(snapshot).needsAttention);
    assert(maintenanceAttention({...snapshot,incidents:[],aiStatus:'AI unavailable: HTTP 429',fresh:true}).needsAttention,'fresh checks cannot hide AI failure');
    const create = () => {const s=initialMaintenanceState();reconcileMaintenance(s,[outage],now);reconcileMaintenance(s,[outage],now+60_000);return s;};
    let calls=0;
    const success=(async()=>{calls++;return Response.json({status:'completed',usage:{input_tokens:20,output_tokens:20},output:[{content:[{type:'output_text',text:JSON.stringify({summary:'Check failed',likelyCause:'Unknown',nextStep:'Verify the operation',verification:'Read back its outcome'})}]}]});}) as typeof fetch;
    const ai=create(); await diagnoseMaintenance(ai,'mock',()=>{},now+60_000,success,()=>true);
    for(let i=2;i<5;i++)reconcileMaintenance(ai,[{...clear,verified:true}],now+i*60_000);
    for(let i=5;i<7;i++)reconcileMaintenance(ai,[outage],now+i*60_000);
    await diagnoseMaintenance(ai,'mock',()=>{},now+7*60_000,success,()=>true);
    assert.equal(calls,1,'reopening does not re-spend on a recent diagnosis');
    ai.aiStatus='AI unavailable: HTTP 429; monitoring continues'; ai.aiFailureCode=undefined;
    await diagnoseMaintenance(ai,'mock',()=>{},now+8*60_000,success,()=>true);
    assert(ai.aiStatus.includes('unavailable'),'legacy HTTP-only provider failure cannot clear on an idle tick');
    await diagnoseMaintenance(ai,'mock',()=>{},now+2*86_400_000,success,()=>true);
    assert.equal(calls,1,'an unchanged continuously open condition must not create a daily paid refresh');
    const quota=create();let quotaCalls=0;
    const reject=(async()=>{quotaCalls++;return Response.json({error:{code:'insufficient_quota',message:'private raw text'}},{status:429});}) as typeof fetch;
    await diagnoseMaintenance(quota,'mock',()=>{},now+60_000,reject,()=>true);
    assert.equal(quota.aiFailureCode,'insufficient_quota');assert(quota.aiBlocked);
    await diagnoseMaintenance(quota,'mock',()=>{},now+3*86_400_000,reject,()=>true);
    assert.equal(quotaCalls,1,'known exhausted quota must not keep retrying');
    assert(!JSON.stringify(quota).includes('private'));
    const unknown=create();await diagnoseMaintenance(unknown,'mock',()=>{},now+60_000,(async()=>Response.json({error:{code:'unrecognized',message:'private'}},{status:429})) as typeof fetch,()=>true);
    assert.equal(Date.parse(unknown.aiRetryAfter!),now+60_000+21_600_000);
    assert(!unknown.aiBlocked);assert(unknown.aiFailureCode?.includes('reason unavailable'));
    console.log('Maintenance reliability passed: coverage, privacy, persistent failures, stale verification, recurrence deduplication, status honesty, quota stop and ambiguous-429 backoff. Providers mocked.');
  } finally { fs.rmSync(directory,{recursive:true,force:true}); }
}
main().catch(error=>{console.error(error);process.exitCode=1;});
