import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {applyStopOrders,saveStopOrder,StopOrderConflict} from '../lib/desktop-stop-order-store';
import {orderGroups,orderGroupKey,orderSourceKey,compareStops} from '../lib/schedule-stop-order';
import {scheduleRoutePairs,type DesktopAppointment} from '../lib/desktop-schedule';
import {nextTruckStop} from '../lib/schedule-next-stop';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'day-order-'));
process.env.SCHEDULE_STOP_ORDER_DIR=directory;
try {
 const jobs=[1,2,3,4,5].map((id,index)=>({recordId:`2026-10-07:appointment:${id}`,appointmentId:String(id),version:'1',address:'100 Example St',status:index===0?'Completed':index===4?'Canceled':'Confirmed',truck:'Truck 9',appointmentStartMinutes:480+index*60,appointmentEndMinutes:540+index*60,jkNumber:`JK${id}`} as DesktopAppointment));
 const read=()=>applyStopOrders('2026-10-07',jobs);
 const group=orderGroups(read(),'remaining')[0];
 assert.deepEqual(group.map(j=>j.appointmentId),['2','3','4']);
 const ids=[...group].reverse().map(j=>j.recordId);
 const input={date:'2026-10-07',scope:'remaining' as const,groupKey:orderGroupKey(group[0],'remaining'),sourceKey:orderSourceKey(group,'remaining'),ids,actor:'test'};
 saveStopOrder(input,read);
 const result=read();
 assert.deepEqual(orderGroups(result,'remaining')[0].map(j=>j.recordId),ids,'Saved cross-window order survives independent reads');
 assert.deepEqual(result.map(({visitOrder,stopOrder,...job})=>job),jobs,'Source times, trucks, status and identity are unchanged');
 assert.deepEqual(scheduleRoutePairs(result).map(j=>[j.fromJk,j.toJk]),[['JK1','JK4'],['JK4','JK3'],['JK3','JK2']],'Completed work precedes remaining saved route');
 assert.equal(nextTruckStop(result,'Truck 9',true)?.job.recordId,ids[0],'Truck progress follows saved next stop');
 assert.throws(()=>saveStopOrder(input,read),StopOrderConflict,'Concurrent stale writer rejected');
 assert.equal(applyStopOrders('2026-10-08',jobs).some(j=>j.visitOrder!==undefined),false,'Date isolation');
 const changed=jobs.map(j=>j.appointmentId==='4'?{...j,status:'Completed'}:j);
 assert.deepEqual(orderGroups(applyStopOrders(input.date,changed),'remaining')[0].map(j=>j.appointmentId),['3','2'],'Finished stop naturally leaves remaining sequence');
 assert.throws(()=>saveStopOrder({...input,sourceKey:orderSourceKey(group,'remaining')},()=>changed),StopOrderConflict,'Completion while editing invalidates the draft');
 const moved=jobs.map(j=>j.appointmentId==='4'?{...j,truck:'Truck 6'}:j);
 assert.equal(applyStopOrders(input.date,moved).find(j=>j.appointmentId==='4')?.visitOrder,undefined,'Saved rank cannot leak to another truck');
 const incoming={...jobs[1],recordId:'2026-10-07:appointment:new',appointmentId:'new',appointmentStartMinutes:400};
 assert.equal(orderGroups(applyStopOrders(input.date,[...jobs,incoming]),'remaining')[0].at(-1)?.appointmentId,'new','New appointments append without silently reordering saved stops');
 const original=JSON.stringify(jobs);
 [...result].sort(compareStops);
 assert.equal(JSON.stringify(jobs),original);
 const timed=jobs.slice(0,2).map((j,i)=>({...j,status:'Completed',truckVisits:[{truck:'Truck 9',arrival:`2026-10-07T${i===0?'17':'16'}:10:00Z`,departure:null,observedThrough:`2026-10-07T${i===0?'17':'16'}:25:00Z`}]}));
 assert.equal(scheduleRoutePairs(timed)[0].fromJk,'JK2','Recorded chronology precedes old booked times for completed stops');
 console.log('Day stop order passed: persisted cross-window sequence, unchanged source, current progress, completion/reassignment/date isolation, new stops, concurrency, recorded chronology.');
} finally {fs.rmSync(directory,{recursive:true,force:true});delete process.env.SCHEDULE_STOP_ORDER_DIR;}
