import assert from 'node:assert/strict';
import { buildKreweHours } from '../lib/desktop-krewe-hours';
import { payPeriodDates } from '../lib/pay-period';
import { buildPayrollReview, payrollReviewCsv, reviewedPayrollRows } from '../desktop-ui/lib/payroll-review';
import type { CrewAmounts, DesktopCrewMember, DesktopKreweSnapshot } from '../desktop-ui/lib/people-fleet-contract';

const period = payPeriodDates('2026-09-05');
const sources = new Map(period.dates.map((date, index) => [date, { payroll_records: [{ name: 'Sample Crew', hours_worked: index < 5 ? 9 : index >= 7 && index < 11 ? 8 : 0, clock_in: '8:00 AM', clock_out: '5:00 PM' }] }]));
const hours = buildKreweHours('2026-09-05', sources, new Map(), new Date('2026-09-07T12:00:00Z'));
const amounts: CrewAmounts = { hours: 0, regularHours: 0, overtimeHours: 0, jobs: 0, revenue: 0, labor: 0, tips: 0, bonuses: 0, supplemental: 0, totalPay: 0 };
const member: DesktopCrewMember = { ...amounts, id: 'sample crew', name: 'Sample Crew', initials: 'SC', role: 'Driver', truck: '1', working: true, clockIn: '', clockOut: '', hourlyRate: 20, status: '', issue: '', version: 'v1', correction: null,
  days: hours.employees[0].weeks.flatMap(week => week.days.map(day => ({ ...amounts, date: day.date, clockIn: day.clockIn, clockOut: day.clockOut, hours: day.hours, labor: (day.hours || 0) * 20, tips: 5, bonuses: 3, supplemental: 2, totalPay: (day.hours || 0) * 20 + 10, sourceAt: '2026-09-07T11:00:00Z' }))) };
const payroll: DesktopKreweSnapshot = { date: hours.date, view: 'payperiod', start: period.start, end: period.end, sourceUpdatedAt: null, missingDates: [], payrollVisible: true, canWrite: true, members: [member], totals: amounts, callIn: null };
const original = JSON.stringify(payroll);
const [row] = buildPayrollReview(hours, payroll);
assert.equal(row.issues.length, 0);
assert.equal(row.hours, 77); assert.equal(row.regular, 72); assert.equal(row.overtime, 5, 'Overtime is weekly, never an 80-hour period threshold');
assert.deepEqual(row.weeks.map(week => week.hours), [45, 32]);
assert.equal(row.pay.tips, 70); assert.equal(row.pay.bonuses, 42); assert.equal(row.pay.supplemental, 28); assert.equal(row.pay.totalPay, 1680);
const marks = { [row.id]: row.signature };
assert.equal(reviewedPayrollRows([row], marks).length, 1);
const refreshed = structuredClone(payroll); refreshed.members[0].days[0].sourceAt = '2026-09-07T12:00:00Z';
assert.equal(buildPayrollReview({ ...hours, generatedAt: '2026-09-07T13:00:00Z' }, refreshed)[0].signature, row.signature);
refreshed.members[0].days[0].bonuses! += 1; refreshed.members[0].days[0].totalPay! += 1;
assert.equal(reviewedPayrollRows(buildPayrollReview(hours, refreshed), marks).length, 0, 'Changed pay invalidates review');
const bad = structuredClone(payroll);
bad.members[0].days[0].tips = null; bad.members[0].days[1].totalPay! += 10; bad.members[0].days[2].syncStatus = 'pending'; bad.members[0].days[3].hours = 3;
const [flagged] = buildPayrollReview(hours, bad);
assert.equal(flagged.pay.tips, null);
for (const message of ['Pay breakdown incomplete', 'Pay total does not match its components', 'JunkWare correction pending', 'Time and pay records disagree on hours']) assert.ok(flagged.issues.some(issue => issue.message === message), message);
assert.equal(reviewedPayrollRows([flagged], { [flagged.id]: flagged.signature }).length, 0);
const offDay = structuredClone(hours); const offPay = structuredClone(payroll);
offDay.employees[0].weeks[0].days[5].clockIn = ''; offDay.employees[0].weeks[0].days[5].clockOut = 'Not scheduled';
offPay.members[0].days[5] = { ...offPay.members[0].days[5], ...amounts, clockIn: '', clockOut: 'Not scheduled' };
assert.equal(buildPayrollReview(offDay, offPay)[0].issues.length, 0, 'Off-day source labels are not clock evidence');
const fallbackHours = structuredClone(hours); fallbackHours.employees[0].weeks[0].days[0].clockIn = ''; fallbackHours.employees[0].weeks[0].days[0].clockOut = '';
assert.equal(buildPayrollReview(fallbackHours, payroll)[0].issues.length, 0, 'Collected timesheet clocks fill missing summary clocks');
const missingPay = structuredClone(payroll); missingPay.members[0].days.shift();
assert.ok(buildPayrollReview(hours, missingPay)[0].issues.some(issue => issue.message === 'Pay record missing'));
assert.deepEqual(buildPayrollReview(hours, { ...payroll, date: '2026-09-06' }), []);
const options = { start: period.start, end: period.end, retrievedAt: hours.generatedAt, warnings: [], reviewed: true };
assert.throws(() => payrollReviewCsv({ ...options, rows: [flagged] }), /Resolve/);
assert.throws(() => payrollReviewCsv({ ...options, rows: [row], warnings: ['Daily source unavailable'] }), /Resolve/);
const csv = payrollReviewCsv({ ...options, rows: [row] });
assert.ok(csv.startsWith('\uFEFF')); assert.match(csv, /"45.00","32.00","77.00","72.00","5.00"/); assert.match(csv, /Reviewed in this session/);
const draft = payrollReviewCsv({ ...options, reviewed: false, rows: [{ ...flagged, name: '=HYPERLINK("bad")' }], warnings: ['Partial period'] });
assert.ok(draft.includes('"\'=HYPERLINK(""bad"")"')); assert.match(draft, /Draft - not reviewed/); assert.match(draft, /Partial period/); assert.ok(!draft.includes('null'));
assert.equal(JSON.stringify(payroll), original, 'Review never changes pay records');
console.log('Payroll review passed: both weeks, source totals, discrepancies, nulls, correction status, review invalidation, CSV escaping and read-only source preservation.');
