import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { INSPECTION_SECTIONS, inspectionDate, validateTruckInspection } from "../lib/truck-inspection";
import { createInspectionPairing, pairInspectionPhone, connectInspectionPhone, listInspectionDevices, inspectionDevice, submitTruckInspection, findTruckInspection, listTruckInspections, revokeInspectionDevice } from "../lib/truck-inspection-store";
import { inspectionRequestBody } from "../lib/truck-inspection-http";
import { publicAuthRoute } from "../lib/auth";
const directory = fs.mkdtempSync(path.join(os.tmpdir(), "truck-inspection-test-"));
process.env.OPS_TRUCK_INSPECTION_DIR = directory;
const now = new Date("2026-09-15T13:00:00Z");
const valid = () => ({ requestId: randomUUID(), truck: "Truck 4", inspector: "Test inspector", odometer: "123456", fuel: "1/2", loadLevel: "3/4", startedAt: now.toISOString(), answers: INSPECTION_SECTIONS.map(s => ({ id: s.id, status: "good", notes: "" })), status: "clear", notes: "", initials: "TI", photos: [] });
async function main() { try {
  const connectionToken = randomBytes(32).toString("hex");
  const direct = connectInspectionPhone(connectionToken, now);
  assert.equal(direct.device.truck, undefined);
  assert.deepEqual(connectInspectionPhone(connectionToken, now), direct, "a lost connection response must not create a second phone");
  assert.throws(() => connectInspectionPhone("short", now), /Reload/);
  assert.equal(listInspectionDevices().length, 1);
  revokeInspectionDevice(direct.device.deviceId, "manager@example.invalid");
  assert.throws(() => connectInspectionPhone(connectionToken, now), /disconnected/);
  const pairing = createInspectionPairing("Truck 4", "Synthetic truck phone", "manager@example.invalid", now);
  const phone = pairInspectionPhone(pairing.code, now);
  assert.equal(inspectionDevice(phone.token, now)?.truck, "Truck 4");
  assert.equal(inspectionDevice("bad", now), null);
  assert.throws(() => pairInspectionPhone(pairing.code, now), /already used/);
  assert.throws(() => pairInspectionPhone(createInspectionPairing("Truck 2", "Expired phone", "test", now).code, new Date(now.getTime() + 86400_001)), /expired/);
  const { loadLevel: _load, ...oldInput } = valid();
  assert.throws(() => validateTruckInspection(oldInput, now), /truck fullness/);
  assert.throws(() => validateTruckInspection({ ...valid(), loadLevel: "125%" }, now), /truck fullness/);
  assert.throws(() => validateTruckInspection({ ...valid(), fuel: "" }, now), /fuel/);
  assert.throws(() => submitTruckInspection(oldInput, phone.device, now), /truck fullness/);
  const legacyReport = { ...oldInput, version: 1, deviceId: phone.device.deviceId, receivedAt: now.toISOString(), inspectionDate: "2026-09-15" };
  const legacyPath = path.join(directory, "reports", `${createHash("sha256").update(`${phone.device.deviceId}:${oldInput.requestId}`).digest("hex")}.json`);
  fs.mkdirSync(path.dirname(legacyPath), { recursive: true });
  fs.writeFileSync(legacyPath, JSON.stringify(legacyReport));
  assert.deepEqual(submitTruckInspection(oldInput, phone.device, now), legacyReport, "a legacy receipt retry does not invent fullness or alter its version");
  assert.equal(fs.readFileSync(legacyPath, "utf8"), JSON.stringify(legacyReport));
  assert.throws(() => submitTruckInspection({ ...oldInput, loadLevel: "Empty" }, phone.device, now), /different answers/);
  const raw = valid(); const saved = submitTruckInspection(raw, phone.device, now);
  assert.equal(saved.truck, "Truck 4");
  assert.equal(saved.version, 2);
  assert.equal(saved.loadLevel, "3/4");
  assert.equal(saved.fuel, "1/2");
  assert.throws(() => submitTruckInspection({ ...raw, loadLevel: "Empty" }, phone.device, now), /different answers/);
  const { truck: _truck, ...legacy } = raw;
  assert.deepEqual(submitTruckInspection(legacy, phone.device, now), saved, "an old loaded client can finish its original truck report");
  assert.throws(() => submitTruckInspection({ ...raw, truck: "Truck 8" }, phone.device, now), /different answers/, "a retry cannot move a saved inspection to another truck");
  assert.throws(() => validateTruckInspection({ ...raw, truck: "Truck 99" }, now), /Choose the truck/);
  assert.throws(() => submitTruckInspection(legacy, direct.device, now), /Choose the truck/, "new shared phones require an explicit truck");
  assert.deepEqual(submitTruckInspection(raw, phone.device, new Date(now.getTime() + 1000)), saved);
  assert.equal(listTruckInspections("2026-09-15").length, 2);
  assert.deepEqual(findTruckInspection(phone.device.deviceId, raw.requestId), saved);
  assert.equal(findTruckInspection(randomUUID(), raw.requestId), null, "another device cannot read a report");
  assert.throws(() => submitTruckInspection({ ...raw, odometer: "999" }, phone.device, now), /different answers/);
  assert.throws(() => validateTruckInspection({ ...valid(), answers: [] }, now), /five sections/);
  assert.throws(() => validateTruckInspection({ ...valid(), answers: Array(5).fill(raw.answers[0]) }, now), /Check/);
  assert.throws(() => validateTruckInspection({ ...valid(), odometer: "" }, now), /mileage/);
  assert.throws(() => validateTruckInspection({ ...valid(), odometer: "1e4" }, now), /whole number/);
  const problem = valid(); problem.answers[0].status = "problem";
  assert.throws(() => validateTruckInspection(problem, now), /note/);
  problem.answers[0].notes = "Fluid leak";
  assert.throws(() => validateTruckInspection(problem, now), /problem was marked/);
  problem.status = "stop";
  assert.throws(() => submitTruckInspection(problem, phone.device, now), /photo for Walk-around/);
  assert.equal(findTruckInspection(phone.device.deviceId, problem.requestId), null, "missing evidence must not save a report");
  const photo = { section: "walk-around", data: "data:image/jpeg;base64,/9j/AA==" };
  assert.throws(() => validateTruckInspection({ ...problem, photos: [{ ...photo, section: "wheels-tires" }] }, now), /photo for Walk-around/);
  const photographed = { ...problem, photos: [photo] };
  assert.equal(submitTruckInspection(photographed, phone.device, now).status, "stop");
  assert.throws(() => submitTruckInspection(problem, phone.device, now), /different answers/, "removing a saved photo cannot alter a receipt");
  const allProblems = { ...valid(), status: "reported", answers: INSPECTION_SECTIONS.map(s => ({ id: s.id, status: "problem", notes: "Issue found" })), photos: INSPECTION_SECTIONS.map(s => ({ ...photo, section: s.id })) };
  assert.equal(submitTruckInspection(allProblems, phone.device, now).photos.length, 5);
  for (const section of INSPECTION_SECTIONS) {
    assert.throws(() => validateTruckInspection({ ...allProblems, photos: allProblems.photos.filter(p => p.section !== section.id) }, now), /Add a photo/);
  }
  assert.throws(() => validateTruckInspection({ ...allProblems, photos: [...allProblems.photos, photo] }, now), /up to five/);
  const stop = { ...valid(), status: "stop", notes: "Unsafe condition" };
  assert.throws(() => validateTruckInspection(stop, now), /photo showing why/);
  assert.equal(validateTruckInspection({ ...stop, photos: [photo] }, now).photos.length, 1);
  // Before this requirement, both report versions could be received without photos.
  for (const version of [1, 2]) {
    const oldProblem = { ...problem, requestId: randomUUID() };
    const oldReceipt = { ...oldProblem, version, deviceId: phone.device.deviceId, receivedAt: now.toISOString(), inspectionDate: "2026-09-15" };
    const oldPath = path.join(directory, "reports", `${createHash("sha256").update(`${phone.device.deviceId}:${oldProblem.requestId}`).digest("hex")}.json`);
    fs.writeFileSync(oldPath, JSON.stringify(oldReceipt));
    assert.deepEqual(submitTruckInspection(oldProblem, phone.device, now), oldReceipt);
    assert.equal(fs.readFileSync(oldPath, "utf8"), JSON.stringify(oldReceipt));
    assert.throws(() => submitTruckInspection({ ...oldProblem, notes: "Changed" }, phone.device, now), /different answers/);
    assert.throws(() => submitTruckInspection({ ...oldProblem, requestId: randomUUID(), version }, phone.device, now), /photo for Walk-around/, "client version cannot bypass photo validation");
  }
  assert.throws(() => validateTruckInspection({ ...valid(), status: "stop" }, now), /notes/);
  assert.throws(() => validateTruckInspection({ ...valid(), photos: [{ section: "walk-around", data: "data:image/svg+xml,<svg/>" }] }, now), /JPEG/);
  assert.equal(inspectionDate(new Date("2026-09-15T03:00:00Z")), "2026-09-14");
  assert.throws(() => validateTruckInspection({ ...valid(), startedAt: "2026-09-01T13:00:00Z" }, now), /seven days/);
  const dailyDir = path.join(directory, "dates", "2026-09-15"); fs.rmSync(dailyDir, { recursive: true });
  findTruckInspection(phone.device.deviceId, raw.requestId);
  assert.equal(listTruckInspections("2026-09-15").length, 1, "receipt lookup repairs an interrupted date index");
  const nextTruck = submitTruckInspection({ ...valid(), truck: "Truck 8" }, phone.device, now);
  assert.equal(nextTruck.truck, "Truck 8", "one phone can inspect another truck");
  assert.deepEqual(findTruckInspection(phone.device.deviceId, raw.requestId), saved);
  revokeInspectionDevice(phone.device.deviceId, "manager@example.invalid");
  assert.equal(inspectionDevice(phone.token, now), null);
  await assert.rejects(() => inspectionRequestBody(new Request("https://example.invalid/api/truck-inspection", { method: "POST", headers: { "Content-Type": "text/plain" }, body: "{}" })), /JSON/);
  await assert.rejects(() => inspectionRequestBody(new Request("https://example.invalid/api/truck-inspection", { method: "POST", headers: { "Content-Type": "application/json", Origin: "https://evil.invalid" }, body: "{}" })), /inspection app/);
  await assert.rejects(() => inspectionRequestBody(new Request("https://example.invalid/api/truck-inspection", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: "X".repeat(100) }) }), 10), /too large/);
  for (const route of ["/truck-inspection", "/api/truck-inspection", "/truck-inspection/manifest.webmanifest"]) assert.equal(publicAuthRoute(route), true);
  for (const route of ["/truck-inspection/admin", "/api/fleet-inspections", "/fleet-inspections"]) assert.equal(publicAuthRoute(route), false);
  console.log("Truck inspection storage, validation, retry, identity and request boundary checks passed.");
} finally { fs.rmSync(directory, { recursive: true, force: true }); } }
void main().catch(error => { console.error(error); process.exitCode = 1; });
