import assert from 'node:assert/strict';
import { filterHistory, historyEntries, historyCosts, truckMileageReview, workSections, visitTitle } from '../desktop-ui/lib/convoy-records';
import type { FleetMaintenanceRow, FleetIssueRow, DesktopFleetTruck } from '../desktop-ui/lib/people-fleet-contract';
const base: FleetMaintenanceRow={recordId:'invoice-example-100',truck:'Truck# 2',serviceDate:'2026-07-20',status:'completed',serviceType:'Other',description:'Invoice #100 — completed service and repairs\nBrakes: rear shoes',odometer:130000,cost:500,vendor:'Example Shop',nextServiceDate:'',nextServiceOdometer:null,notes:'VIN: EXAMPLE123',version:'test'};
const child={...base,recordId:'oil',serviceType:'Oil change',description:'Oil and filter replaced',cost:null,notes:'Linked invoice record: invoice-example-100. Category cost is unallocated.'};
const wrongTruck={...child,recordId:'wrong-truck',truck:'Truck# 3'};
const orphan={...child,recordId:'orphan',notes:'Linked invoice record: missing. Original invoice unavailable.'};
const zero={...base,recordId:'warranty',description:'Warranty',cost:0};
const scheduled={...child,recordId:'scheduled',status:'scheduled',serviceDate:'2026-10-20',cost:90};
const issue={issueId:'repair',truck:'Truck 2',title:'Mirror',description:'Replaced under warranty',status:'resolved',cost:0,updatedAt:'2026-08-01T12:00:00Z',resolution:'Done',owner:''} as FleetIssueRow;
const rows=historyEntries({maintenance:[base,child,wrongTruck,orphan,zero,scheduled],issues:[issue]});
assert.equal(rows.length,6);
assert.equal(rows.find(r=>r.kind==='invoice')!.children.length,1);
assert.equal(filterHistory(rows,{query:'EXAMPLE123',kind:'invoice'}).length,1);
assert.equal(filterHistory(rows,{category:'Oil change',kind:'completed',truck:'Truck 2'}).length,2);
assert.equal(filterHistory(rows,{from:'2026-08-01',to:'2026-08-01'}).length,1);
assert.equal(filterHistory(rows,{kind:'scheduled'}).length,1);
assert.equal(filterHistory(rows,{query:'no match'}).length,0);
assert.deepEqual(historyCosts(rows),{total:500,missing:2,count:5});
assert.deepEqual(historyCosts([rows.find(r=>r.record?.recordId==='warranty')!]),{total:0,missing:0,count:1});
assert.equal(historyCosts([]).total,null);
const now=Date.parse('2026-10-07T19:00:00Z');
const truck={id:'Truck 2',mileage:{value:14000,source:'virtual',reportedAt:new Date(now).toISOString(),retrievedAt:new Date(now).toISOString(),estimated:14000,conflicting:false,duplicate:false}} as DesktopFleetTruck;
assert.equal(truckMileageReview(truck,[base],now).quality,'conflict');
assert.equal(truckMileageReview(truck,[{...base,status:'scheduled'}],now).quality,'current');
assert.equal(truckMileageReview(truck,[{...base,serviceDate:'2027-01-01'}],now).quality,'current');
assert.equal(truckMileageReview(truck,[{...base,truck:'Truck 3'}],now).quality,'current');
console.log('Convoy records passed: explicit invoice grouping, orphan preservation, filters, null/zero costs and mileage conflict evidence.');

// Display grouping preserves original amounts and continuation lines without inferring work.
assert.deepEqual(workSections('Invoice #100 — completed service and repairs\nBrakes: Shoes ($500).\nContinued note.\nOil change: Filter and oil.'),[{label:'Brakes',text:'Shoes ($500).\nContinued note.'},{label:'Oil change',text:'Filter and oil.'}]);
assert.deepEqual(workSections('Complaint: Runs rough.\nDiagnosis pending.'),[{label:'Complaint',text:'Runs rough.\nDiagnosis pending.'}]);
assert.equal(visitTitle(rows.find(r=>r.kind==='invoice')!),'Oil change');
assert.equal(visitTitle(rows.find(r=>r.kind==='repair')!),'Mirror');
