import assert from 'node:assert/strict';
import { appointmentVisitAlerts } from '../lib/appointment-visit-alerts';
import { commandAlertWorkItemForSource } from '../lib/command-alert-workflow';
import type { OperationalAlert } from '../lib/operational-alert-presentation';
import type { WorkItem } from '../lib/platform/contracts';
const date='2026-09-08',now=Date.parse('2026-09-09T03:00:00Z');
const interval={arrival:'2026-09-08T13:00:00Z',departure:'2026-09-08T13:20:16Z',departure_confirmed:true};
const visit={appointment_id:'101',jk_number:'JK1000001',truck_number:'2',match_confidence:'confirmed',visit_count:1,visit_intervals:[interval]};
const job={appointmentId:'101',jkNumber:'JK1000001',customerName:'Example Customer',address:'Example service address',territory:'New Orleans',truck:'Truck 9'};
const run=(rows:Parameters<typeof appointmentVisitAlerts>[1],alerts:OperationalAlert[]=[],operatingDate=date)=>appointmentVisitAlerts(alerts,rows,[job],operatingDate,now);
const fact=(alert:OperationalAlert,label:string)=>alert.facts.find(f=>f.label===label)?.value;
const closed=run([visit]);
assert.equal(closed.length,1,'confirmed visit is visible without Slack');
assert.equal(closed[0].label,'Site Visit Completed');
assert.equal(fact(closed[0],'Time on site'),'20m 16s');
assert.equal(closed[0].truck,'Truck 2','actual truck is independent of assignment');
assert.match(closed[0].href,/appointment=101/);
const open={...visit,visit_intervals:[{arrival:interval.arrival,departure:null,departure_confirmed:false}]};
const arrived=run([open])[0];
assert.equal(arrived.label,'Arrival');
assert.equal(fact(arrived,'Departed'),'Awaiting confirmed departure');
assert.equal(arrived.id,closed[0].id,'arrival identity survives departure');
const returned=run([{...visit,visit_intervals:[interval,{arrival:'2026-09-08T15:00:00Z',departure:'2026-09-08T15:05:00Z',departure_confirmed:true}]}]);
assert.equal(returned.length,2);
assert.equal(new Set(returned.map(a=>a.id)).size,2);
assert.deepEqual(returned.map(a=>fact(a,'Time on site')),['5m','20m 16s'],'exclude time away');
assert.equal(run([visit,visit]).length,1,'duplicate records do not duplicate visits');
assert.equal(run([{...visit,pass_by_only:true}]).length,0);
assert.equal(run([{...visit,match_confidence:'possible'}]).length,0);
assert.equal(run([{...visit,visit_count:2,visit_intervals:[],first_arrival:interval.arrival,final_departure:interval.departure}]).length,0,'do not span unsegmented return visits');
assert.equal(run([{...visit,visit_intervals:[{arrival:'invalid'}]}]).length,0);
assert.equal(run([{...visit,visit_intervals:[{arrival:'2026-09-10T13:00:00Z'}]}]).length,0);
assert.equal(run([visit],[],'2026-09-07').length,0);
assert.equal(run([{...visit,visit_intervals:[{...interval,departure_confirmed:false}]}])[0].label,'Arrival');
assert.equal(run([{...visit,visit_intervals:[{...interval,departure:'2026-09-10T14:00:00Z'}]}])[0].label,'Arrival');
const conflict=run([visit,{...visit,visit_intervals:[{...interval,departure:'2026-09-08T13:22:00Z'}]}])[0];
assert.equal(fact(conflict,'Time on site'),undefined);
assert.match(fact(conflict,'Departed')!,/conflicting/);
const operational=run([{...visit,operational_confirmation:true}])[0];
assert.equal(operational.source,'Operational confirmation');
assert.match(fact(operational,'Time on site')!,/Unavailable/);
const overnight=run([{...visit,visit_intervals:[{arrival:'2026-09-08T04:55:00Z',departure:'2026-09-08T05:10:00Z'}]}])[0];
assert.equal(fact(overnight,'Time on site'),'15m');
assert.match(fact(overnight,'Arrived')!,/Sep 7/);
const legacy=(id:string,label:string,reported:string):OperationalAlert=>({id,label,timestamp:'2026-09-08T13:21:00Z',title:'Truck 2 · JK1000001',truck:'Truck 2',domain:'Dispatch',detected:'8:21 AM',facts:[{label,value:reported}],owner:'Dispatch',next:'',href:'',needsAction:false});
const reports=[legacy('arrival','Arrival','8:00 AM'),legacy('departure1','Departure','8:10 AM'),legacy('departure2','Departure','8:20 AM')];
const merged=run([visit],reports);
assert.equal(merged.length,1,'arrival and revised departures become one visit');
assert.deepEqual(new Set(merged[0].sourceMessageIds),new Set(reports.map(a=>a.id)));
const review={id:'review',entity:{id:'departure1'},status:'acknowledged'} as WorkItem;
assert.equal(commandAlertWorkItemForSource([review],merged[0])?.id,'review');
assert.equal(run([open],[reports[0]]).length,1,'open arrival absorbs its Slack report');
assert.equal(run([visit],[{...reports[0],threadReply:true}]).length,2,'thread replies remain independent');
assert.equal(run([visit],[{...reports[0],truck:'Truck 9'}]).length,2,'wrong truck is never absorbed');
assert.equal(run([visit,{...visit,appointment_id:'102'}],[reports[0]]).length,3,'ambiguous appointment reports remain independent');
console.log('PASS appointment visit alerts: arrivals, departures, returns, aliases, confidence, gaps, dates, actual truck');
