import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {resolveWaypointFleetCrew,readWaypointFleetCrews} from '../lib/fleet-waypoint-crew';
import {createCrewPhoneEnrollment,enrollCrewPhone} from '../lib/crew-phone-store';
import {saveCrewDay} from '../lib/crew-phone-day';
import {INSPECTION_SECTIONS} from '../lib/truck-inspection';
import {connectInspectionPhone,submitTruckInspection,correctInspectionTruck,listTruckInspections,findTruckInspection} from '../lib/truck-inspection-store';
import {readInspectionMileage} from '../lib/fleet-mileage-inspections';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'waypoint-fleet-crew-'));
process.env.OPS_CREW_PHONE_DIR=path.join(root,'phones');process.env.OPS_TRUCK_INSPECTION_DIR=path.join(root,'inspections');process.env.OPSCENTER_DATA_DIR=root;
const now=new Date(),date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago'}).format(now);
try {
 const phone=enrollCrewPhone(createCrewPhoneEnrollment('Truck 9','Test phone','test',now).code,'a'.repeat(64),now);
 const day=saveCrewDay(phone,{date,truck:'Truck 9',requestId:randomUUID(),expectedVersion:0,driver:'Driver One',responsible:'Driver One',navigators:['Navigator One']},now,['Driver One','Navigator One']);
 assert.equal(readWaypointFleetCrews(date,['Truck 9'],now).get('Truck 9')?.driver,'Driver One');
 const setup={label:phone.label,day};
 assert.match(resolveWaypointFleetCrew('Truck# 9',[setup],[])!.crewNote,/Inspection not received/);
 assert.equal(resolveWaypointFleetCrew('Truck 4',[setup],[]),null);
 assert.equal(resolveWaypointFleetCrew('Truck 9',[setup,{label:'Other',day:{...day,driver:'Driver Two'}}],[])!.driver,'Crew conflict');
 assert.equal(resolveWaypointFleetCrew('Truck 9',[setup,setup],[])!.driver,'Driver One');
 const device=connectInspectionPhone('b'.repeat(64),now).device;
 const input={requestId:randomUUID(),truck:'Truck 9',inspector:'Driver One',odometer:'154820',fuel:'Full',loadLevel:'Full',startedAt:now.toISOString(),answers:INSPECTION_SECTIONS.map(s=>({id:s.id,status:'good',notes:''})),status:'clear',notes:'',initials:'DO',photos:[]};
 const report=submitTruckInspection(input,device,now);
 const files=fs.readdirSync(path.join(root,'inspections/reports'));
 const original=fs.readFileSync(path.join(root,'inspections/reports',files[0]),'utf8');
 assert.equal(readInspectionMileage()[0].truck,'Truck 9');
 const correction={deviceId:device.deviceId,requestId:report.requestId,expectedTruck:'Truck 9',truck:'Truck 4',actor:'test manager',reason:'Wrong truck selected'};
 correctInspectionTruck(correction,now);
 assert.equal(listTruckInspections(date)[0].truck,'Truck 4');
 assert.equal(findTruckInspection(device.deviceId,report.requestId)?.truck,'Truck 4');
 assert.equal(readInspectionMileage()[0].truck,'Truck 4','Cached mileage must follow correction');
 assert.equal(submitTruckInspection(input,device,now).truck,'Truck 4','Original retry returns corrected receipt');
 assert.equal(correctInspectionTruck(correction,now).truck,'Truck 4');
 assert.throws(()=>correctInspectionTruck({...correction,truck:'Truck 2'},now),/different correction/);
 assert.equal(fs.readFileSync(path.join(root,'inspections/reports',files[0]),'utf8'),original,'Original submission is immutable');
 saveCrewDay(phone,{date,truck:'Truck 4',requestId:randomUUID(),expectedVersion:1,driver:day.driver,responsible:day.responsible,navigators:day.navigators},now,['Driver One','Navigator One']);
 const resolved=readWaypointFleetCrews(date,['Truck 4','Truck 9'],now);
 assert.equal(resolved.get('Truck 4')?.driver,'Driver One');assert.equal(resolved.has('Truck 9'),false,'Prior phone truck is not retained');
 assert.match(resolved.get('Truck 4')!.crewNote,/Inspection received/);
 assert.equal(readWaypointFleetCrews('2000-01-01',['Truck 4'],now).size,0);
 fs.writeFileSync(path.join(root,'phones/days',phone.deviceId,date,'2.json'),'invalid');
 assert.equal(readWaypointFleetCrews(date,['Truck 4'],now).get('Truck 4')?.driver,'Crew unavailable');
 console.log('Waypoint crew projection and immutable inspection correction passed.');
} finally {fs.rmSync(root,{recursive:true,force:true});}
