import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { processRecyclingImage, isRecyclingMessage } from '../lib/whatsapp-recycling';
import { readRecyclingData } from '../lib/recycling-receipt-store';
import { updateDesktopFinance } from '../lib/desktop-finance';
import { parseRecyclingOcr } from '../lib/recycling-receipt-ocr';
import { recordWhatsAppTextContext, recentWhatsAppPhotoContext } from '../lib/whatsapp-job-photo-queue';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'recycling-fixture-'));
const env={...process.env};process.env.OPSCENTER_DESKTOP_COMMERCIAL_DIR=path.join(root,'store');process.env.WHATSAPP_JOB_PHOTO_STATE_DIR=path.join(root,'queue');
const actor={email:'test@example.invalid',role:'manager' as const};
const message={version:1 as const,messageId:'page1',senderPhone:'15550001111',phoneNumberId:'test-receiver',receivedAt:'2026-09-11T12:00:00Z',mediaId:'test',mimeType:'image/jpeg',sha256:'',caption:'Recycling',enqueuedAt:''};
const image=path.join(root,'image.jpg');fs.writeFileSync(image,'synthetic image');
const recognize=async()=>[];
async function main(){try {
 assert.equal(isRecyclingMessage('Recycling'),true);assert.equal(isRecyclingMessage('Resale'),false);
 const other=await processRecyclingImage({...message,caption:'JK4000123'},async()=>{throw Error('must not download')},recognize,false);assert.equal(other,null);
 const saved=await processRecyclingImage(message,async()=>image,recognize,false);assert.equal(saved?.status,'review');assert.equal(readRecyclingData().records.length,0,'OCR never posts income');
 await processRecyclingImage(message,async()=>{throw Error('duplicate downloaded')},recognize,false);assert.equal(readRecyclingData().receiptDrafts![0].photos.length,1);
 recordWhatsAppTextContext({...message,text:'Recycling'});
 const context=recentWhatsAppPhotoContext(message.senderPhone,new Date('2026-09-11T12:01:00Z'),10,message.phoneNumberId);
 assert.equal(context.recycling?.messageId,'page1');assert.equal(recentWhatsAppPhotoContext(message.senderPhone,new Date('2026-09-11T12:11:00Z'),10,message.phoneNumberId).recycling,undefined);
 await processRecyclingImage({...message,messageId:'page2',caption:'',matchingContext:{version:1,...context,capturedAt:''}},async()=>image,recognize,false);
 let draft=readRecyclingData().receiptDrafts![0];assert.equal(draft.photos.length,2);
 const operation={requestId:crypto.randomUUID(),recordId:draft.id,date:'2026-09-11',action:'recycling.receipt.record' as const,expectedVersion:draft.version,values:{reviewed:true,paid:true,paymentDate:'2026-09-11',paymentReference:'Cash',yard:'Test yard',total:12.34,rows:[{date:'2026-08-01',ticket:'TEST-1',material:'Steel',weightLb:20,amount:5},{date:'2026-08-02',ticket:'TEST-2',material:'Copper',weightLb:10,amount:7.34}]}};
 assert.throws(()=>updateDesktopFinance({...operation,values:{...operation.values,total:13}},actor),/equal/);
 assert.throws(()=>updateDesktopFinance({...operation,values:{...operation.values,paymentDate:''}},actor),/received/);
 assert.throws(()=>updateDesktopFinance({...operation,values:{...operation.values,reviewed:false}},actor),/checked/);
 assert.equal(updateDesktopFinance(operation,actor).status,'verified');assert.equal(updateDesktopFinance(operation,actor).status,'verified');
 assert.equal(readRecyclingData().records.length,2);assert.equal(readRecyclingData().records[0].paymentDate,'2026-09-11');assert.equal(readRecyclingData().receiptDrafts![0].status,'recorded');
 await processRecyclingImage({...message,messageId:'late-page',caption:'',matchingContext:{version:1,...context,capturedAt:''}},async()=>image,recognize,false);
 assert.equal(readRecyclingData().receiptDrafts!.length,2,'Late page gets its own review, never alters posted runs');
 const later=readRecyclingData().receiptDrafts![1];assert.throws(()=>updateDesktopFinance({...operation,requestId:crypto.randomUUID(),recordId:later.id,expectedVersion:later.version},actor),/already recorded/);
 assert.equal(readRecyclingData().records.length,2,'Overlap never duplicates income');
 assert.equal(parseRecyclingOcr([]).rows.length,0);
 const box=(text:string,x:number,y:number)=>({text,x,y,width:.02,height:.01,confidence:1});
 const parsed=parseRecyclingOcr([box('Ticket',.15,.8),box('Gross',.4,.8),box('Net',.6,.8),box('Rate',.7,.8),box('Total',.9,.8),box('8/1/26',.05,.70),box('8/2/26',.05,.68),box('12345',.15,.70),box('12346',.15,.68),box('Steel',.25,.70),box('Copper',.25,.68),box('$10.00',.9,.72),box('$20.00',.9,.70),box('100 LB',.6,.713),box('200 LB',.6,.693)]);
 assert.deepEqual(parsed.rows.map(row=>row.weightLb),[100,200],'Photographed slope must not select the preceding row weight');
 assert.deepEqual(parsed.rows.map(row=>row.amount),[10,20]);
 console.log('OpsBot recycling: routing, page context, retry deduplication, review-only OCR, exact totals, payment dates, late pages and duplicate-ticket rejection passed.');
}finally{process.env=env;fs.rmSync(root,{recursive:true,force:true});}}
void main();
