import assert from 'node:assert/strict';
import { customerSearchFields, normalizeCustomerSelection } from '../lib/junkware-customer-contract';
import { customerRow, selectedCustomerIndex } from './junkware-customer-lookup';
assert.deepEqual(customerSearchFields(' Sample   Customer '), { firstName: 'Sample', lastName: 'Customer' });
assert.deepEqual(customerSearchFields('Customer'), { lastName: 'Customer' });
assert.deepEqual(customerSearchFields('+1 (504) 555-0100'), { phone: '5045550100' });
assert.deepEqual(customerSearchFields('sample@example.com'), { email: 'sample@example.com' });
assert.throws(() => customerSearchFields('555'), /seven/);
assert.throws(() => customerSearchFields('a'), /2–160/);
const cells = ['Job', 'Sample Customer', '', '(504) 555-0100', '', 'sample@example.com', '100 Sample St', '100 Sample St'];
const job = customerRow(cells), estimate = customerRow(['Estimate', ...cells.slice(1)]);
assert.notEqual(job.key, estimate.key);
assert.equal(selectedCustomerIndex([job, estimate], estimate.key), 1, 'Job and Estimate source records remain individually selectable');
assert.throws(() => selectedCustomerIndex([job, job], job.key), /ambiguous/, 'indistinguishable records must not be selected arbitrarily');
assert.throws(() => selectedCustomerIndex([customerRow([...cells.slice(0,7), '200 Other St'])], job.key), /changed/);
assert.throws(() => customerRow(['unexpected columns']), /columns changed/);
assert.deepEqual(normalizeCustomerSelection({ query: 'Sample Customer', key: job.key }), { query: 'Sample Customer', key: job.key });
assert.throws(() => normalizeCustomerSelection({ query: 'Sample Customer', key: 'bad' }));
console.log('Customer lookup: name/phone/email, source selection, changed and ambiguous records passed.');
