import assert from 'node:assert/strict';
import {advanceInspectionMileage,type MileageGpsDay} from '../lib/fleet-gps-mileage';
import type {FleetMileage} from '../lib/fleet-service-plan';
const at=Date.parse('2026-10-08T12:00:00Z');
const baseline:FleetMileage={value:81013,source:'inspection',reportedAt:new Date(at).toISOString(),retrievedAt:new Date(at).toISOString(),estimated:null,conflicting:false,duplicate:false};
const t=(minutes:number)=>new Date(at+minutes*60000).toISOString();
const point=(minutes:number,longitude:number)=>({truck:'Truck 9',timestamp:t(minutes),latitude:30,longitude});
const trip={truck:'Truck 9',id:'a',start:at+60000,end:at+11*60000,miles:5};
const day:MileageGpsDay={date:'2026-10-08',observedAt:t(20),trips:[trip,trip],points:[point(1,-90),point(5,-89.95),point(11,-89.9)]};
const result=advanceInspectionMileage('Truck# 9',baseline,[day],at+20*60000);
assert.equal(result.value,81018,'Completed trips and duplicate receipts count once; covered points do not add again');
assert.equal(result.source,'estimated');assert.equal(result.inspectionBaseline?.value,81013);
assert.equal(advanceInspectionMileage('Truck 9',result,[day],at+20*60000),result,'Never compound a calculated total');
assert.equal(advanceInspectionMileage('Truck 4',baseline,[day],at+20*60000).value,81013,'Another truck cannot contribute');
const partial=advanceInspectionMileage('Truck 9',baseline,[{...day,trips:[],points:[point(1,-90),point(2,-89.99),point(15,-89.5)]}],at+20*60000);
assert.ok(partial.value!>81013&&partial.value!<81014);assert.equal(partial.gpsIncomplete,true,'Long gaps cannot become invented mileage');
const reset=advanceInspectionMileage('Truck 9',{...baseline,value:82000,reportedAt:t(12)},[day],at+20*60000);assert.equal(reset.value,82000,'New reading resets baseline and excludes earlier trips');
const overlap=advanceInspectionMileage('Truck 9',{...baseline,reportedAt:t(5)},[day],at+20*60000);assert.ok(overlap.value!<81018,'Trip crossing inspection time is not counted in full');
assert.equal(advanceInspectionMileage('Truck 9',{...baseline,conflicting:true},[day],at+20*60000).source,'inspection');
console.log('Visual baseline plus GPS: reset, truck isolation, deduplication, overlapping trips and gaps passed.');
