import assert from 'node:assert/strict';
import { operatingChartRows, smoothOperatingChartRows, shiftDay, scopeOperatingTrends, type OperatingDay, type OperatingTrendsData } from '../lib/operating-trends';
import { monthRevenueProjection, operatingPatterns, planningEstimate, planningBacktest, upcomingDemand } from '../lib/operating-planning';

const row = (date: string, overrides: Partial<OperatingDay> = {}): OperatingDay => ({ date, jobDay: 'operating', completedJobs: 10, revenue: 1000, recordedFuel: 20, wexCost: 30, gallons: 10, netPerGallon: 3, dumpCost: 40, ...overrides });
const data: OperatingTrendsData = { generatedAt: '2026-09-25T15:00:00Z', snapshotDate: '2026-09-25', historyThrough: '2026-09-24', forecasts: [], wexCoverage: null, daily: Array.from({ length: 100 }, (_, i) => row(shiftDay('2026-09-24', i - 99))) };
const raw = operatingChartRows(data, 'revenue', 30);
const closed = row('2026-09-20', { revenue: 0, completedJobs: 0, jobDay: 'zero' });
const changed = { ...data, daily: data.daily.filter(day => day.date !== '2026-09-21').map(day => day.date === closed.date ? closed : day.date === '2026-09-22' ? { ...day, revenue: null } : day) };
const smoothed = smoothOperatingChartRows(changed, 'revenue', operatingChartRows(changed, 'revenue', 30), true);
assert.equal(smoothed.find(day => day.date === closed.date), undefined, 'confirmed closures omitted');
assert.equal(smoothed.find(day => day.date === '2026-09-21')?.actual, null, 'missing day remains gap');
assert.equal(smoothed.find(day => day.date === '2026-09-22')?.actual, null, 'missing metric remains gap');
assert.equal(smoothed.at(-1)?.actual, 1000);
assert.equal(operatingChartRows(changed, 'revenue', 30).find(day => day.date === closed.date)?.actual, 0, 'raw zero retained');
assert.equal(raw[0].actual, smoothOperatingChartRows(data, 'revenue', raw, true)[0].actual);
assert.equal(smoothOperatingChartRows(data, 'revenue', raw, true)[0].observedDays, 7, 'uses history before plotted range');
const zeroRevenue = { ...data, daily: [row('2026-09-23'), row('2026-09-24', { revenue: 0 })] };
assert.equal(smoothOperatingChartRows(zeroRevenue, 'revenue', operatingChartRows(zeroRevenue, 'revenue', 2), true).at(-1)?.actual, 500, 'real metric zero on working day counts');
const unknown = { ...data, daily: [row('2026-09-24', { jobDay: null })] };
assert.equal(smoothOperatingChartRows(unknown, 'revenue', operatingChartRows(unknown, 'revenue', 1), true)[0].actual, null);
const weighted = { ...data, daily: [row('2026-09-23', { wexCost: 10, gallons: 1 }), row('2026-09-24', { wexCost: 90, gallons: 90 })] };
assert.equal(smoothOperatingChartRows(weighted, 'netPerGallon', operatingChartRows(weighted, 'netPerGallon', 2), true).at(-1)?.actual, 100 / 91);
const campaign = { ...data, daily: [row('2026-09-24', { jobDay: 'zero', adCost: 80, calls: 4 })] };
assert.equal(smoothOperatingChartRows(scopeOperatingTrends(campaign, 'marketing')!, 'costPerCall', operatingChartRows(campaign, 'costPerCall', 1), false)[0].actual, 20, 'closed-day campaigns preserved');

assert.equal(planningEstimate(data.daily, '2026-09-25', 'revenue')?.value, 1000);
assert.equal(planningEstimate([...data.daily, row('2026-09-26', { revenue: 999999 })], '2026-09-25', 'revenue')?.value, 1000, 'no future leakage');
assert.equal(planningEstimate([closed], '2026-09-25', 'revenue'), null, 'closure cannot train model');
const sundayHistory = data.daily.map(day => new Date(`${day.date}T12:00Z`).getUTCDay() === 0 ? { ...day, jobDay: 'zero' as const, completedJobs: 0, revenue: 0 } : day);
sundayHistory.push(row('2026-09-13', { revenue: 400 }), row('2026-09-20', { revenue: 800 }));
assert.equal(planningEstimate(sundayHistory, '2026-09-27', 'revenue')?.samples, 2, 'new Sundays use operating Sunday history');
assert.equal(planningEstimate(sundayHistory, '2026-09-27', 'revenue')?.value, 2000 / 3);
const patterns = operatingPatterns(changed, 90);
assert.equal(patterns.weekdays.reduce((sum, day) => sum + day.samples, 0), 88, 'one closure and one missing date excluded');
assert.equal(patterns.monthDays.length, 31);
assert.equal(planningBacktest(data.daily, 'completedJobs').wape, 0);
assert.equal(upcomingDemand(data, '2026-09-25').length, 14);
assert.equal(upcomingDemand(data, '2026-09-26').length, 0, 'stale snapshot suppressed');
assert.equal(upcomingDemand({ ...data, historyThrough: '2026-09-20' }, '2026-09-25').length, 0, 'historical selection suppressed');
const input = { today: '2026-09-25', month: '2026-09', actual: 24000, through: '2026-09-24', partialDayRevenue: null };
assert.equal(monthRevenueProjection(data, input)?.remaining, 6000);
assert.equal(monthRevenueProjection(data, input)?.total, 30000);
assert.equal(monthRevenueProjection(data, { ...input, actual: 24200, through: '2026-09-25', partialDayRevenue: 200 })?.total, 30000, 'no double counting partial day');
assert.equal(monthRevenueProjection(data, { ...input, actual: 26000, through: '2026-09-25', partialDayRevenue: 2000 })?.total, 31000, 'never subtract strong actuals');
assert.equal(monthRevenueProjection(data, { ...input, through: '2026-09-25' }), null, 'unknown partial amount cannot be guessed');
assert.equal(monthRevenueProjection(data, { ...input, month: '2026-08' }), null);
assert.equal(monthRevenueProjection(data, { ...input, actual: null }), null);
assert.equal(monthRevenueProjection({ ...data, daily: [] }, input), null);
assert.deepEqual(monthRevenueProjection(data, { ...input, missingDates: ['2026-09-07'] })?.missingDates, ['2026-09-07']);
assert.equal(scopeOperatingTrends(data, 'jobs')?.daily[0].revenue, null);
console.log('PASS: operating-day smoothing, weighted rates, calendar patterns, prior-only forecasts, month-end reconciliation and scope safety');
