import assert from 'node:assert/strict';
import {closeoutChargesSummary,closeoutGpsTimes} from '../lib/closeout-draft-summary';
const draft={loadPrice:'598.00',bedloadPrice:'50.00',discount:'20',tip:'10',otherCharges:[{label:'Labor',quantity:'2',price:'30',total:'$60.00'}],otherChargeOptions:[]};
assert.deepEqual(closeoutChargesSummary(draft,[]),{subtotal:708,total:698,estimated:false});
assert.deepEqual(closeoutChargesSummary({...draft,loadPrice:'0.10',bedloadPrice:'0.20',discount:'',tip:'',otherCharges:[]},[]),{subtotal:.3,total:.3,estimated:false});
assert.deepEqual(closeoutChargesSummary(draft,[{label:'Extra',quantity:'2',price:'25',total:'',typeValue:'extra|25|0'}]),{subtotal:758,total:748,estimated:false});
assert.deepEqual(closeoutChargesSummary(draft,[{label:'Card fee',quantity:'1',price:'',total:'',typeValue:'card|3|1'}]),{subtotal:728.64,total:718.64,estimated:true});
assert.ok(Number.isNaN(closeoutChargesSummary({...draft,loadPrice:'bad'},[]).subtotal));
const hours=Array.from({length:24},(_,i)=>({value:String(i).padStart(2,'0'),label:String(i)}));
const minutes=Array.from({length:12},(_,i)=>({value:String(i*5).padStart(2,'0'),label:String(i*5)}));
const times={actualStartHour:{value:'',options:hours},actualEndHour:{value:'',options:hours},actualStartMinute:{value:'',options:minutes},actualEndMinute:{value:'',options:minutes}};
const visit={minutes:23,arrival:'2026-09-09T14:26:24Z',departure:'2026-09-09T14:49:00Z',label:'23 min'};
const suggested={actualStartHour:'09',actualStartMinute:'25',actualEndHour:'09',actualEndMinute:'50'};
assert.deepEqual(closeoutGpsTimes(visit,'Truck# 1','Truck 1','2026-09-09',times),suggested);
assert.deepEqual(closeoutGpsTimes({...visit,departure:null},'Truck 1','Truck 1','2026-09-09',times),{actualStartHour:'09',actualStartMinute:'25'});
for (const [truck,date] of [['Truck 6','2026-09-09'],['Truck 1','2026-09-08'],['','2026-09-09']]) assert.deepEqual(closeoutGpsTimes(visit,'Truck 1',truck,date,times),{});
assert.deepEqual(closeoutGpsTimes(undefined,'Truck 1','Truck 1','2026-09-09',times),{});
assert.deepEqual(closeoutGpsTimes({...visit,arrival:'invalid'},'Truck 1','Truck 1','2026-09-09',times),{});
assert.deepEqual(closeoutGpsTimes({...visit,departure:'2026-09-09T14:20:00Z'},'Truck 1','Truck 1','2026-09-09',times),{actualStartHour:'09',actualStartMinute:'25'});
assert.deepEqual(closeoutGpsTimes({...visit,arrival:'2026-09-09T14:59:00Z',departure:null},'Truck 1','Truck 1','2026-09-09',times),{actualStartHour:'10',actualStartMinute:'00'});
console.log('Draft closeout totals and GPS defaults passed: currency rounding, discounts, tips, added charges, estimated fees, truck/day matching, missing exits and source minute options.');
