import assert from 'node:assert/strict';
import {desktopSourceHref, desktopAppointmentHref, desktopAlertHref} from '../desktop-ui/lib/desktop-links';
import {fixtureSnapshot} from './fixtures/crew-progress';
import {resolveScheduleDeepLink, type ScheduleAppointment} from '../desktop-ui/lib/schedule-contract';
const origin='https://ops.junk-king.app';
const job=new URL(desktopAppointmentHref('JK4000001','2026-09-06'),origin);
assert.equal(job.pathname,'/desktop');
assert.equal(job.searchParams.get('workspace'),'Schedule');
assert.equal(job.searchParams.get('q'),'JK4000001');
assert.equal(job.searchParams.get('date'),'2026-09-06');
const legacy=new URL(desktopSourceHref('/jobs?date=2026-09-06&jk=JK4000001',origin),origin);
assert.equal(legacy.pathname,'/desktop');assert.equal(legacy.searchParams.get('q'),'JK4000001');
assert.equal(desktopSourceHref('https://junkware.junk-king.com/source',origin),'https://junkware.junk-king.com/source');
assert.equal(new URL(desktopSourceHref('/fleet?truck=Truck%203',origin),origin).searchParams.get('truck'),'Truck 3');
const hashLink=new URL(desktopSourceHref('/jobs?date=2026-09-06#job-jk4000001',origin),origin);
assert.equal(hashLink.searchParams.get('q'),'JK4000001');
assert.equal(hashLink.searchParams.get('date'),'2026-09-06');
assert.equal(hashLink.searchParams.get('scheduleDay'),'today');
assert.equal(hashLink.hash,'');
const snapshot=fixtureSnapshot();
const closed=snapshot.alerts.find(alert=>alert.id==='closed-one')!;
const exact=new URL(desktopAlertHref(closed,snapshot,origin),origin);
assert.equal(exact.searchParams.get('appointment'),'101','A linked closeout opens its source appointment, not just the JK');
assert.equal(exact.searchParams.get('date'),'2026-09-07');
assert.equal(new URL(desktopAlertHref({...closed,href:'/jobs?date=2026-09-06&appointment=201'},snapshot,origin),origin).searchParams.get('appointment'),'201','An explicit source identity takes precedence over JK-based progress matching');
const choices=[{recordId:'2026-09-07:appointment:101',appointmentId:'101',jkNumber:'JK1000001',customerName:'Example'}, {recordId:'2026-09-07:appointment:201',appointmentId:'201',jkNumber:'JK1000001',customerName:'Example'}] as ScheduleAppointment[];
assert.equal(resolveScheduleDeepLink(choices,exact.searchParams.get('q')||'',exact.searchParams.get('appointment')||'').recordId,choices[0].recordId);
const fallback=new URL(desktopAlertHref({...closed,href:'/jobs?date=2026-09-06#job-jk1000001'},{date:snapshot.date},origin),origin);
assert.equal(fallback.searchParams.get('date'),'2026-09-06','Legacy links retain their operating date');
assert.equal(resolveScheduleDeepLink(choices,fallback.searchParams.get('q')||'','').recordId,null,'An ambiguous JK must remain a choice');
const bare=new URL(desktopAlertHref({...closed,href:'/jobs'},{date:'2026-09-06'},origin),origin);
assert.equal(bare.searchParams.get('q'),'JK1000001');
assert.equal(bare.searchParams.get('date'),'2026-09-06');
assert.equal(desktopAlertHref({...closed,id:'fuel',href:'/fleet?date=2026-09-06&truck=4'},snapshot,origin),'/desktop?date=2026-09-06&truck=4&workspace=Fleet&data=live');
assert.equal(desktopAlertHref({...closed,id:'external',href:'https://junkware.junk-king.com/source'},snapshot,origin),'https://junkware.junk-king.com/source');
console.log('Desktop links preserve date, appointment reference, workspace, and external source URLs.');
