import assert from 'node:assert/strict';
import { canonicalControlInput, controlGateCleared, controlItemActive, parseControlRequest, validControlDate, type ControlGate } from '../desktop-ui/lib/control-contract';
import { CONTROL_ACTION_DEFINITIONS, controlReconciliationReady } from '../lib/desktop-control';
import { opsRoleCan } from '../lib/ops-roles';
import { canTransitionWorkItem } from '../lib/platform/state-machines';

const now = new Date('2026-09-04T15:00:00Z');
const request = { date: '2026-09-04', requestId: 'synthetic-control-test-001', expectedVersion: 1, action: 'handoff', itemId: 'work_synthetic', status: 'in_progress', reason: 'Review the source before dispatch.', dueAt: '2026-09-05T15:00:00Z', assignToSelf: true };
assert.equal(validControlDate('2028-02-29'), '2028-02-29');
assert.throws(() => validControlDate('2026-02-29'), /valid/);
assert.throws(() => validControlDate('2026-09-31'), /valid/);
assert.throws(() => validControlDate('../today'), /valid/);
assert.equal(parseControlRequest(request, now).dueAt, '2026-09-05T15:00:00.000Z');
assert.throws(() => parseControlRequest({ ...request, action: 'verified' }, now), /Unsupported/);
assert.throws(() => parseControlRequest({ ...request, expectedVersion: '1' }, now), /version/);
assert.throws(() => parseControlRequest({ ...request, expectedVersion: 0 }, now), /version/);
assert.throws(() => parseControlRequest({ ...request, dueAt: now.toISOString() }, now), /future/);
assert.throws(() => parseControlRequest({ ...request, dueAt: '2027-01-01T00:00:00Z' }, now), /future/);
assert.throws(() => parseControlRequest({ ...request, dueAt: undefined }, now), /deadline/);
assert.throws(() => parseControlRequest({ ...request, reason: 'done' }, now), /reason/);
assert.throws(() => parseControlRequest({ ...request, status: 'verified' }, now), /working status/);
assert.throws(() => parseControlRequest({ ...request, action: 'own_gate', gateId: 'close:jobs', evidenceVersion: 'old' }, now), /evidence/);
assert.equal(parseControlRequest({ ...request, action: 'own_gate', gateId: 'close:jobs', evidenceVersion: 'a'.repeat(64) }, now).gateId, 'close:jobs');
assert.equal(canonicalControlInput({ action: 'handoff', details: { z: 1, a: 'note' }, absent: undefined }), canonicalControlInput({ details: { a: 'note', z: 1 }, action: 'handoff' }), 'A JSONB key-order change must not invalidate an identical retry.');
assert.notEqual(canonicalControlInput({ reason: 'original' }), canonicalControlInput({ reason: 'changed' }), 'Changed input cannot reuse a committed receipt.');
const gate = { id: 'close:fleet', count: null } as ControlGate;
assert.equal(controlGateCleared(gate), false, 'Missing evidence must never be source-ready.');
assert.equal(controlGateCleared({ ...gate, count: 0 }), true);
assert.equal(controlGateCleared({ ...gate, ownedBy: 'Operator' }), false, 'An owner label without durable work is insufficient.');
assert.equal(controlGateCleared({ ...gate, ownedBy: 'Operator', workItemId: 'work_synthetic' }), true, 'An explicit owned handoff can carry unknown evidence without claiming it is ready.');
assert.equal(controlItemActive({ status: 'snoozed' }), true, 'Waiting work stays open.');
assert.equal(controlItemActive({ status: 'resolved' }), false);
assert.equal(canTransitionWorkItem('resolved', 'in_progress'), false, 'Final work must reopen before editing.');
assert.equal(opsRoleCan('operator', CONTROL_ACTION_DEFINITIONS.close_day.permission), false);
assert.equal(opsRoleCan('manager', CONTROL_ACTION_DEFINITIONS.close_day.permission), true);
assert.equal(opsRoleCan('operator', CONTROL_ACTION_DEFINITIONS.handoff.permission), true);
assert.match(CONTROL_ACTION_DEFINITIONS.resolve_manually.verifier, /exact work-item version/);
assert.equal(controlReconciliationReady('2026-09-04', null, now), false);
assert.equal(controlReconciliationReady('2026-09-04', { appointments: [], employee_leaderboard: [] }, now), false, 'No fallback timestamp may authorize source resolution.');
const complete = { generated_at: now.toISOString(), appointments: [], employee_leaderboard: [], missing_inputs: [] };
assert.equal(controlReconciliationReady('2026-09-04', complete, now), true);
assert.equal(controlReconciliationReady('2026-09-04', { ...complete, missing_inputs: ['JunkWare'] }, now), false);
assert.equal(controlReconciliationReady('2026-09-04', { ...complete, generated_at: '2026-09-04T06:00:00Z' }, now), false);
console.log('Desktop Control contract checks passed: strict dates, deadlines, versions, supported actions, role permissions, honest unknown gates, durable handoff references, and JSONB-stable retry comparison. No database or source writes performed.');
