import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { enqueueWhatsAppImage, queuedWhatsAppImages, recentWhatsAppPhotoContext, recentWhatsAppText, recordWhatsAppTextContext, type WhatsAppImageMessage } from "@/lib/whatsapp-job-photo-queue";
import { matchesExactJkReference, matchWhatsAppPhoto } from "@/lib/whatsapp-job-photo-matching";
import { truckLoadPhotoRequest } from "@/lib/whatsapp-truck-loads";
const root = fs.mkdtempSync(path.join(os.tmpdir(), "photo-context-"));
const previous = process.env.WHATSAPP_JOB_PHOTO_STATE_DIR;
process.env.WHATSAPP_JOB_PHOTO_STATE_DIR = root;
const senderPhone = "5045550101";
const date = (seconds: number) => new Date(Date.UTC(2026, 8, 5, 15, 0, seconds));
const text = (messageId: string, seconds: number, body: string, phoneNumberId = "inbox-a") => recordWhatsAppTextContext({ messageId, senderPhone, receivedAt: date(seconds).toISOString(), phoneNumberId, text: body });
const read = (seconds: number, inbox = "inbox-a", exclude?: string) => recentWhatsAppText(senderPhone, date(seconds), 10, inbox, exclude);
const photo = (id: string, seconds: number, caption = ""): WhatsAppImageMessage => ({ version: 1, messageId: id, senderPhone, phoneNumberId: "inbox-a", receivedAt: date(seconds).toISOString(), enqueuedAt: date(seconds).toISOString(), mediaId: id, mimeType: "image/jpeg", sha256: "", caption });
try {
  text("job-a", 0, "JK4000001");
  text("before-caption", 1, "Before");
  enqueueWhatsAppImage(photo("before-caption", 1, "Before"));
  text("job-b", 5, "JK4000002");
  assert.equal(read(2), "Before JK4000001", "delayed webhook uses historical job, not newest job");
  assert.equal(read(1, "inbox-a", "before-caption"), "JK4000001", "own caption does not erase preceding job");
  const saved = JSON.parse(fs.readFileSync(queuedWhatsAppImages()[0], "utf8"));
  assert.equal(saved.matchingContext.text, "JK4000001", "later job cannot rebind queued photo");
  assert.equal(enqueueWhatsAppImage(photo("before-caption", 1)).duplicate, true);
  assert.equal(read(-1), "", "future context is excluded");
  text("other-inbox", 6, "JK4999999", "inbox-b");
  assert.equal(read(7), "JK4000002", "receiving inbox is isolated");
  assert.equal(recentWhatsAppText(senderPhone, date(7)), "", "legacy callers fail closed across inboxes");
  text("dump", 8, "Dump receipt");
  assert.equal(read(9), "Dump receipt", "expense context stops prior JK inheritance");
  text("truck", 10, "Truck 2");
  assert.equal(read(11), "Truck 2");
  text("same-second-a", 12, "JK4000003");text("same-second-b", 12, "JK4000004");
  assert.equal(read(13), "", "same-second conflicting JKs are ambiguous");
  assert.equal(recentWhatsAppPhotoContext(senderPhone, date(13), 10, "inbox-a").reviewReason, "ambiguous_context", "ambiguity must not fall through to GPS matching");
  text("same-second-a", 12, "JK4999999");
  assert.equal(read(13), "", "duplicate webhook cannot replace immutable history");
  text("job-c", 14, "JK4000005");text("category-c", 14, "Before");
  assert.equal(read(15), "Before JK4000005", "same-second category and job compose safely");
  text("after-c", 16, "After");
  assert.equal(read(17), "After JK4000005", "newest category replaces prior category");
  enqueueWhatsAppImage(photo("no-context", -1));
  text("late-context", -2, "JK4000006");
  const empty = queuedWhatsAppImages().map(p => JSON.parse(fs.readFileSync(p, "utf8"))).find(p => p.messageId === "no-context");
  assert.equal(empty.matchingContext.text, "", "late text does not silently bind an already queued photo");
  assert.equal(matchesExactJkReference("Appointment JK4000001", "JK4000001"), true);
  assert.equal(matchesExactJkReference("Appointment JK40000012", "JK4000001"), false);
  assert.equal(matchesExactJkReference("Appointment JK4000001 JK4000002", "JK4000001"), false);
  const input = { senderPhone, caption: "After JK4000001", recentText: "Before JK4000002", receivedAt: date(0), appointments: [], fleet: [], senderTruckMap: {} };
  const match = matchWhatsAppPhoto(input);
  assert.equal(matchWhatsAppPhoto({...input, caption: "", recentText: "After Before JK4000001"}).category, "after", "newer standalone category wins over category in older job text");
  assert.equal(match.status, "matched");if (match.status === "matched") {assert.equal(match.jkNumber, "JK4000001");assert.equal(match.category, "after");}
  assert.equal(matchWhatsAppPhoto({...input, caption: "JK4000001 JK4000002"}).status, "review");
  assert.equal(matchWhatsAppPhoto({...input, appointments: [{appt_id:"1",job_id:"JK4000001"},{appt_id:"2",job_id:"JK4000001"}]}).status,"review");
  assert.equal(truckLoadPhotoRequest(photo("explicit-job", 0, "JK4000001"), "Truck 2"), null);
  assert.deepEqual(truckLoadPhotoRequest(photo("explicit-truck", 0, "Truck 2"), "JK4000001"), {truck:"Truck# 2"});
  console.log("PASS: frozen job context, historical ordering, inbox isolation, category precedence, ambiguous jobs and truck routing");
} finally {
  if (previous === undefined) delete process.env.WHATSAPP_JOB_PHOTO_STATE_DIR; else process.env.WHATSAPP_JOB_PHOTO_STATE_DIR = previous;
  fs.rmSync(root, { recursive: true, force: true });
}
