import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { INSPECTION_SECTIONS, type TruckInspectionReport } from '../lib/truck-inspection';
import { inspectionLoadEvents, inspectionFleetEvidence } from '../lib/truck-inspection-fleet';
import { deriveCloseoutTruckLoads, readOperationalTruckLoads, truckChargeSummary } from '../lib/truck-load-closeouts';
import { submitTruckInspection, connectInspectionPhone } from '../lib/truck-inspection-store';
import { readDesktopFleet } from '../lib/desktop-fleet';
const date='2026-09-16';
const report:TruckInspectionReport={version:2,truck:'Truck 3',inspector:'Fixture',initials:'FX',odometer:'12345',fuel:'1/2',loadLevel:'3/4',startedAt:`${date}T12:00:00Z`,receivedAt:`${date}T12:20:00Z`,inspectionDate:date,deviceId:randomUUID(),requestId:randomUUID(),answers:INSPECTION_SECTIONS.map(s=>({id:s.id,status:'good',notes:''})),status:'clear',photos:[],notes:''};
const observation=inspectionLoadEvents([report])[0];
const previous=deriveCloseoutTruckLoads('2026-09-15',['3'],[{...observation,eventId:'old',date:'2026-09-15',kind:'day_start',loadFraction:0}],[])[0];
previous.needsVerification=true;previous.verificationNote='Old unplaced load';
const derive=(events=[observation])=>deriveCloseoutTruckLoads(date,['3'],events,[],[],0,[previous])[0];
assert.equal(derive().currentLoadFraction,.75);
assert.equal(derive().needsVerification,false);
assert.match(truckChargeSummary(derive()),/Inspection baseline 3\/4/);
assert.doesNotMatch(truckChargeSummary(derive()),/Starting load carried/);
assert.equal(derive([{...observation,eventId:'pickup',kind:'job_closeout',loadFraction:.25,occurredAt:`${date}T13:00:00Z`,appointmentId:'1234'},observation]).currentLoadFraction,1,'Later pickup adds to inspection');
assert.equal(derive([{...observation,eventId:'dump',kind:'yard_reset',loadFraction:0,occurredAt:`${date}T13:00:00Z`},observation]).currentLoadFraction,0,'Later unload wins');
assert.match(truckChargeSummary(derive([{...observation,eventId:'dump',kind:'yard_reset',loadFraction:0,occurredAt:`${date}T13:00:00Z`},observation])),/Later unload reset/);
assert.equal(derive([{...observation,recordedAt:`${date}T23:00:00Z`},{...observation,eventId:'later',loadFraction:.5,occurredAt:`${date}T14:00:00Z`}]).currentLoadFraction,.5,'Late upload cannot erase a newer observation');
assert.equal(inspectionLoadEvents([{...report,version:1,loadLevel:undefined}]).length,0);
assert.equal(inspectionLoadEvents([{...report,loadLevel:'Empty'}])[0].loadFraction,0);
assert.equal(deriveCloseoutTruckLoads('2026-09-17',['3'],[],[],[],0,[derive()])[0].currentLoadFraction,.75);
assert.equal(inspectionFleetEvidence([report],'Truck# 3')?.label,'Complete');
assert.equal(inspectionFleetEvidence([{...report,status:'stop'}, {...report,requestId:randomUUID(),startedAt:`${date}T13:00:00Z`}],'3')?.stop,true);
assert.equal(inspectionFleetEvidence([{...report,answers:report.answers.map((a,i)=>({...a,notes:i===0?'Bent rim':''}))}],'3')?.problem,true);
const defect = {...report, status: 'reported' as const, notes: 'Check before next route.', answers: report.answers.map((answer, index) => index === 1 ? {...answer, status: 'problem' as const, notes: 'Rear tire has a cut.'} : answer)};
assert.deepEqual(inspectionFleetEvidence([defect], '3')?.findings, [
 {label: 'Wheels & tires', notes: 'Rear tire has a cut.'}, {label: 'Inspector notes', notes: 'Check before next route.'},
]);
assert.equal(inspectionFleetEvidence([defect], '4'), null, 'Findings cannot leak across trucks');
assert.deepEqual(inspectionFleetEvidence([report], '3')?.findings, []);
assert.equal(inspectionFleetEvidence([{...defect, status: 'stop'}, {...report, startedAt: `${date}T14:00:00Z`}], '3')?.findings[0].notes, 'Rear tire has a cut.', 'A later clear inspection cannot hide the stop report findings');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'inspection-fleet-'));
const cwd=process.cwd();
try {
 process.env.OPSCENTER_DATA_DIR=path.join(root,'data'); delete process.env.OPS_TRUCK_INSPECTION_DIR;
 process.chdir(root);
 const now=new Date(report.receivedAt);const device=connectInspectionPhone('b'.repeat(64),now).device;
 for(const [truck,loadLevel] of [['Truck 2','1/2'],['Truck 3','3/4'],['Truck 4','Full'],['Truck 8','Full'],['Truck 9','3/4']]) submitTruckInspection({...report,requestId:randomUUID(),truck,loadLevel},device,now);
 fs.writeFileSync(path.join(root,'data','fleet','repair_issues.json'),JSON.stringify({version:1,issues:[]}));
 const loads=readOperationalTruckLoads(date,[],[]);
 assert.deepEqual(loads.map(r=>[r.truck,r.capacityPercent]),[['Truck# 2',50],['Truck# 3',75],['Truck# 4',100],['Truck# 8',100],['Truck# 9',75]]);
 assert.equal(readOperationalTruckLoads('2026-09-17',[],[]).find(r=>r.truck==='Truck# 3')?.capacityPercent,75,'Inspection-only history participates in carry-forward');
 submitTruckInspection({...defect, truck:'Truck 4',requestId:randomUUID(),photos:[{section:'wheels-tires',data:'data:image/jpeg;base64,/9j/AA=='}]},device,now);
 const fleet=readDesktopFleet(date,'overview','admin');
 assert.deepEqual(fleet.trucks.find(t=>t.id==='Truck# 4')?.inspectionFindings, inspectionFleetEvidence([defect],'3')?.findings);
 assert.deepEqual(fleet.trucks.find(t=>t.id==='Truck# 3')?.inspectionFindings, []);
 assert.ok(!JSON.stringify(fleet).includes('photos'), 'Desktop projection excludes inspection photo payloads');
 assert.equal(fleet.trucks.find(t=>t.id==='Truck# 3')?.checklist,'Complete');
 assert.equal(fleet.trucks.find(t=>t.id==='Truck# 3')?.loadPercent,75);
 assert.equal(fleet.trucks.find(t=>t.id==='Truck# 3')?.readiness,'Ready');
 console.log('Inspection Fleet checks passed: exact morning values, carry replacement, later pickups/unloads, late uploads, historical carry, readiness and legacy reports.');
} finally {process.chdir(cwd);fs.rmSync(root,{recursive:true,force:true});}
