import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { INSPECTION_SECTIONS, inspectionDate, validateTruckInspection } from "../lib/truck-inspection";
import { createInspectionPairing, pairInspectionPhone, inspectionDevice, submitTruckInspection, findTruckInspection, listTruckInspections, revokeInspectionDevice } from "../lib/truck-inspection-store";
import { inspectionRequestBody } from "../lib/truck-inspection-http";
import { publicAuthRoute } from "../lib/auth";
const directory = fs.mkdtempSync(path.join(os.tmpdir(), "truck-inspection-test-"));
process.env.OPS_TRUCK_INSPECTION_DIR = directory;
const now = new Date("2026-09-15T13:00:00Z");
const valid = () => ({ requestId: randomUUID(), inspector: "Test inspector", odometer: "123456", fuel: "1/2", startedAt: now.toISOString(), answers: INSPECTION_SECTIONS.map(s => ({ id: s.id, status: "good", notes: "" })), status: "clear", notes: "", initials: "TI", photos: [] });
async function main() { try {
  const pairing = createInspectionPairing("Truck 4", "Synthetic truck phone", "manager@example.invalid", now);
  const phone = pairInspectionPhone(pairing.code, now);
  assert.equal(inspectionDevice(phone.token, now)?.truck, "Truck 4");
  assert.equal(inspectionDevice("bad", now), null);
  assert.throws(() => pairInspectionPhone(pairing.code, now), /already used/);
  assert.throws(() => pairInspectionPhone(createInspectionPairing("Truck 2", "Expired phone", "test", now).code, new Date(now.getTime() + 86400_001)), /expired/);
  const raw = valid(); const saved = submitTruckInspection({ ...raw, truck: "Truck 8" }, phone.device, now);
  assert.equal(saved.truck, "Truck 4", "truck must come from the device, not client input");
  assert.deepEqual(submitTruckInspection(raw, phone.device, new Date(now.getTime() + 1000)), saved);
  assert.equal(listTruckInspections("2026-09-15").length, 1);
  assert.deepEqual(findTruckInspection(phone.device.deviceId, raw.requestId), saved);
  assert.equal(findTruckInspection(randomUUID(), raw.requestId), null, "another device cannot read a report");
  assert.throws(() => submitTruckInspection({ ...raw, odometer: "999" }, phone.device, now), /different answers/);
  assert.throws(() => validateTruckInspection({ ...valid(), answers: [] }, now), /five sections/);
  assert.throws(() => validateTruckInspection({ ...valid(), answers: Array(5).fill(raw.answers[0]) }, now), /Check/);
  assert.throws(() => validateTruckInspection({ ...valid(), odometer: "" }, now), /mileage/);
  assert.throws(() => validateTruckInspection({ ...valid(), odometer: "1e4" }, now), /whole number/);
  const problem = valid(); problem.answers[0].status = "problem";
  assert.throws(() => validateTruckInspection(problem, now), /note/);
  problem.answers[0].notes = "Fluid leak";
  assert.throws(() => validateTruckInspection(problem, now), /problem was marked/);
  problem.status = "stop";
  assert.equal(submitTruckInspection(problem, phone.device, now).status, "stop");
  assert.throws(() => validateTruckInspection({ ...valid(), status: "stop" }, now), /notes/);
  assert.throws(() => validateTruckInspection({ ...valid(), photos: [{ section: "walk-around", data: "data:image/svg+xml,<svg/>" }] }, now), /JPEG/);
  assert.equal(inspectionDate(new Date("2026-09-15T03:00:00Z")), "2026-09-14");
  assert.throws(() => validateTruckInspection({ ...valid(), startedAt: "2026-09-01T13:00:00Z" }, now), /seven days/);
  const dailyDir = path.join(directory, "dates", "2026-09-15"); fs.rmSync(dailyDir, { recursive: true });
  findTruckInspection(phone.device.deviceId, raw.requestId);
  assert.equal(listTruckInspections("2026-09-15").length, 1, "receipt lookup repairs an interrupted date index");
  revokeInspectionDevice(phone.device.deviceId, "manager@example.invalid");
  assert.equal(inspectionDevice(phone.token, now), null);
  await assert.rejects(() => inspectionRequestBody(new Request("https://example.invalid/api/truck-inspection", { method: "POST", headers: { "Content-Type": "text/plain" }, body: "{}" })), /JSON/);
  await assert.rejects(() => inspectionRequestBody(new Request("https://example.invalid/api/truck-inspection", { method: "POST", headers: { "Content-Type": "application/json", Origin: "https://evil.invalid" }, body: "{}" })), /inspection app/);
  await assert.rejects(() => inspectionRequestBody(new Request("https://example.invalid/api/truck-inspection", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: "X".repeat(100) }) }), 10), /too large/);
  for (const route of ["/truck-inspection", "/api/truck-inspection", "/truck-inspection/manifest.webmanifest"]) assert.equal(publicAuthRoute(route), true);
  for (const route of ["/truck-inspection/admin", "/api/fleet-inspections", "/fleet-inspections"]) assert.equal(publicAuthRoute(route), false);
  console.log("Truck inspection storage, validation, retry, identity and request boundary checks passed.");
} finally { fs.rmSync(directory, { recursive: true, force: true }); } }
void main().catch(error => { console.error(error); process.exitCode = 1; });
