import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { appendRecyclingReceiptPhoto, readRecyclingData } from '../lib/recycling-receipt-store';
import { recordReviewedRecyclingReceipt } from '../lib/recycling-receipt-review';
import { parseRecyclingPurchaseTicket } from '../lib/recycling-purchase-ticket';
import { recyclingMonth } from '../desktop-ui/lib/recycling-month';
import { recyclingMatchStatus } from '../desktop-ui/lib/recycling-reconciliation';
import { buildRecyclingSlackAlerts } from '../lib/recycling-slack';
import type { CommercialOperation } from '../desktop-ui/lib/commercial-contract';
import type { RecyclingReceiptLine } from '../desktop-ui/lib/recycling-receipts';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'recycling-deliveries-'));
const oldEnv = process.env.OPSCENTER_DESKTOP_COMMERCIAL_DIR;
process.env.OPSCENTER_DESKTOP_COMMERCIAL_DIR = root;
const actor = { email: 'reviewer@example.invalid', role: 'manager' as const };
const ticketText = 'European Metal Recycling Ltd\nPurchase Ticket\nTicket No/Depot: 1234501 TEST\nDate/Time\n: 14-Sep-26 08:18\nPaid UM\n2,140 LB\nFRAG FEED\nTOTALS\nLB\n2,140';
const rows = parseRecyclingPurchaseTicket(ticketText);
function operation(id: string, lines: RecyclingReceiptLine[], kind: 'delivery' | 'statement', total: number | null): CommercialOperation {
  const photoId = crypto.createHash('sha256').update(id).digest('hex');
  const draft = appendRecyclingReceiptPhoto(id, { photoId, mimeType:'image/jpeg', receivedAt:'2026-09-14T13:00:00Z', text: '', rows: lines, total, warnings: [] }, 'Test yard');
  return { requestId: crypto.randomUUID(), date: '2026-09-14', action: 'recycling.receipt.record', recordId: draft.id, expectedVersion:draft.version, values: {kind, rows: lines, total, reviewed:true, paid:false, yard:'Test yard'} };
}
try {
  assert.deepEqual(rows, [{date:'2026-09-14',ticket:'1234501',material:'FRAG FEED',weightLb:2140,amount:null}]);
  assert.deepEqual(parseRecyclingPurchaseTicket(ticketText.replace('14-Sep','31-Sep')), []);
  assert.deepEqual(parseRecyclingPurchaseTicket(ticketText + '\n200 LB\nCOPPER'), [], 'Ambiguous multi-material receipt remains manual');
  assert.deepEqual(parseRecyclingPurchaseTicket(ticketText + '\nTicket No/Depot: 1234567 OTHER'), []);
  const legacy = appendRecyclingReceiptPhoto('legacy', {photoId:'a'.repeat(64),mimeType:'image/jpeg',receivedAt:'2026-09-14T13:00:00Z',text:ticketText,rows:[],total:null,warnings:['old unsupported layout']},'Test yard');
  assert.equal(legacy.kind,'delivery'); assert.equal(legacy.rows[0].weightLb,2140, 'Previously received tickets recover from saved OCR without downloads');
  const delivery = operation('delivery',rows,'delivery',null);
  assert.throws(()=>recordReviewedRecyclingReceipt({...delivery,values:{...delivery.values,paid:true}},actor), /cannot record income/);
  assert.throws(()=>recordReviewedRecyclingReceipt({...delivery,values:{...delivery.values,reviewed:false}},actor), /checked/);
  assert.throws(()=>recordReviewedRecyclingReceipt({...delivery,values:{...delivery.values,total:0}},actor), /cannot record income/);
  assert.equal(recordReviewedRecyclingReceipt(delivery,actor).status,'verified');
  assert.equal(recordReviewedRecyclingReceipt(delivery,actor).status,'verified','Same request is idempotent');
  let record = readRecyclingData().records[0]; const id = record.id;
  assert.equal(record.expectedValue,null);assert.equal(record.realizedValue,null);assert.equal(record.status,'Submitted');assert.equal(record.netWeightLb,2140);
  assert.equal(recyclingMonth([record],'2026-09').unmatched.length,1);
  assert.equal(recyclingMonth([record],'2026-09').receivedValue,0);
  const alerts = buildRecyclingSlackAlerts(readRecyclingData());
  assert.match(alerts.find(alert=>alert.id==='receipt:delivery')!.text,/Delivery Recorded/);
  assert.match(alerts.find(alert=>alert.id==='receipt:delivery')!.text,/Awaiting monthly cash-out/);
  const duplicate = operation('duplicate',rows,'delivery',null);
  assert.throws(()=>recordReviewedRecyclingReceipt(duplicate,actor), /already recorded/);
  const statementRows = [{...rows[0], amount:210, weightLb:2100}, {...rows[0],ticket:'1234502',amount:10,weightLb:100}];
  const statement = operation('cash-out',statementRows,'statement',220);
  assert.throws(()=>recordReviewedRecyclingReceipt(statement,actor),/changed/,'Match requires the version reviewed by the operator');
  statement.values.recordVersions = {[record.id]:record.version};
  statement.values.paid = true;statement.values.paymentDate='2026-10-03';statement.values.paymentReference='Monthly cash-out cash receipt';
  assert.throws(()=>recordReviewedRecyclingReceipt({...statement,values:{...statement.values,total:221}},actor),/equal/);
  assert.equal(recordReviewedRecyclingReceipt(statement,actor).status,'verified');
  assert.match(buildRecyclingSlackAlerts(readRecyclingData()).find(alert=>alert.id==='receipt:delivery')!.text,/Weight mismatch/);
  const store = readRecyclingData();assert.equal(store.records.length,2, 'Matching updates delivery rather than duplicating income');
  record = store.records.find(r=>r.id===id)!;
  assert.equal(record.netWeightLb,2140,'Original delivered weight survives statement mismatch');assert.equal(record.statementWeightLb,2100);
  assert.equal(record.deliveryLines![0].weightLb,2140);assert.equal(record.statementLines![0].weightLb,2100);
  assert.match(recyclingMatchStatus(record),/Weight mismatch/);
  const september = recyclingMonth(store.records,'2026-09');
  assert.equal(september.unmatched.length,0);assert.equal(september.matched.length,1);assert.equal(september.weightExceptions.length,1);assert.equal(september.statementOnly.length,1);assert.equal(september.runValue,220);assert.equal(september.receivedValue,0);
  assert.equal(recyclingMonth(store.records,'2026-10').receivedValue,220, 'Cash counted once in receipt month');
  const replay = operation('cash-out-copy',statementRows,'statement',220);
  assert.throws(()=>recordReviewedRecyclingReceipt(replay,actor),/already matched|already recorded/);
  const otherDelivery = operation('missing-from-statement',[{...rows[0],ticket:'1234599'}],'delivery',null);
  recordReviewedRecyclingReceipt(otherDelivery,actor);
  assert.equal(recyclingMonth(readRecyclingData().records,'2026-09').unmatched.length,1, 'Omitted tickets remain open after cash-out');
  const laterDelivery = operation('late-delivery',[{...rows[0],ticket:'1234502',weightLb:100}],'delivery',null);
  const statementOnly = readRecyclingData().records.find(row=>row.ticket==='1234502')!;
  laterDelivery.values.recordVersions = {[statementOnly.id]:statementOnly.version};
  assert.equal(recordReviewedRecyclingReceipt(laterDelivery,actor).status,'verified');
  const linked = readRecyclingData().records.find(row=>row.id===statementOnly.id)!;
  assert.equal(linked.realizedValue,10);assert.equal(linked.paymentDate,'2026-10-03');assert.equal(linked.status,'Paid');
  assert.equal(recyclingMonth(readRecyclingData().records,'2026-09').statementOnly.length,0);
  const duplicateLines = operation('duplicate-lines',[{...rows[0],ticket:'9999999'},{...rows[0],ticket:'9999999'}],'delivery',null);
  assert.throws(()=>recordReviewedRecyclingReceipt(duplicateLines,actor),/Duplicate delivery lines/);
  const changedYard = operation('other-yard',[{...rows[0],ticket:'1234501'}],'delivery',null);
  changedYard.values.yard='Different yard';
  assert.equal(recordReviewedRecyclingReceipt(changedYard,actor).status,'verified','Ticket numbers are yard scoped');
  console.log('Recycling deliveries: purchase-ticket recovery, no invented values, reviewed writes, duplicate and stale-match guards, statement reconciliation, preserved weight differences, unmatched tickets, yard scope, exact cash totals and payment month passed.');
} finally { if(oldEnv===undefined)delete process.env.OPSCENTER_DESKTOP_COMMERCIAL_DIR;else process.env.OPSCENTER_DESKTOP_COMMERCIAL_DIR=oldEnv;fs.rmSync(root,{recursive:true,force:true}); }
