import assert from 'node:assert/strict';
import { crewAssignedDay,crewAppointmentStatus,crewScheduleAssignmentId } from '../lib/crew-assigned-day';
import type { CrewPhone } from '../lib/crew-phone';

const date='2026-09-22',now=Date.parse(`${date}T18:00:00Z`);
const phone={deviceId:'test-phone',truck:'Truck 1'} as CrewPhone;
const row=(id:string,truck='Truck# 1',status='Confirmed')=>({appt_id:id,job_id:`JK${id}`,truck,job_status:status,customer_name:`Customer ${id}`,address:`${id} Example Street`,appointment_time:'09:00 AM - 10:00 AM'});
let snapshot={date,scrapedAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString(),updatedAtMs:now,freshnessAtMs:now,appointments:[row('100'),row('101'),row('102','Truck 2'),row('103','Truck 1','Completed')],cancelled:[row('104','Truck 1','Cancelled')]};
const overrides=new Map();
let resetToken:string|null=null;
const deps={snapshot:()=>snapshot,rows:()=>[],overrides:()=>overrides,dispatch:()=>({truck:'Truck 1',version:1,current:{assignmentId:'released-100',appointmentId:'100',date,releasedAt:new Date(now).toISOString()},queued:null}),reset:(truck:string,resetDate:string,id:string)=>resetToken&&id==='101'?{appointmentId:id,date:resetDate,truck,priorAssignmentId:crewScheduleAssignmentId(truck,resetDate,id),token:resetToken,resetAt:new Date(now).toISOString(),actor:'test'}:null};
const result=crewAssignedDay(phone,date,deps,now);
assert.equal(result.state,'assigned');
assert.deepEqual(result.jobs?.map(job=>job.appointmentId),['100','101','103'],'All truck jobs are visible without a separate release, including completed work');
assert.equal(result.job?.assignmentId,'released-100');
assert.equal(result.jobs?.find(job=>job.appointmentId==='101')?.assignmentId,crewScheduleAssignmentId('Truck# 1',date,'101'),'Every fresh truck-day appointment has stable closeout scope');
assert.equal(crewScheduleAssignmentId('Truck 1',date,'101'),crewScheduleAssignmentId('Truck #1',date,'101'),'Truck label variants retain one closeout scope');
resetToken='11111111-1111-4111-8111-111111111111';
const reset=crewAssignedDay(phone,date,deps,now).jobs?.find(job=>job.appointmentId==='101');
assert.notEqual(reset?.assignmentId,crewScheduleAssignmentId('Truck 1',date,'101'),'A reset rotates only the appointment closeout scope');
assert.equal(reset?.resetPriorAssignmentId,crewScheduleAssignmentId('Truck 1',date,'101'));
resetToken=null;
assert.equal(JSON.stringify(result).includes('Customer 102'),false,'Other truck customer data never leaves the server');
assert.equal(JSON.stringify(result).includes('Customer 104'),false,'Canceled appointments are excluded');
overrides.set('appt:102',{truck:'Truck 1',junkwareSyncStatus:'verified',junkwareVerifiedAt:new Date(now+1).toISOString(),appointmentTime:'11:00 AM - 12:00 PM'});
const immediate=crewAssignedDay(phone,date,deps,now);
assert.equal(immediate.jobs?.find(job=>job.appointmentId==='102')?.appointmentTime,'11:00 AM - 12:00 PM','A newer source-verified move reaches the phone before the next full schedule scrape');
assert.notEqual(immediate.updateToken,result.updateToken,'Assignment changes produce a new local update token');
overrides.clear();
overrides.set('appt:102',{truck:'Truck 1',junkwareSyncStatus:'verified',junkwareVerifiedAt:new Date(now-1).toISOString()});
assert.equal(crewAssignedDay(phone,date,deps,now).jobs?.some(job=>job.appointmentId==='102'),false,'A newer full source snapshot supersedes an older assignment receipt');
overrides.clear();
overrides.set('appt:101',{truck:'Truck 2',junkwareSyncStatus:'pending'});
assert.deepEqual(crewAssignedDay(phone,date,deps,now).jobs?.map(job=>job.appointmentId),['100','103'],'A pending move is withheld');
overrides.clear();
snapshot={...snapshot,appointments:[...snapshot.appointments,row('101')]};
assert.equal(crewAssignedDay(phone,date,deps,now).jobs?.some(job=>job.appointmentId==='101'),false,'Ambiguous identities are withheld');
snapshot={...snapshot,freshnessAtMs:now-121_000};
assert.equal(crewAssignedDay(phone,date,deps,now).state,'unavailable','Stale source fails promptly without opening a browser');
snapshot={...snapshot,freshnessAtMs:now+1};
assert.equal(crewAssignedDay(phone,date,deps,now).state,'unavailable');
snapshot={...snapshot,freshnessAtMs:now,appointments:[row('101')],cancelled:[]};
assert.equal(crewAssignedDay(phone,date,deps,now).jobs?.length,1,'An old or missing current release does not hide scheduled jobs');
snapshot={...snapshot,appointments:[{...row('103','Truck 1','Completed'),appointment_type:'Estimate',closeout:{total:'568.00'},appointment_notes:['Other: Training only, no discount: internal test (9/22/2026)']} as ReturnType<typeof row>]};
const closed=crewAssignedDay(phone,date,deps,now).jobs![0];
assert.equal(closed.appointmentType,'Estimate');assert.equal(closed.closedTotal,568);
assert.deepEqual(closed.estimateOutcomes,['Other: Training only, no discount: internal test (9/22/2026)']);
snapshot={...snapshot,appointments:[{...snapshot.appointments[0],job_status:'Completed Duration: 585 min(s)'}]};
const withDuration=crewAssignedDay(phone,date,deps,now).jobs![0];
assert.equal(withDuration.status,'Completed');assert.equal(withDuration.closedTotal,568);
snapshot={...snapshot,appointments:[{...row('105','Truck 1','Completed'),appointment_type:'Job',closeout:{loadQuantity:1,loadSize:'Full truck',loadPrice:728,bedloadQuantity:0,bedloadSize:'',bedloadPrice:0,otherCharges:[{name:'Labor',quantity:2,unitPrice:75,total:150},{name:'CC Surcharge (Card Present)',quantity:1,unitPrice:26.34,total:26.34}],discount:0,tip:0,total:904.34,payments:[{method:'Credit Card',detail:'4111111111112868',amount:904.34}],balance:0}} as ReturnType<typeof row>]};
const completedJob=crewAssignedDay(phone,date,deps,now).jobs![0];
assert.deepEqual(completedJob.closeout?.otherCharges.map(charge=>charge.name),['Labor','CC Surcharge (Card Present)']);
assert.equal(completedJob.closeout?.payments[0].detail,'2868','Only the card last four leave the server projection');
assert.equal(crewAppointmentStatus('Not Completed'),null);
assert.equal(crewAppointmentStatus('Cancelled'),null);
snapshot={...snapshot,appointments:[{...snapshot.appointments[0],job_status:'Confirmed'}]};
assert.equal(crewAssignedDay(phone,date,deps,now).jobs![0].closedTotal,undefined,'An open appointment never claims a saved closeout amount');
console.log('PASS: full assigned day with closeout scope, immediate verified assignment projection and update token, truck isolation, source freshness, pending move exclusion and duplicate identity rejection; no provider calls.');
