import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { validateMerchantSnapshot, readMerchantSnapshot, reconcileMerchantEvidence, type MerchantSnapshot } from '../lib/merchant-center-evidence';
import type { PaymentByJobRow, PaymentReconciliation } from '../lib/payment-reconciliation';
const date = '2026-09-10', observedAt = '2026-09-11T16:00:00Z', now = Date.parse(observedAt);
const row: PaymentByJobRow = { date, jkNumber:'JK4000001',customer:'Example Person',paymentMethod:'Credit Card',cardLastFour:'1234',paidAmount:120,revenueAmount:120,tipAmount:0,qboTransactionId:null,qboTransactionType:null,qboStatus:null,reconciliation:'Missing in QBO' };
const transaction = {date,transactionId:'processor-1',amount:120,cardLastFour:'1234',customer:'Example Person',jkNumber:'JK4000001',status:'Approved',transactionType:'Sale',fee:4,observedAt};
const snapshot: MerchantSnapshot = {schema:1,date,collector:'merchant-center-export',accountName:'Junk Krewe',accountLastFour:'4618',collectedAt:observedAt,complete:true,transactions:[transaction]};
const run = (rows=[row], s:MerchantSnapshot|null=snapshot) => reconcileMerchantEvidence(rows,null,s,null,now);
assert.equal(validateMerchantSnapshot(snapshot,date),snapshot);
assert.throws(()=>validateMerchantSnapshot({...snapshot,accountLastFour:'0000'},date));
assert.throws(()=>validateMerchantSnapshot({...snapshot,collector:'qbo-accounting-api'},date));
assert.throws(()=>validateMerchantSnapshot({...snapshot,transactions:[transaction,transaction]},date));
assert.throws(()=>validateMerchantSnapshot({...snapshot,transactions:[{...transaction,amount:NaN}]},date));
const result=run();
assert.equal(result.paymentsByJob[0].processor?.state,'approved');
assert.equal(result.paymentsByJob[0].qboTransactionId,null,'Approval cannot invent an accounting record');
assert.equal(result.paymentsByJob[0].reconciliation,'Missing in QBO','Accounting exception remains');
assert.equal(result.processor.approvedTotal,120);
assert.equal(result.processor.unmatched.length,0);
assert.equal(run([{...row,paidAmount:121}]).paymentsByJob[0].processor?.state,'not_found','Never clear unequal totals');
assert.equal(run([{...row,cardLastFour:'4321'}]).paymentsByJob[0].processor?.state,'not_found','Conflicting card blocks JK match');
assert.equal(run([{...row,jkNumber:'JK4000002'}]).paymentsByJob[0].processor?.state,'not_found','Conflicting job blocks amount/card match');
assert.equal(run([row,{...row}]).paymentsByJob[0].processor?.state,'ambiguous','No processor transaction can be assigned twice');
assert.equal(run([row],{...snapshot,transactions:[transaction,{...transaction,transactionId:'processor-2'}]}).paymentsByJob[0].processor?.state,'ambiguous','Do not arbitrarily choose duplicate charges');
assert.equal(run([row],{...snapshot,transactions:[{...transaction,status:'Declined'}]}).paymentsByJob[0].processor?.state,'review');
assert.equal(run([row],{...snapshot,transactions:[{...transaction,transactionType:'Refund'}]}).processor.approvedTotal,0);
assert.equal(run([row],{...snapshot,transactions:[{...transaction,status:'Unknown'}]}).processor.approvedTotal,0);
assert.equal(run([row],null).paymentsByJob[0].processor?.state,'unavailable');
assert.equal(run([row],{...snapshot,complete:false,transactions:[]}).paymentsByJob[0].processor?.state,'unavailable','Partial coverage cannot establish absence');
assert.equal(reconcileMerchantEvidence([row],null,snapshot,null,now+25*3600_000).paymentsByJob[0].processor?.fresh,false);
assert.equal(run([{...row,qboTransactionId:'qbo-1',reconciliation:'Matched'}]).paymentsByJob[0].qboTransactionId,'qbo-1');
const qbo = {sources:{merchant_center:{collector:'qbo-accounting-api'}},matches:[],exceptions:{merchant_center_only:[{date,transaction_id:'qbo-2',amount:120,card_last_four:'1234'}]}} as unknown as PaymentReconciliation;
assert.equal(reconcileMerchantEvidence([],qbo,snapshot,null,now).processor.unmatched[0].qboTransactionId,'qbo-2');
const original=process.env.OPSBOT_DATA_DIR, temp=fs.mkdtempSync(path.join(os.tmpdir(),'merchant-evidence-test-'));
try {
 process.env.OPSBOT_DATA_DIR=temp;
 assert.equal(readMerchantSnapshot(date).snapshot,null);
 const directory=path.join(temp,'imports/merchant_center/junk_krewe');fs.mkdirSync(directory,{recursive:true});
 fs.writeFileSync(path.join(directory,`transactions-${date}.json`),JSON.stringify(snapshot));
 assert.equal(readMerchantSnapshot(date).snapshot?.complete,true);
 const details={...snapshot,collector:'merchant-center-detail',complete:false,collectedAt:'2026-09-11T17:00:00Z',transactions:[{...transaction,status:'Voided',observedAt:'2026-09-11T17:00:00Z'}]};
 fs.writeFileSync(path.join(directory,`details-${date}.json`),JSON.stringify(details));
 assert.equal(readMerchantSnapshot(date).snapshot?.transactions[0].status,'Voided','Later detail supersedes prior approved observation');
 assert.equal(readMerchantSnapshot(date).snapshot?.complete,false);
 assert.equal(readMerchantSnapshot('../bad').snapshot,null);
} finally {if(original===undefined)delete process.env.OPSBOT_DATA_DIR;else process.env.OPSBOT_DATA_DIR=original;fs.rmSync(temp,{recursive:true,force:true});}
console.log('Merchant evidence passed: source identity, independent posting, conservative matches, duplicate claims, non-sales, stale/partial evidence, and later voids.');
