import assert from 'node:assert/strict';
import { financePerformance, financeChange, performanceExplanation } from '../desktop-ui/lib/finance-performance';
import { financeTrendComparisons, fromFinanceMonth } from '../lib/finance-trend-comparison';
import type { FinanceData } from '../desktop-ui/lib/commercial-contract';
const month = (key: string, revenue: number, jobs: number, sales = revenue): FinanceData['trends'][number] => ({ monthKey: key, monthDisplay: key, dataThroughDate: key + '-31', complete: true, reportingComplete: true, grossRevenue: revenue, completedJobs: jobs, operatingRevenue: sales, recyclingIncome: 0, totalOperatingExpenses: sales * .4, estimatedOperatingProfit: sales * .6, revenueSource: 'fixture', missingDates: [] });
const trends = [month('2025-01', 800, 8), month('2025-02', 1200, 4), month('2026-01', 1000, 5, 900), month('2026-02', 1600, 8, 1400)];
const data = { trends, trendComparisons: financeTrendComparisons(trends, () => null) };
const feb = financePerformance(data, '2026-02', 'month', 'prior');
assert.equal(feb.current.revenue, 1600); assert.equal(feb.prior.revenue, 1000);
assert.equal(feb.current.margin, 60, 'Profit must use its own sales basis, not dashboard revenue');
assert.equal(feb.revenueDifference, 200); assert.equal(feb.current.profit, 840);
const ytd = financePerformance(data, '2026-02', 'ytd', 'prior');
assert.equal(ytd.current.revenue, 2600); assert.equal(ytd.current.jobs, 13);
assert.equal(ytd.current.averageJob, 200); assert.equal(ytd.prior.averageJob, 2000 / 12);
assert.equal(ytd.current.margin, 60); assert.equal(ytd.prior.margin, 60);
assert.equal(ytd.start, '2026-01-01'); assert.equal(ytd.priorStart, '2025-01-01');
assert.equal(ytd.end, '2026-02-28'); assert.equal(ytd.priorEnd, '2025-02-28');
const missing = financePerformance({ ...data, trends: trends.filter(m => m.monthKey !== '2026-01') }, '2026-02', 'ytd', 'year');
assert.equal(missing.current.revenue, null); assert.equal(missing.missingMonths, 1);
const daily = (date: string) => ({ total_revenue: date.startsWith('2025') ? 50 : 100, sales: 90, jobs_by_market: { A: 2 }, total_expenses: 30, net_profit: 60 });
const partial = { ...month('2026-03', 900, 18), dataThroughDate: '2026-03-06', complete: false, reportingComplete: false };
const partialData = { trends: [partial], trendComparisons: financeTrendComparisons([partial], daily) };
const mismatch = financePerformance(partialData, '2026-03', 'month', 'year');
assert.equal(mismatch.current.revenue, 900); assert.equal(mismatch.prior.revenue, null, 'Do not attach a delta for 600 daily revenue to a 900 monthly headline');
const missingDaily = { ...partial, operatingRevenue: null, totalOperatingExpenses: null, estimatedOperatingProfit: null, missingDates: ['2026-03-03'] };
assert.equal(fromFinanceMonth(missingDaily).margin, null);
const fullAuthority = { ...month('2025-03', 4000, 20), complete: false, reportingComplete: true, totalOperatingExpenses: null, estimatedOperatingProfit: null, operatingRevenue: null };
assert.equal(financeTrendComparisons([fullAuthority], () => null)['2025-03'].currentEnd, '2025-03-31', 'Full-month authority is not mislabeled as partial daily history');
assert.equal(financeChange('revenue', 100, 0)?.percent, null);
assert.equal(financeChange('revenue', 0, 0)?.percent, 0);
assert.equal(financeChange('margin', 50, 40)?.difference, 10);
assert.match(performanceExplanation(fromFinanceMonth(month('2026-02', 800, 10)), fromFinanceMonth(month('2026-01', 1000, 10))), /Average job value contributed more/);
assert.match(performanceExplanation(fromFinanceMonth(month('2026-02', 800, 8)), fromFinanceMonth(month('2026-01', 1000, 10))), /Job count contributed more/);
assert.match(performanceExplanation(fromFinanceMonth(month('2026-02', 0, 0)), fromFinanceMonth(month('2026-01', 1000, 10))), /zero/);
console.log('Finance performance: source reconciliation, weighted YTD, missing months/days, matching card deltas, full-month authority, zero baselines and revenue drivers passed.');

const uncovered = { ...trends[2], revenueCovered: false, missingDates: ['2026-01-04'] };
assert.equal(fromFinanceMonth(uncovered).revenue, null, 'Unverified daily subtotals cannot stand in for a full monthly or YTD total');
