import assert from 'node:assert/strict';
import { currentGpsPresence } from '../lib/schedule-gps-presence';
const now = Date.parse('2026-09-10T16:02:00Z');
const job = { appointmentId: 'one', location: { latitude: 29.97, longitude: -90.07 }, appointmentStartMinutes: 660, appointmentEndMinutes: 720, status: 'Confirmed' };
const points = [0,1,2,3].map(i => ({ ...job.location, timestamp: new Date(now - (3-i)*60_000).toISOString(), continuousUntil: null }));
const truck = { truck: 'Truck# 3', ...job.location, lastGpsUpdate: points.at(-1)!.timestamp, routePoints: points };
assert.equal(currentGpsPresence(job, [truck], [job], now)?.truck, 'Truck 3');
assert.equal(currentGpsPresence(job, [{ ...truck, routePoints: points.slice(-1) }], [job], now), undefined, 'One nearby point is a drive-by, not a visit');
assert.equal(currentGpsPresence(job, [truck], [job], now + 11*60_000)?.current, false, 'Preserve stale dwell as last reported, never current');
assert.equal(currentGpsPresence(job, [truck], [job], now + 13*3600_000), undefined, 'Old history must not become today current presence');
assert.equal(currentGpsPresence(job, [truck], [job, { ...job, appointmentId: 'two' }], now), undefined, 'Two nearby appointments cannot be assigned the same inferred visit');
assert.equal(currentGpsPresence(job, [truck, { ...truck, truck: 'Truck 6' }], [job], now), undefined, 'Multiple trucks need resolved visit evidence');
assert.equal(currentGpsPresence(job, [{ ...truck, latitude: 30.4 }], [job], now), undefined, 'Current position outside clears fallback');
assert.equal(currentGpsPresence({ ...job, status: 'Completed' }, [truck], [job], now), undefined);
assert.equal(currentGpsPresence(job, [{ ...truck, routePoints: [{ ...points[0], timestamp: new Date(now-30*60_000).toISOString() }, points[3]] }], [job], now), undefined, 'No bridging a telemetry outage');
assert.equal(currentGpsPresence({ ...job, location: null }, [truck], [job], now), undefined);
console.log('GPS presence: continuous dwell, current location, stale GPS, drive-bys, ambiguity and closed jobs passed.');
const early = { ...job, truck: 'Truck# 3', appointmentStartMinutes: 780, appointmentEndMinutes: 840 };
assert.equal(currentGpsPresence(early, [truck], [early], now)?.truck, 'Truck 3', 'An assigned crew physically onsite may arrive more than ninety minutes early');
assert.equal(currentGpsPresence({ ...early, truck: 'Unassigned' }, [truck], [{ ...early, truck: 'Unassigned' }], now), undefined, 'An unrelated early pass must not become an appointment arrival');
