import assert from 'node:assert/strict';
import { closeoutPaymentFacts } from '../lib/closeout-payment-verification';
import { combinedCloseoutAlerts } from '../lib/combined-closeout-alerts';
import { toOperationalAlert } from '../lib/operational-alert-presentation';
import type { PaymentReconciliationView } from '../lib/payment-reconciliation';
import type { SlackDigestMessage } from '../lib/slack-digest';
const row={job_id:'JK4079177',closeout:{payments:[{method:'Credit Card',detail:'***2463',amount:'$244.73'}]}};
const matched={date:'2026-09-06',jkNumber:'JK4079177',paidAmount:244.73,cardLastFour:'2463',reconciliation:'Matched',qboTransactionId:'txn-123',qboStatus:'Completed'};
const view={merchantCollector:'qbo-accounting-api',merchantCenterAvailable:true,merchantCenterFresh:true,paymentsByJob:[matched]} as PaymentReconciliationView;
const status=(v:PaymentReconciliationView,r=row)=>closeoutPaymentFacts(r,v).find(f=>f.label==='Card verification')?.value;
assert.equal(status(view),'Verified against QuickBooks');
for(const patch of [{paidAmount:203.94},{jkNumber:'JK4999999'},{cardLastFour:'9999'},{qboTransactionId:null},{qboStatus:'Voided'}]) assert.notEqual(status({...view,paymentsByJob:[{...matched,...patch}]} as PaymentReconciliationView),'Verified against QuickBooks');
assert.equal(status({...view,merchantCenterFresh:false}),'Awaiting fresh QuickBooks data');
assert.notEqual(status({...view,merchantCollector:'merchant-center'}),'Verified against QuickBooks');
assert.match(status({...view,paymentsByJob:[{...matched,reconciliation:'Needs review'}]} as PaymentReconciliationView)!,/Needs review/);
assert.notEqual(status({...view,paymentsByJob:[matched,{...matched,qboTransactionId:'txn-other'}]} as PaymentReconciliationView),'Verified against QuickBooks');
assert.notEqual(status(view,{...row,closeout:{payments:[...row.closeout.payments,...row.closeout.payments]}}),'Verified against QuickBooks');
assert.equal(status(view,{...row,closeout:{payments:[{method:'Cash',detail:'',amount:'$20.00'}]}}),undefined);
assert.equal(closeoutPaymentFacts(row,view).find(f=>f.label==='Payment')?.value,'Card ending 2463 ($244.73)');
const msg=(id:string,text:string):SlackDigestMessage=>({id,rawText:text,text,timestamp:'2026-09-06T17:00:00Z',channel:'#truck-4',threadReply:false});
const closed={...msg('closeout',':moneybag: *Job Closed*\nJK4079177'),closeout:{jobNumber:'JK4079177',lines:['Total: $203.94','Tips: $40.79'],href:'/jobs'},photos:[{url:'/photo.jpg',category:'After',fileName:'photo.jpg'}]} as SlackDigestMessage;
const payment=msg('payment',':credit_card: *Payment recorded*\n*Job:* JK4079177\n*Payment:* Card ending 2463 ($244.73)');
const combined=combinedCloseoutAlerts([payment,closed], [row],view);
assert.equal(combined.length,1);assert.equal(combined[0].id,'closeout');assert.equal(combined[0].photos?.length,1);
assert.equal(combined[0].facts.find(f=>f.label==='Job total')?.value,'$203.94');
assert.equal(combined[0].facts.find(f=>f.label==='Tips')?.value,'$40.79');
assert.equal(combined[0].facts.find(f=>f.label==='Card verification')?.value,'Verified against QuickBooks');
assert.equal(combinedCloseoutAlerts([payment],[],view).length,1,'Do not lose a payment before closeout arrives');
assert.equal(combinedCloseoutAlerts([closed,{...closed,id:'duplicate'}],[row],view).length,1);
for(const label of ['On-site','Arrival','Departure']) assert.equal(toOperationalAlert(msg(label,`:truck: *Truck 4 ${label}*\nJK4079177\n12:00 PM\nCustomer`)).label,label==='On-site'?'Arrival':label);
console.log('Closeout consolidation and transaction-level QBO verification passed.');
