import assert from 'node:assert/strict';
import { presentDrivingScores, memberDrivingScores } from '../lib/desktop-driving-scores';
import { drivingSummary } from '../desktop-ui/lib/driving-score';
const row = {truck:'Truck# 6', assigned_drivers:['Driver One'], opscenter_driving_score:80, driver_score_status:'Confirmed', confidence_status:'Confirmed', weighted_alert_availability:{harshBraking:true}, weighted_alert_counts:{harshBraking:0}, alert_deductions:{harshBraking:0}};
const rows = presentDrivingScores('2026-09-12', [row]);
assert.equal(rows[0].score,80);
assert.equal(rows[0].events.find(event=>event.label==='Harsh Braking')?.deduction,0);
assert.equal(rows[0].events.find(event=>event.label==='Phone Use')?.deduction,null);
assert.equal(memberDrivingScores(rows,'Driver One','Truck# 6')[0].attribution,'confirmed');
assert.equal(memberDrivingScores(rows,'Navigator','Truck# 6')[0].attribution,'truck');
assert.deepEqual(memberDrivingScores(rows,'Other','Truck# 4'),[]);
assert.equal(presentDrivingScores('2026-09-12',[{...row,assigned_drivers:['Driver One','Driver Two']}])[0].attribution,'review');
assert.equal(presentDrivingScores('2026-09-12',[{...row,confidence_status:'Partial'}])[0].attribution,'review');
assert.equal(presentDrivingScores('2026-09-12',[{...row,assigned_drivers:[]}])[0].attribution,'review');
assert.equal(presentDrivingScores('2026-09-12',[{...row,opscenter_driving_score:null}])[0].score,null);
const zero=presentDrivingScores('2026-09-11',[{...row,opscenter_driving_score:0}])[0];
assert.equal(zero.score,0);
assert.deepEqual(drivingSummary([...rows,zero,{...zero,truck:'Truck# 4'}, {...zero,date:'2026-09-10',attribution:'review'}]),{scoredDays:2,belowDays:1,reviewDays:1});
assert.equal(drivingSummary([{...rows[0],score:null}]).scoredDays,0);
console.log('Desktop driving scores: attribution, missing data, zero scores, and day counts passed.');
