import assert from 'node:assert/strict';
import { verifyAddressResult,verifyCensusAddress } from '../lib/desktop-address-verification';
const component=(type:string,value:string)=>({types:[type],long_name:value,short_name:value});
const result={address_components:[component('street_number','100'),component('route','Example Street'),component('postal_code','70125'),component('administrative_area_level_1','LA'),component('country','US')],geometry:{location:{lat:29.95,lng:-90.1},location_type:'ROOFTOP'}};
const payload={status:'OK',results:[result]};
assert.ok(verifyAddressResult('100 Example St, New Orleans, LA 70125',payload).location);
assert.ok(verifyAddressResult('Business Name 100 Example Street New Orleans, 70125',payload).location);
assert.equal(verifyAddressResult('101 Example Street, New Orleans, LA 70125',payload).location,null);
assert.equal(verifyAddressResult('100 Other Street, New Orleans, LA 70125',payload).location,null);
assert.equal(verifyAddressResult('100 Example Street, New Orleans, LA 70124',payload).location,null);
assert.equal(verifyAddressResult('100 Example Street, New Orleans, LA 70125',{status:'OK',results:[{...result,partial_match:true}]}).location,null);
assert.equal(verifyAddressResult('100 Example Street, New Orleans, LA 70125',{status:'OK',results:[result,result]}).location,null);
assert.equal(verifyAddressResult('100 Example Street, New Orleans, LA 70125',{status:'OK',results:[{...result,geometry:{...result.geometry,location_type:'APPROXIMATE'}}]}).location,null);
assert.equal(verifyAddressResult('100 Example Street, New Orleans, LA 70125',{status:'REQUEST_DENIED'}).reason,'Geocoding REQUEST_DENIED');
const cityResult={...result,address_components:[...result.address_components,component('locality','New Orleans')]};
assert.ok(verifyAddressResult('100 Example New Orleans, LA 70125',{status:'OK',results:[cityResult]}).location,'An omitted road type is safe with the exact following city');
assert.equal(verifyAddressResult('100 Example Other City, LA 70125',{status:'OK',results:[cityResult]}).location,null);
assert.equal(verifyAddressResult('100 Example Heights New Orleans, LA 70125',{status:'OK',results:[cityResult]}).location,null,'Do not accept a different street sharing a prefix');
assert.equal(verifyAddressResult('100 Example New Orleans, LA 70124',{status:'OK',results:[cityResult]}).location,null);
assert.equal(verifyAddressResult('100 Example New Orleans, LA 70125',{status:'OK',results:[{...cityResult,partial_match:true}]}).location,null);
const renamedRoute={...cityResult,address_components:cityResult.address_components.map(c=>c.types.includes('route')?component('route','South Norman C. Francis Parkway'):c)};
assert.ok(verifyAddressResult('100 South Norman Francis Parkway, New Orleans, LA 70125',{status:'OK',results:[renamedRoute]}).location);
assert.equal(verifyAddressResult('100 North Norman Francis Parkway, New Orleans, LA 70125',{status:'OK',results:[renamedRoute]}).location,null,'Direction remains significant');
console.log('Address verification: exact house/street/ZIP, aliases, business prefixes, partial matches, ambiguous results, and provider failure passed.');

const censusMatch={matchedAddress:'100 EXAMPLE ST, NEW ORLEANS, LA, 70125',addressComponents:{zip:'70125',state:'LA',city:'NEW ORLEANS'},coordinates:{x:-90.1,y:29.95}};
assert(verifyCensusAddress('100 Example St New Orleans LA 70125',{result:{addressMatches:[censusMatch]}}).location);
assert.equal(verifyCensusAddress('101 Example St New Orleans LA 70125',{result:{addressMatches:[censusMatch]}}).location,null);
assert.equal(verifyCensusAddress('100 Example St New Orleans LA 70124',{result:{addressMatches:[censusMatch]}}).location,null);
assert.equal(verifyCensusAddress('100 Example St New Orleans LA 70125',{result:{addressMatches:[censusMatch,censusMatch]}}).location,null);
const hospital={matchedAddress:'1014 W ST CLAIRE BLVD, GONZALES, LA, 70737',addressComponents:{zip:'70737',state:'LA',city:'GONZALES'},coordinates:{x:-90.931727047708,y:30.208176890499}};
const full='Our Lady Of The Lake St. Elizabeth 1014 W St Clare Blvd Suite 3110 Gonzales, LA 70737';
assert.ok(verifyCensusAddress(full,{result:{addressMatches:[hospital]}}).location,'Read business, house, suite, locality and ZIP together');
assert.equal(verifyCensusAddress(full.replace('1014','1015'),{result:{addressMatches:[hospital]}}).location,null);
assert.equal(verifyCensusAddress(full.replace('70737','70734'),{result:{addressMatches:[hospital]}}).location,null);
assert.equal(verifyCensusAddress(full.replace(' W St',' E St'),{result:{addressMatches:[hospital]}}).location,null);
assert.equal(verifyCensusAddress(full.replace('Gonzales','Other City'),{result:{addressMatches:[hospital]}}).location,null,'Alias must not cross localities');
assert.ok(verifyCensusAddress('Business 84 Location 2, 100 Example St Suite 3 New Orleans LA 70125',{result:{addressMatches:[censusMatch]}}).location,'Business/unit numbers must not replace the street number');
assert.equal(verifyCensusAddress('100 Example St New Orleans LA 70125 or 200 Other St New Orleans LA 70125',{result:{addressMatches:[censusMatch]}}).location,null,'Two street addresses require review');
