import assert from 'node:assert/strict';
import {gpsTripColor,gpsTripDisplay,unassignedGpsColor} from '../desktop-ui/lib/gps-trip-display';
import type {TruckGpsRoute} from '../desktop-ui/lib/gps-route-contract';
const points=[0,1,2,3,4,5].map(i=>({timestamp:`2026-09-11T13:0${i}:00.000Z`,latitude:30+(i%2)*.001,longitude:-90}));
const trips=[0,2].map((i,index)=>({id:`trip-${index}`,number:index+1,departure:points[i].timestamp,arrival:points[i+1].timestamp,from:{...points[i],address:'Start'},to:{...points[i+1],address:'Stop'}}));
const route:TruckGpsRoute={date:'2026-09-11',truck:'Truck 3',status:'available',sourceVersion:'current',observedAt:null,coveredThrough:null,points,paths:[points.slice(0,2),points.slice(2,4)],gapLinks:[points.slice(4,6)],trips,gaps:2,rejected:0};
const aligned={...route,streets:{sourceVersion:'current',status:'available' as const,unmatched:0,paths:[0,2,4].map(sourceEdge=>({sourceEdge,kind:'matched' as const,points:points.slice(sourceEdge,sourceEdge+2)}))}};
const display=gpsTripDisplay(aligned);
assert.deepEqual(display.paths.map(p=>p.sourceEdge),[0,2,4],'Never join excluded gaps');
assert.deepEqual(display.paths.map(p=>p.trip?.number),[1,2,undefined],'Repeated coordinates are attributed by time, not location');
assert.deepEqual(display.paths.map(p=>p.color),[gpsTripColor(1),gpsTripColor(2),unassignedGpsColor]);
assert.equal(new Set(Array.from({length:32},(_,i)=>gpsTripColor(i+1))).size,32);
const selected=gpsTripDisplay(aligned,'trip-1');
assert.equal(selected.paths.length,1);assert.equal(selected.paths[0].color,display.paths[1].color,'Trip color is stable when isolated');
assert.equal(selected.isolated.length,0,'Other trips do not reappear as points');
const streets={sourceVersion:'current',status:'partial' as const,unmatched:2,paths:[{sourceEdge:2,kind:'estimated' as const,points:[points[2],{latitude:30.002,longitude:-90.002},points[3]]}]};
assert.equal(gpsTripDisplay({...route,streets}).paths[0].points.length,3,'Use aligned geometry for its exact source edge');
assert.equal(gpsTripDisplay({...route,streets}).paths.length,1,'Unmatched edges never invent straight road routes');
assert.equal(gpsTripDisplay({...route,streets}).isolated.length,4,'Unmatched GPS evidence remains visible as points');
assert.equal(gpsTripDisplay({...route,streets:{...streets,sourceVersion:'old'}}).paths.length,0,'Never use stale road alignment');
assert.equal(gpsTripDisplay(route).paths.length,0,'Missing alignment cannot draw cross-country lines');
assert.equal(gpsTripDisplay({...route,paths:[],gapLinks:[]}).paths.length,0,'Trip endpoints alone never invent a route');
assert.equal(gpsTripDisplay({...route,paths:[],gapLinks:[]}).isolated.length,6);
console.log('Trip display checks passed: source-time colors, selection, repeated streets, sparse links, disconnected outages, partial and stale alignment, no straight-line fallback.');
