import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {readAddressMapFallback} from '../lib/address-map-fallback';
import {parishAddressQuery} from '../lib/parish-service-address';
import {osmServiceAddressQuery} from '../lib/osm-service-address';
import {geocodioAddressQuery} from '../lib/geocodio-service-address';
import {normalizeServiceAddress} from '../lib/service-address-format';
import {planningLocation} from '../lib/planning-geocodes';
import {scheduleMapLocation,needsScheduleMapLocation,needsScheduleAddressVerification,type ScheduleAppointment} from '../desktop-ui/lib/schedule-contract';
import {stopOrderMap} from '../desktop-ui/lib/stop-order-map';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'map-fallback-'));
const old={...process.env};
process.env.OPSBOT_DATA_DIR=root;process.env.OPSCENTER_DATA_DIR=root;
process.env.OSM_ADDRESS_CACHE_DIR=path.join(root,'cache/osm-address-lookups');
process.env.GEOCODIO_FREE_STATE_FILE=path.join(root,'geocodio.json');
process.env.SERVICE_ADDRESS_CACHE_DIR=path.join(root,'cache/verifications');
const now=Date.now(),hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const save=(p:string,d:unknown)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(d));};
try {
 const address='123 Example Wind Blvd Mandeville, LA 70471',q=parishAddressQuery(address)!;
 const parishFile=path.join(root,'cache/parish-address-lookups',hash(q.url)+'.json');
 const feature={attributes:{OBJECTID:1,ADDRESS:'123 EXAMPLE WIND LN',CITY_L:'MANDEVILLE',ZIP_CODE:70471},geometry:{x:-90.05,y:30.45}};
 const parish=(features:unknown[],expires=now+60000)=>save(parishFile,{expires,payload:{spatialReference:{wkid:4326},features}});
 parish([feature,{...feature,attributes:{...feature.attributes,OBJECTID:2,ADDRESS:'123 OTHER ST'}}]);
 const approximate=readAddressMapFallback(address,now)!;
 assert.ok(approximate);assert.match(approximate.matchedAddress,/EXAMPLE WIND LN/);
 assert.equal(planningLocation(address,{}),null,'Display evidence cannot become verified planning/visit evidence');
 const job={recordId:'one',status:'Confirmed',location:null,mapFallback:approximate} as ScheduleAppointment;
 assert.equal(needsScheduleAddressVerification(job),true);
 assert.equal(needsScheduleMapLocation(job),false);
 assert.deepEqual(scheduleMapLocation(job),feature.geometry&&{latitude:30.45,longitude:-90.05});
 const model=stopOrderMap([job,{...job,recordId:'two'}],[]);
 assert.equal(model.stops.length,2);assert.equal(model.paths.length,0,'Approximate points cannot fabricate road legs');
 assert.deepEqual(scheduleMapLocation({...job,location:{latitude:30.4,longitude:-90.1}}),{latitude:30.4,longitude:-90.1},'Verified result supersedes fallback');
 parish([feature,{...feature,geometry:{x:-90.1,y:30.5}}]);assert.equal(readAddressMapFallback(address,now),null,'Conflicting candidates stay unresolved');
 parish([{...feature,attributes:{...feature.attributes,ADDRESS:'124 EXAMPLE WIND LN'}}]);assert.equal(readAddressMapFallback(address,now),null);
 parish([{...feature,attributes:{...feature.attributes,ADDRESS:'123 N EXAMPLE WIND LN'}}]);assert.equal(readAddressMapFallback(address,now),null,'Direction must not disappear');
 parish([feature],now-1000);assert.equal(readAddressMapFallback(address,now)?.stale,true);
 parish([feature],now-8*86400_000);assert.equal(readAddressMapFallback(address,now),null);
 parish([{...feature,geometry:{x:0,y:0}}]);assert.equal(readAddressMapFallback(address,now),null);
 const outside='123 N 10th Ave, Pensacola, 32503';
 const osmParams=new URLSearchParams({q:osmServiceAddressQuery(outside)!,format:'jsonv2',addressdetails:'1',limit:'5',countrycodes:'us'});
 const osmFile=path.join(process.env.OSM_ADDRESS_CACHE_DIR!,hash('search?'+osmParams)+'.json');
 const osm={osm_type:'way',osm_id:10,lat:'30.43',lon:'-87.20',address:{house_number:'123',road:'North 10th Avenue',city:'Pensacola',state:'Florida',postcode:'32503',country_code:'us'}};
 save(osmFile,{expires:now+60000,payload:[osm]});assert.ok(readAddressMapFallback(outside,now),'Out-of-state addresses can display without Louisiana bounds');
 save(osmFile,{expires:now+60000,payload:[osm,{...osm,lon:'-87.3'}]});assert.equal(readAddressMapFallback(outside,now),null);
 const interpolated='123 Canal St, New Orleans, 70115',gq=geocodioAddressQuery(interpolated)!;
 save(process.env.GEOCODIO_FREE_STATE_FILE!,{schema:1,cache:{[hash(normalizeServiceAddress(gq))]:{expires:now+60000,payload:{results:[{address_components:{number:'123',formatted_street:'Canal St',city:'New Orleans',state_province:'LA',postal_code:'70119',country:'US'},location:{lat:29.97,lng:-90.09},accuracy_type:'range_interpolation'}]}}}});
 assert.match(readAddressMapFallback(interpolated,now)?.detail||'',/Estimated position along the street/);
 save(osmFile,{expires:now+60000,payload:[null]});assert.equal(readAddressMapFallback(outside,now),null,'Corrupt evidence fails without breaking schedule');
 console.log('Map fallback: coverage, approximation, geography, ambiguity, stale evidence and verification isolation passed.');
} finally {process.env=old;fs.rmSync(root,{recursive:true,force:true});}
