import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomBytes, randomUUID } from 'node:crypto';
import { createCrewPhoneEnrollment, enrollCrewPhone } from '../lib/crew-phone-store';
import { requireCrewPhone, requireCrewReady } from '../lib/crew-phone-http';
import { saveCrewDay, readCrewDay } from '../lib/crew-phone-day';
import { crewInspectionState } from '../lib/crew-phone-inspection';
import { chicagoDateKey } from '../lib/chicago-date';
import { CREW_PHONE_COOKIE } from '../lib/crew-phone';
import { INSPECTION_SECTIONS } from '../lib/truck-inspection';
import { connectInspectionPhone, submitTruckInspection } from '../lib/truck-inspection-store';
import { GET, POST } from '../app/api/crew-jobs/inspection/route';
import { GET as currentJob } from '../app/api/crew-jobs/current/route';

async function main() {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'waypoint-day-'));
  process.env.OPS_CREW_PHONE_DIR=path.join(root,'phones');
  process.env.OPS_TRUCK_INSPECTION_DIR=path.join(root,'inspections');
  process.env.OPS_CREW_DISPATCH_DIR=path.join(root,'dispatch');
  process.env.OPSCENTER_LOGIN_RATE_LIMIT_FILE=path.join(root,'attempts.json');
  process.env.OPS_CREW_ROSTER_JSON=JSON.stringify([{employee:'Test Driver',username:'test.driver',active:true}]);
  const origin='https://waypoint.example.invalid';
  const token=randomBytes(32).toString('hex');
  const request=(body?:unknown,query='')=>new Request(`${origin}/api/crew-jobs/inspection${query}`,{method:body?'POST':'GET',headers:{Cookie:`${CREW_PHONE_COOKIE}=${token}`,Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
  try {
    const phone=enrollCrewPhone(createCrewPhoneEnrollment('Truck 1','Test phone','manager').code,token);
    assert.equal((await GET(new Request(request().url))).status,401);
    assert.equal((await GET(request())).status,409,'Setup must precede inspection');
    assert.equal((await currentJob(request())).status,409,'Setup must precede jobs');
    const date=chicagoDateKey(), setup={date,truck:'Truck 6',requestId:randomUUID(),expectedVersion:0,responsible:'Test Driver',driver:'Test Driver',navigators:[]};
    const day=saveCrewDay(phone,setup);
    assert.equal(requireCrewPhone(request()).truck,'Truck 6','Daily selection overrides enrollment default');
    assert.equal(readCrewDay(phone)?.truck,'Truck 6','Enrollment identity still reads daily truck');
    assert.deepEqual(saveCrewDay(phone,setup),day,'Retry keeps exact daily setup');
    assert.throws(()=>saveCrewDay(phone,{...setup,truck:'Truck 7'}),/already used/);
    assert.throws(()=>saveCrewDay(phone,{...setup,requestId:randomUUID(),truck:'Truck 10'}),/Choose the truck/);
    assert.equal((await currentJob(request())).status,409,'Direct job URL cannot skip inspection');
    const context=await (await GET(request())).json();
    assert.deepEqual(context.trucks,['Truck 6']);assert.equal(context.dayVersion,1);
    const report={requestId:randomUUID(),truck:'Truck 6',inspector:'Test Driver',odometer:'12345',fuel:'Full',loadLevel:'Empty',startedAt:new Date().toISOString(),answers:INSPECTION_SECTIONS.map(s=>({id:s.id,status:'good',notes:''})),photos:[],status:'clear',notes:'',initials:'TD'};
    const legacy=connectInspectionPhone(randomBytes(32).toString('hex'));
    submitTruckInspection(report,legacy.device);
    assert.equal(crewInspectionState(phone).status,'ready','A saved same-day truck inspection applies across crews');
    assert.equal((await POST(request({action:'submit',dayVersion:1,report:{...report,truck:'Truck 7'}}))).status,409);
    assert.equal((await POST(request({action:'submit',dayVersion:0,report}))).status,409);
    assert.equal((await POST(request({action:'submit',dayVersion:1,report:{...report,startedAt:new Date(Date.now()-86400000).toISOString()}}))).status,409);
    const saved=await (await POST(request({action:'submit',dayVersion:1,report}))).json();
    assert.equal(saved.report.truck,'Truck 6');
    assert.deepEqual((await (await POST(request({action:'submit',dayVersion:1,report}))).json()).report,saved.report,'Lost response retry retains one receipt');
    assert.deepEqual((await (await GET(request(undefined,`?requestId=${report.requestId}`))).json()).report,saved.report,'Receipt recovery is read-only');
    assert.equal(crewInspectionState(phone).status,'ready');
    assert.equal(requireCrewReady(request()).truck,'Truck 6');
    assert.equal((await currentJob(request())).status,200,'Jobs unlock after durable inspection');
    saveCrewDay(phone,{...setup,truck:'Truck 7',requestId:randomUUID(),expectedVersion:1});
    assert.equal(requireCrewPhone(request()).truck,'Truck 7');
    assert.equal(crewInspectionState(phone).status,'required','Changing setup invalidates old clearance');
    assert.equal((await currentJob(request())).status,409);
    assert.equal((await (await GET(request(undefined,`?requestId=${report.requestId}`))).json()).report,null,'Previous setup receipt cannot be relabeled');
    const stopped={...report,requestId:randomUUID(),truck:'Truck 7',status:'stop',notes:'Synthetic safety test',photos:[{section:'walk-around',data:'data:image/jpeg;base64,/9j/AA=='}]};
    assert.equal((await POST(request({action:'submit',dayVersion:2,report:stopped}))).status,200);
    assert.equal(crewInspectionState(phone).status,'blocked');
    assert.throws(()=>requireCrewReady(request()),/Do not operate/);
    assert.equal((await currentJob(request())).status,409);
    const other=enrollCrewPhone(createCrewPhoneEnrollment('Truck 7','Other phone','manager').code,randomBytes(32).toString('hex'));
    saveCrewDay(other,{...setup,truck:'Truck 7',requestId:randomUUID()});
    assert.equal(crewInspectionState(other).status,'blocked','The same-day stop report applies across crews');
    console.log('PASS: setup → assigned truck inspection → jobs; direct bypass, wrong truck/date/version, public report reuse, stop status, setup changes and cross-phone receipt isolation. Synthetic storage only.');
  } finally { fs.rmSync(root,{recursive:true,force:true}); }
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
