import assert from 'node:assert/strict';
import {applyClockOutCorrections,consolidateCrewClockOutAlerts} from '../lib/crew-clock-out-alerts';
import {toOperationalAlert} from '../lib/operational-alert-presentation';
import {deduplicateOperationalUpdates} from '../lib/operational-update-dedup';
import {combinedCloseoutAlerts} from '../lib/combined-closeout-alerts';
import {commandAlertWorkItemForSource} from '../lib/command-alert-workflow';
import type {SlackDigestMessage} from '../lib/slack-digest';
import type {DesktopCrewMember} from '../desktop-ui/lib/people-fleet-contract';
import type {WorkItem} from '../lib/platform/contracts';

const source=(id:string,kind:'clock'|'pay',name='Example Worker',stamp='2026-09-07T23:13:00Z',extra:Partial<SlackDigestMessage>={}):SlackDigestMessage=>{
  const rawText=kind==='clock' ? `*Krewe clocked out*\n*Krewe member:* ${name}\n*Clock out:* 06:10 PM\n*Hours:* 8.25`
    : `*Final daily pay*\n*Krewe member:* ${name}\n*Total pay:* $225.68\n*Hourly pay:* $188.70\n*Tips:* $36.98\n*Bonuses:* $0.00\n*Other pay:* $0.00`;
  return {id,timestamp:stamp,rawText,text:rawText,threadReply:false,channel:'#crew',...extra};
};
const clock=source('clock','clock'), pay=source('pay','pay');
const combine=(messages:SlackDigestMessage[])=>consolidateCrewClockOutAlerts(deduplicateOperationalUpdates(messages).map(toOperationalAlert));
const [merged]=combine([pay,clock]);
assert.equal(combine([pay,clock]).length,1);
assert.equal(merged.id,'clock');
assert.equal(merged.label,'Clock Out');
assert.equal(merged.timestamp,clock.timestamp);
assert.deepEqual(merged.sourceMessageIds,['clock','pay']);
assert.deepEqual(merged.facts.map(f=>f.label),['Krewe member','Clock out','Hours','Total pay','Hourly pay','Tips','Bonuses','Other pay']);
assert.equal(merged.facts.find(f=>f.label==='Total pay')?.value,'$225.68');
assert.equal(merged.facts.find(f=>f.label==='Bonuses')?.value,'$0.00','Recorded zeroes remain explicit');
assert.match(merged.href,/crew\?date=2026-09-07/);
assert.equal(merged.corrected,false,'Adding pay is not a correction to attendance');
assert.deepEqual(combine([clock]),[toOperationalAlert({...clock,sourceMessageIds:['clock']})],'Clock-out appears before final pay is available');
assert.equal(combine([pay])[0].label,'Final Daily Pay','Missing clock-out cannot be invented');
assert.equal(combine([clock,source('other','pay','Different Worker')]).length,2);
assert.equal(combine([clock,source('next-day','pay','Example Worker','2026-09-08T23:13:00Z')]).length,2);
assert.equal(combine([clock,source('reply','pay','Example Worker',undefined,{threadReply:true})]).length,2);
assert.equal(combine([clock,source('missing-name','pay','')]).length,2);
assert.equal(combine([clock,source('invalid','pay','Example Worker','invalid')]).length,2);
assert.equal(combine([clock,source('pay','pay','Worker, Example')]).length,1,'Legacy name ordering matches the publisher employee identity');
const latePay=source('late','pay','Example Worker','2026-09-08T05:30:00Z',{eventFingerprint:'crew_daily_pay:2026-09-07:example-worker'});
assert.equal(combine([clock,latePay]).length,1,'Explicit operating date supports pay posted after midnight');
assert.equal(combine([clock,latePay])[0].timestamp,clock.timestamp,'Late pay does not move the clock-out event');
const earlyMorning=source('overnight','clock','Example Worker','2026-09-08T04:59:00Z');
assert.equal(combine([earlyMorning,pay]).length,1,'Legacy dates use Chicago midnight');
const clockRetry={...clock,id:'clock-retry',timestamp:'2026-09-07T23:14:00Z',eventFingerprint:'crew_clock_out:2026-09-07:example-worker'};
const correctedPay={...pay,id:'pay-retry',timestamp:'2026-09-07T23:15:00Z',eventFingerprint:'crew_daily_pay:2026-09-07:example-worker',rawText:pay.rawText.replace('$225.68','$230.68').replace('$0.00','$5.00')};
const revisions=combine([{...clock,eventFingerprint:clockRetry.eventFingerprint},clockRetry,{...pay,eventFingerprint:correctedPay.eventFingerprint},correctedPay]);
assert.equal(revisions.length,1,'Delivery retries stay in one merged alert');
assert.equal(revisions[0].facts.find(f=>f.label==='Total pay')?.value,'$230.68');
assert.equal(revisions[0].corrected,true);
assert.deepEqual(new Set(revisions[0].sourceMessageIds),new Set(['clock','clock-retry','pay','pay-retry']));
assert.equal(combine([clock,{...clock,id:'second-shift',rawText:clock.rawText.replace('06:10 PM','08:00 PM')},pay]).length,3,'Distinct shifts are not silently merged');
const owned={entity:{id:'pay'},status:'in_progress',ownerActorId:'manager',version:4} as WorkItem;
const reviewed={entity:{id:'clock'},status:'acknowledged',version:2} as WorkItem;
assert.equal(commandAlertWorkItemForSource([owned,reviewed],merged),owned,'Existing pay follow-up survives the merged clock-out');
assert.equal(commandAlertWorkItemForSource([owned],merged)?.version,4,'Writes use the surviving action version');
const production=combinedCloseoutAlerts([pay,clock],[],{} as Parameters<typeof combinedCloseoutAlerts>[2]);
assert.equal(production.length,1,'Shared Command and workflow source projection performs consolidation');
assert.equal(production.find(alert=>alert.id===pay.id || alert.sourceMessageIds?.includes(pay.id))?.id,'clock','A stale client pay identity resolves to the merged event');
const correctedMember={name:'Example Worker',clockOut:'06:00 PM',hours:10.75,totalPay:264.1,labor:227.12,tips:36.98,bonuses:0,supplemental:0,issue:'',correction:{updatedAt:'2026-09-08T02:00:00Z'}} as DesktopCrewMember;
const changed=applyClockOutCorrections([merged],{date:'2026-09-07',members:[correctedMember]})[0];
assert.equal(changed.facts.find(f=>f.label==='Total pay')?.value,'$264.10');
assert.equal(changed.facts.find(f=>f.label==='Clock out')?.value,'06:00 PM');
assert.equal(changed.source,'OpsCenter'); assert.equal(changed.corrected,true);
assert.match(changed.facts.find(f=>f.label==='Pay basis')!.value,/Not synced to JunkWare/);
assert.equal(applyClockOutCorrections([merged],{date:'2026-09-06',members:[correctedMember]})[0],merged,'Another date cannot override alert pay');
assert.deepEqual(changed.sourceMessageIds,merged.sourceMessageIds,'Local correction retains the shared action identity');
console.log('Clock-out/pay checks passed: full details, employee/day identity, late pay, missing sources, distinct shifts, retries, corrections and surviving Control actions.');
