import { readDesktopLocalReceipt } from '@/lib/desktop-krewe';
import { AUTH_SESSION_COOKIE, verifyAuthSessionCookie, resolveRequestOrigin } from '@/lib/auth';
import { cookies } from 'next/headers';
import { readDesktopKrewe, runDesktopKreweAction, kreweActionVersions } from '@/lib/desktop-krewe';
import { chicagoDateKey } from '@/lib/report-dates';
import { opsRoleCan } from '@/lib/ops-roles';
import type { KreweView } from '../../../../desktop-ui/lib/people-fleet-contract';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'private, no-store, max-age=0'};
export async function GET(request:Request){const session=await verifyAuthSessionCookie((await cookies()).get(AUTH_SESSION_COOKIE)?.value||'');if(!session)return Response.json({error:'Authentication required.'},{status:401,headers});const params=new URL(request.url).searchParams;if(params.has('receipt')){try{const receipt=readDesktopLocalReceipt(params.get('receipt')||'',session.email,'krewe');return Response.json({receipt},{status:receipt?200:404,headers});}catch{return Response.json({error:'Saved result could not be read.'},{status:503,headers});}}const date=params.get('date')||chicagoDateKey();const view=(params.get('view')||'today') as KreweView;if(!['today','callin','payperiod','monthly'].includes(view))return Response.json({error:'Invalid Krewe view.'},{status:400,headers});if((view==='monthly'||view==='payperiod')&&!opsRoleCan(session.role,'finance.read'))return Response.json({error:'Manager access is required for payroll.'},{status:403,headers});try{const snapshot=readDesktopKrewe(date,view,session.role);return Response.json({...snapshot,members:snapshot.members.map(row=>({...row,actionVersions:snapshot.canWrite?kreweActionVersions(date,row.name):undefined}))},{headers});}catch{return Response.json({error:'Krewe sources could not be read.'},{status:503,headers});}}
export async function POST(request:Request){const session=await verifyAuthSessionCookie((await cookies()).get(AUTH_SESSION_COOKIE)?.value||'');if(!session)return Response.json({error:'Authentication required.'},{status:401,headers});if(request.headers.get('origin')&&request.headers.get('origin')!==resolveRequestOrigin(request))return Response.json({error:'Same-origin request required.'},{status:403,headers});const body=await request.json().catch(()=>null);if(!body||typeof body!=='object')return Response.json({error:'Invalid action.'},{status:400,headers});if(!opsRoleCan(session.role,body.action==='callin'?'operations.write':'sensitive.write'))return Response.json({error:'Your role cannot make this change.'},{status:403,headers});try{const receipt=runDesktopKreweAction(body,session.email,session.role);return Response.json({receipt,...(receipt.status==='failed'?{error:'The source rejected these values. No record was saved.'}:{})},{status:receipt.status==='verified'?200:receipt.status==='failed'?422:202,headers});}catch(error){return Response.json({error:error instanceof Error?error.message:'The action could not be verified.'},{status:409,headers});}}
